### DISCUSSION TITLE
Failure no such index [.opendistro_security]

### DISCUSSION THREAD

**Discussion by mrvdcsg** [Opster/opensearch-k8s-operator#424] [Q&A] [answered]
I created a new cluster with certificates signed by my CA. I added nodes.DN and created a separate client cert for admin.dn but no matter what I do I get "Not yet initialized (you may need to run securityadmin)". What am I missing? Do I have to do all custom securityconfig to enable the default security if I bring my own certificate? Does my CA cert need to be defined in caSecrets or can it be included in the TLS secret as the docs say?

```
spec:
  security:
    tls:  
      transport:  
        generate: false  
        perNode: false  
        secret: 
          name: opensearch-certs # Name of the secret that contains the provided certificate
        # caSecret: # Included in opensearch-certs
        #  name:  # Name of the secret that contains a CA the operator should use
        nodesDn: # List of certificate DNs allowed to connect
          - 'CN=xxxxx'
        adminDn: # List of certificate DNs that should get admin access
          - 'CN=admin-xxxxxx'
      http:
        generate: false 
        secret:
          name:  opensearch-certs
    config:
     adminSecret:
       name: openserach-admin-certs
```

I have spun my wheels on certificates for 2 days and can't seem to get past this. I tried to run securityadmin.sh manually in one of the pods without success as I couldn't actually find my admin certs. the tls-http and tls-transport certs were both in folders under config so I wasn't sure if the admin ones get put in the opensearch.keystore. Any help is hugely appreciated!
