### DISCUSSION TITLE
multiple auth types syntax

### DISCUSSION THREAD

**Discussion by treknado** [Opster/opensearch-k8s-operator#549] [Q&A] [answered]
Hello,

whats the syntax for multiple auth types?
like the official opensearch [documentation](https://opensearch.org/docs/latest/security/configuration/multi-auth/#enabling-multiple-authentication-options) suggest, i want to add  
```opensearch_security.auth.type: ["basicauth","openid"]```
to my configuration.

my error:
```
The OpenSearchCluster "my-first-cluster" is invalid: spec.dashboards.additionalConfig.opensearch_security.auth.type: Invalid value: "array": spec.dashboards.additionalConfig.opensearch_security.auth.type in body must be of type string: "array"
```

with ```opensearch_security.auth.type: "openid"``` everything is working like expected.

my configuration:
```
  dashboards:
    additionalConfig:
      #opensearch_security.auth.type: "openid"
      opensearch_security.auth.type: ["basicauth","openid"]
      opensearch_security.auth.multiple_auth_enabled: true
      opensearch_security.openid.connect_url: "https://my-url/realms/my-realm/.well-known/openid-configuration"
      opensearch_security.openid.base_redirect_url: "https://my-url/ogs"
      opensearch_security.openid.client_id: "xxx"
      opensearch_security.openid.client_secret: "xxx"
    annotations:
      sidecar.istio.io/inject: "false"
    version: 2.7.0
    enable: true
    basePath: "/logs"
    replicas: 1
    opensearchCredentialsSecret:
      name: dashboard-credentials-secret # This is the name of your secret that contains the credentials for Dashboards to use
    tls:
      enable: false
      generate: false
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
```

best regards,
treknado
