### DISCUSSION TITLE
ISMPolicy Question

### DISCUSSION THREAD

**Discussion by mrvdcsg** [Opster/opensearch-k8s-operator#696] [Q&A] [answered]
I am creating an ism policy to delete all security-auditlog-* indexes after 7 days as cleanup of these logs is not available by default. I see that creation of ism policies is now part of the newest operator version (though not yet part of a release). I deployed the operator via source rather than the v2.4 version so it would include these crd and while I don't get any errors, the ISM Policy doesn't get created. 

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchISMPolicy
metadata:
  name: auditlog-cleanup
  namespace: opensearch
spec:
  opensearchCluster:
    name: opensearch-cluster-1
  description: A policy that deletes security-auditlog indices after 7 days
  policyId: auditlog-cleanup
  defaultState: normal
  states:
    - name: normal
      actions: []
      transitions:
        - stateName: delete
          conditions:
            minIndexAge: "7d"
    - name: delete
      actions:
        - delete: {}
  ismTemplate:
    indexPatterns:
      - "security-auditlog-*"
```

To note, my cluster is in the "opensearch" namespace and the cluster name is "opensearch-cluster-1".  After this is run, I don't see any difference in the cluster including when I look for ISM Policy definitions.

GET _opendistro/_ism/policies
{
  "policies": [],
  "total_policies": 0
}

I don't think this is due to timing because it doesn't matter how long I wait and I know this is new functionality as of November 2023 but I have an environment deployed with flux and this is the most seamless way to create this policy on current and future clusters. 
Anyone else having this issue? Do you see anything I'm doing wrong? Anything to suggest trying? All help appreciated!
