### DISCUSSION TITLE
Customize log4j2.properties

### DISCUSSION THREAD

**Discussion by hollowdew** [Opster/opensearch-k8s-operator#764] [Q&A]
Hello,

I added the repository **https://opensearch-project.github.io/opensearch-k8s-operator/** and installed **opensearch-cluster** from **opensearch-operator/opensearch-cluster** using helm with the following values.yaml:

```
opensearchCluster:
  enabled: true
  general:
    httpPort: "9200"
    version: 2.8.0
    serviceName: "opensearch-cluster"
    drainDataNodes: true
    setVMMaxMapCount: true
  dashboards:
    enable: true
    replicas: 1
    tls:
      enable: false
      generate: false
    opensearchCredentialsSecret: # doesn't have to be the same as adminCredentialsSecret
      name: admin-credentials-secret
    resources:
      requests:
        memory: "8192Mi"
        cpu: "800m"
      limits:
        memory: "8192Mi"
        cpu: "800m"
  nodePools:
    - component: cluster-managers
      #diskSize: "10Gi" # 10 GiB HDD
      diskSize: "100Gi" # 100 GiB HDD
      replicas: 3
      roles:
        - "cluster_manager"
      resources:
        requests:
          #memory: "2048Mi" # 24 GiB
          #cpu: "1000m" # 4 Cores
          memory: "24576Mi" # 24 GiB
          cpu: "4000m" # 4 Cores
        limits:
          #memory: "2048Mi" # 24 GiB
          #cpu: "1000m" # 4 Cores
          memory: "24576Mi" # 24 GiB
          cpu: "4000m" # 4 Cores
    - component: data-nodes
      diskSize: "4096Gi" # 4 TiB HDD
      #diskSize: "10Gi" # 10 GiB HDD
      replicas: 3
      roles:
        - "data"
      resources:
        requests:
          cpu: "4000m" # 4 Cores
          memory: "24576Mi" # 24 GiB
          #memory: "2048Mi" # 24 GiB
          #cpu: "1000m" # 4 Cores
        limits:
          #memory: "2048Mi" # 24 GiB
          #cpu: "1000m" # 4 Cores
          memory: "24576Mi" # 24 GiB
          cpu: "4000m" # 4 Cores
  security:
    config:
      adminCredentialsSecret: # these are the admin credentials for the Operator to use
        name: admin-credentials-secret
      securityConfigSecret:  # this is the whole security configuration for OpenSearch
        name: securityconfig-secret
    tls:
      transport:
        generate: true
      http:
        generate: true
```
Can you tell me how to configure the **log4j2.properties** file via helm?
I want to configure the data nodes and manager nodes to log in json format.
Any help is much appreciated. 

Thank you!
