### DISCUSSION TITLE
How to add a S3 snapshot repository via values.yaml?

### DISCUSSION THREAD

**Discussion by mame-leadec** [Opster/opensearch-k8s-operator#859] [Q&A]
Hello,

i want to add a S3 snapshot repo via helm chart values. The S3 storage is [MinIO](https://min.io/product/s3-compatibility) pod which resides in the same namespace as the OpenSearchCluster. The bucket "default-bucket" is already configured/created. 

My values.yaml look like this: 

```yaml

opensearchCluster:
  .....

  general:
    keystore:
    - secret:
        name: my-secret
      keyMappings:
        # Renames key accessKey in secret to s3.client.default.access_key in keystore
        username: s3.client.default.access_key
        password: s3.client.default.secret_key
    pluginsList: ["repository-s3"]
    snapshotRepositories:
      - name: my_s3_repository_1
        type: s3
        settings:
          bucket: default-bucket
          endpoint: http://minio-0.minio-svc.opensearch.svc.cluster.local:9000
          path_style_access: true

```

**When the OpenSearch Cluster is up and running **no** snapshot repository is configured.** **Am i missing something?** 

 If i try later via REST API i can configure the snapshot repository and use it.:
 ```shell
curl -k -u admin:admin -X PUT "https://localhost:9200/_snapshot/my_s3_repository_1" -H 'Content-Type: application/json' -d'
{
  "type": "s3",
  "settings": {
    "bucket": "default-bucket",
    "endpoint": "http://minio-0.minio-svc.opensearch.svc.cluster.local:9000",
    "path_style_access": true
  }
}
'
```
So it seems the config parameter like bucket name and URL are correct.
