### DISCUSSION TITLE
OpensearchUser created with a custom resource returns Unauthorized

### DISCUSSION THREAD

**Discussion by t-salt02** [Opster/opensearch-k8s-operator#973] [Q&A]
I created an OpensearchUser using a custom resource.
I checked it with curl expecting a tagline, but got an Unauthorized response.

**Version**
OpenSearch: 2.17.1
Opensearch-k8s-operator: 2.7.0

**What I did.**
Following the user guide, I deployed the following:
https://github.com/opensearch-project/opensearch-k8s-operator/blob/main/docs/userguide/main.md#opensearch-users
- opensearch-k8s-operator
- opensearchCluster
- OpensearchUser
- OpensearchUserRoleBinding
- Secret (for password)

They are all in the same namespace.

user.yaml
```
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: kojo
  namespace: default
spec:
  opensearchCluster: 
    name: my-cluster
  passwordFrom:
    name: sample-user-password
    key: password
```
userrolebinding.yaml
```
apiVersion: opensearch.opster.io/v1
kind: OpensearchUserRoleBinding
metadata:
  name: sample-binding
  namespace: default
spec:
  opensearchCluster: 
    name: my-cluster
  users: 
    - kojo
  roles: 
    - all_access
```
It was confirmed that the user was created using the get users API.
```
$ curl -k -u admin:admin https://my-cluster.default.svc:9200/_plugins/_security/api/internalusers | jq "keys"
[
  "admin",
  "anomalyadmin",
  "kibanaro",
  "kibanaserver",
  "kojo",
  "logstash",
  "readall",
  "snapshotrestore"
]
$
```

**Problem**
I was hoping that executing the following command would return a tagline
`curl -k -u foo:bar https://my-cluster.default.svc:9200`

However, Unauthorized was returned.
There was no Error in the Operator's log.

How can I solve this problem?

**supplement**
Executing the create user API with the admin user created the user and returned the tagline.
https://opensearch.org/docs/latest/security/access-control/api/#create-user
