### ISSUE TITLE
How do I add additional labels and additional Env variables for mater nodes

### ISSUE THREAD

**Issue by NoorKumar** [Opster/opensearch-k8s-operator#135]
### Discussed in https://github.com/Opster/opensearch-k8s-operator/discussions/133

<div type='discussions-op-text'>

<sup>Originally posted by **NoorKumar** May 10, 2022</sup>
Hi Team,
I was trying to create the cluster using operator, I do not see the way to add any additional labels or any extra environment variables to any nodes (master nodes or data nodes). When I submit the cluster config file to operator to create cluster I would like add some labels and env variables. 
</div>

**Comment by NoorKumar** [comment]
`
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster
  namespace: opensearch-demo
spec:
  general:
    version: 1.3.0
    httpPort: 9200
    vendor: opensearch
    serviceName: my-cluster
  dashboards:
    version: 1.3.0
    enable: true
    replicas: 2
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 3
     # here I want to add my own labels along with whatever operator is adding, and env vars to the opensearch container. Operator should those labels and env vars to all the master nodes
      diskSize: "10Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "master"
    - component: nodes
      replicas: 2
     # here I want to add my own labels along with whatever operator is adding, and env vars to the opensearch container. Operator should those labels and env vars to all the data nodes
      diskSize: "10Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
`

If you look the above config file (the one which given in example), I do not have any way to add labels or env vars. I want to add few labels to master node and data node as well and operator can take those labels and operator can add it's own labels (whatever adding as of today). Same for Env vars, I will be using those env vars and labels later.

**Comment by jlamillan** [comment]
@NoorKumar 

New feature looks like:

```yaml
  nodePools:
    - component: nodes
      ...
      labels:
         myLabel: foo
         anotherLabel: bar
      env:
        - name: qux
          value: "quux"
        - name: quuz
          valueFrom:
            configMapKeyRef:
              name: quuz-configmap
              key: corge
```
