### ISSUE TITLE
Multitenant dashboards support

### ISSUE THREAD

**Issue by ekarlso** [Opster/opensearch-k8s-operator#137]
Is it possible to enable multitenancy in the opensearch-dashboards using the operator ?

**Comment by prudhvigodithi** [comment]
Hey @ekarlso, the default installation does not have this [multitenancy](https://github.com/opensearch-project/security/blob/main/securityconfig/config.yml#L70) enabled, however you can override this with your own kubernetes secret.
Example
```
spec:
  security:
    config: 
      securityConfigSecret:
        name: securityconfig-secret
```

**Comment by ekarlso** [comment]
Yes but you need to enable it for the dashboard too if not it will give you an error in Kibana (Dashboards) multitenant.

**Comment by prudhvigodithi** [comment]
> Yes but you need to enable it for the dashboard too if not it will give you an error in Kibana (Dashboards) multitenant.
Yes as I mentioned you need to enable that in your `config.yaml` file and pass it as secret to the operator as shown above
Just check this link as well
https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/#:~:text=Tenants%20in%20Kibana%20are%20spaces,shared%20between%20every%20Kibana%20user.

**Comment by swoehrl-mw** [comment]
@ekarlso Adding to what @prudhvigodithi said: 
You can add additional options to the dashboards config:
```yaml
spec:
  dashboards:
    additionalConfig:  # a map of string->string with extra optons that get added to opensearch_dashboards.yml
      opensearch_security.multitenancy.enabled: "true"
     ...
```
This way you should be able to add all needed options to configure multi-tenancy in dashboards.
