### ISSUE TITLE
integrate with cert-manager for TLS certificates

### ISSUE THREAD

**Issue by rursprung** [Opster/opensearch-k8s-operator#141]
it'd be great if there'd be the option for the OpenSearch operator to use [cert-manager](https://cert-manager.io/) to get the TLS certificates. that way, neither manual management of the certificates for OpenSearch nor a self-signed CA is needed. the setups with cert-manager will range from a self-signed CA for cert-manager (added benefit over the self-signed CA for OpenSearch: it's the same CA also for other things and is usually under strict control of an operations team) to proper public certificates (cert-manager can interface with various external CAs).

i see two options for this:
* get an intermediate CA certificate from cert-manager and use that to issue certificates for OpenSearch directly. big downside: not all security teams are happy with additional (intermediate) CAs and might reject this setup
* create a [`Certificate` CR](https://cert-manager.io/docs/usage/certificate/) for each TLS certificate needed, let cert-manager issue the certificates

i'd strongly suggest to go for the latter as it offers much better security (no additional intermediate CA) and is thus more compatible with security guidelines/requirements in various places.

**Comment by swoehrl-mw** [comment]
Hi @rursprung. Thanks for your suggestion.
With the current architecture we use and if we want to give each node its own certificate integrating cert-manager would currently not be possible.
What is possible (not with v1.0 but with master as soon as #152 is merged) is letting the user create the certificates with cert-manager and then supply them to the operator:

```yaml
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: default
spec:
  secretName: ca-cert
  duration: 9000h # ~1year
  renewBefore: 360h # 15d
  commonName: Test CA
  isCA: true
  privateKey:
    size: 2048
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    name: selfsigned-issuer
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: default
spec:
  ca:
    secretName: ca-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-certs
  namespace: default
spec:
  secretName: opensearch-certs
  duration: 9000h # ~1year
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS8
  dnsNames:
    - my-first-cluster
    - my-first-cluster-masters-0
    - my-first-cluster-masters-1
    - my-first-cluster-masters-2
    - my-first-cluster-bootstrap-0
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  commonName: Opensearch_Node
  issuerRef:
    name: ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-admin-certs
  namespace: default
spec:
  secretName: opensearch-admin-certs
  duration: 9000h # ~1year
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS8
  commonName: OpenSearch_Admin
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: ca-issuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: opensearch-dashboards-certs
  namespace: default
spec:
  secretName: opensearch-dashboards-certs
  duration: 9000h # ~1year
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    size: 2048
    algorithm: RSA
    encoding: PKCS8
  dnsNames:
    - my-first-cluster-dashboards
  usages:
    - signing
    - key encipherment
    - server auth
    - client auth
  issuerRef:
    name: ca-issuer
```
And the cluster spec:
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
    version: 1.3.1
    imagePullSecrets:
      - name: foobar
  dashboards:
    enable: true
    version: 1.3.0
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
    tls:
      enable: true
      generate: false
      secret:
        name: opensearch-dashboards-certs
  security:
    config:
      adminSecret:
        name: opensearch-admin-certs
    tls:
      transport:
        generate: false
        perNode: false
        secret:
          name:  opensearch-certs
        nodesDn: ["CN=Opensearch_Node", ] 
        adminDn: ["CN=OpenSearch_Admin", ]
      http:
        generate: false
        secret:
          name: opensearch-certs
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "3Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
```

**Comment by rursprung** [comment]
thanks for your reply. but your example has the shortcoming you mention: there's only one certificate for the whole cluster rather than one per node.
why couldn't you create one `Certificate` CR for each node (and for REST & transport layers on each, for 1.x where this distinction still exists) from within the operator?
when the operator does it then the whole certificate renewal is also taken care of, as the operator can coordinate the (hot) reloading of the certificates by the nodes, ensuring that all nodes continue to trust each other. when managing this from externally there's a big risk that the cluster will have to be taken offline for the certificate rollover (in your own example both the CA and the node certificates expire after one year, i.e. new node certificates will come from a new CA which won't be trusted by the existing nodes).

**Comment by swoehrl-mw** [comment]
>  why couldn't you create one `Certificate` CR for each node (and for REST & transport layers on each, for 1.x where this distinction still exists) from within the operator?

In the current architecture we use only one secret with certificates for all nodes (as we use StatefulSets we cannnot equip each pod with its own secret so the one secret has the certs for all nodes) and afaik cert-manager creates a new secret for each certificate so I see no easy way to get those approaches together. 

> when managing this from externally there's a big risk that the cluster will have to be taken offline for the certificate rollover

I agree, that is a risk and I think we need to extend the operator to better support this. And yeah, rolling over the certs and the CA at the same time would probably lead to a headache and cluster downtime.

**Comment by rursprung** [comment]
> In the current architecture we use only one secret with certificates for all nodes (as we use StatefulSets we cannnot equip each pod with its own secret so the one secret has the certs for all nodes) and afaik cert-manager creates a new secret for each certificate so I see no easy way to get those approaches together.

i briefly searched online for how ECK is doing it (because they're using a `StatefulSet` and AFAIK have per-node certificates) and found this discussion which i haven't read fully yet but seems to discuss also how to handle the per-node secrets in a `StatefulSet`: https://github.com/elastic/cloud-on-k8s/issues/1173
so they seem to have per-node certificates in a single secret.

i could imagine that the operator in our case could create the `Certificate` CR, then grab the content of the created `Secret` and put that into the `Secret` for the cluster (and monitor the original `Secret` from cert-manager for further changes)?

**Comment by kfox1111** [comment]
This feature, once merged could do what you want rather easily:
https://github.com/cert-manager/csi-driver/pull/82

Could then have the driver create certs per pod with its podname in the san.

Thanks,
Kevin

**Comment by rursprung** [comment]
thanks @kfox1111, i wasn't aware of this!
from their readme it seems that this however has one drawback: it won't work with the `SelfSigned` CA (though i'm not 100% sure whether that's only an issue when using a `SelfSigned` CA directly or also when using the `SelfSigned` CA to sign another CA and then use that ([which is their recommendation](https://cert-manager.io/docs/configuration/selfsigned/#bootstrapping-ca-issuers)):

> Note it is not possible to use SelfSigned Issuers with the CSI Driver. In order for cert-manager to self sign a certificate, it needs access to the secret containing the private key that signed the certificate request to sign the end certificate. This secret is not used and so not available in the CSI driver use case.

**Comment by kfox1111** [comment]
Yeah, not sure on that one. If it doesn't really support ca's managed by cert-manager in any form, seems like that functionality is something that should get added. It would be useful for all sorts of projects like this one.

**Comment by rursprung** [comment]
> This feature, once merged could do what you want rather easily: [cert-manager/csi-driver#82](https://github.com/cert-manager/csi-driver/pull/82)
> 
> Could then have the driver create certs per pod with its podname in the san.
> 
> Thanks, Kevin

just FYI: this has landed in csi-driver v0.3.0 two weeks ago: https://github.com/cert-manager/csi-driver/commit/23f70ec6447f00908582a87526f154e11e3d4179

**Comment by hari819** [comment]
will the operator restart the opensearch pods in case of certs automatically renewed by cert-manager?

or do we need to restart the pods manually ? , please could you confirm!

**Comment by gabriel-suela** [comment]
> Case closed, issued resolved - see below.
> 
> @swoehrl-mw Thanks for the example configuration in you above [comment](https://github.com/opensearch-project/opensearch-k8s-operator/issues/141#issuecomment-1135920157). However, that configuration has the nodes (_2.11.1_) issue the following exceptions:
> 
> ```
> [2024-03-12T08:46:00,522][ERROR][o.o.s.s.h.n.SecuritySSLNettyHttpServerTransport] [debezium-opensearch-nodes-1] Exception during establishing a SSL connection: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
> javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
> 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
> 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:365) ~[?:?]
> 	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
> 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:204) ~[?:?]
> 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
> 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736) ~[?:?]
> 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691) ~[?:?]
> 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
> 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
> 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679) ~[?:?]
> 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:309) ~[netty-handler-4.1.100.Final.jar:4.1.100.Final]
>         ...
> ```
> 
> And:
> 
> ```
> [2024-03-12T08:46:00,524][WARN ][o.o.h.AbstractHttpServerTransport] [debezium-opensearch-nodes-1] caught exception while handling client http traffic, closing connection Netty4HttpChannel{localAddress=/10.96.18.63:9200, remoteAddress=/10.96.2.218:56820}
> io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:499) ~[netty-codec-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[netty-codec-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:689) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:652) [netty-transport-4.1.100.Final.jar:4.1.100.Final]
>         ...
> Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: bad_certificate
> 	at sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[?:?]
> 	at sun.security.ssl.Alert.createSSLException(Alert.java:117) ~[?:?]
> 	at sun.security.ssl.TransportContext.fatal(TransportContext.java:365) ~[?:?]
> 	at sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:293) ~[?:?]
> 	at sun.security.ssl.TransportContext.dispatch(TransportContext.java:204) ~[?:?]
> 	at sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[?:?]
> 	at sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:736) ~[?:?]
> 	at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:691) ~[?:?]
> 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:506) ~[?:?]
> 	at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:482) ~[?:?]
> 	at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:679) ~[?:?]
> 	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:309) ~[netty-handler-4.1.100.Final.jar:4.1.100.Final]
>         ...
> ```
> 
> ~Do you (or anyone else) have an idea what causes this?~
> 
> Never mind - it was an incorrect (incomplete) `ServiceMonitor`. The messages originated from the Prometheus Scrapes failing due to missing configuration.


Can you share what did you do to solve this? im facing the exact same problem

**Comment by StanislavRud** [comment]
Hi @gabriel-suela
To cluster opensearch monitoring configuration, add "insecureSkipVerify: true"

`...
monitoring:
      enable: true
      tlsConfig:
        insecureSkipVerify: true
...`

**Comment by Pigueiras** [comment]
We were testing @swoehrl-mw in https://github.com/opensearch-project/opensearch-k8s-operator/issues/141#issuecomment-1135920157 and once the root CA gets renewed and you generate new cluster certificates with that new CA, you get a: 

```
PKIX path validation failed: java.security.cert.CertPathValidatorException
```

Because the privatekey of the CA have been rotated and the running nodes don't trust the new certificate from the renewed CA And basically you are force to do a full restart of the cluster to make it work.

We added the `rotationPolicy` to never to renew the CA with the same privatekey so it is still trusted by the rest of the nodes of the cluster.

```yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-certificate
  namespace: default
spec:
  secretName: ca-cert
  duration: 90000h # ~10years instead of 1year, that's what the operator CA uses too if I'm not mistaken
  renewBefore: 360h # 15d
  commonName: Test CA
  rotationPolicy: Never  # This one is important
  isCA: true
  privateKey:
    size: 2048
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    name: selfsigned-issuer
```
