### ISSUE TITLE
Can't overwrite namespace in helm chart. Fixed in main branch, can you please make a new release to artifacthub.io?

### ISSUE THREAD

**Issue by andloh** [Opster/opensearch-k8s-operator#153]
First of all, thanks for this operator. Excited about the development of this :D Hope I can somehow contribute aswell

There is something wrong in the logic that inserts custom namespaces in the `v1.0` release. Right now that screws up the clusterRoleBindings.

This seems to be fixed in `main`:

```bash
helm install --dry-run --debug opensearch-operator/. --generate-name --namespace=custom-namespace | grep -B 10 custom-namespace
```
```yaml
NAMESPACE: custom-namespace
--
kind: ClusterRoleBinding
metadata:
  name: opensearch-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opensearch-operator-manager-role
subjects:
- kind: ServiceAccount
  name: opensearch-operator-controller-manager
  namespace: custom-namespace
--
kind: ClusterRoleBinding
metadata:
  name: opensearch-operator-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opensearch-operator-proxy-role
subjects:
- kind: ServiceAccount
  name: opensearch-operator-controller-manager
  namespace: custom-namespace
 ```
 ```bash
git checkout v1.0

helm install --dry-run --debug opensearch-operator/. --generate-name --namespace=custom-namespace | grep -B 10 custom-namespace
```
```yaml
NAME: chart-1653418684
LAST DEPLOYED: Tue May 24 20:58:04 2022
NAMESPACE: custom-namespace
```
