### ISSUE TITLE
Parameter for setting heap size on all nodes

### ISSUE THREAD

**Issue by andloh** [Opster/opensearch-k8s-operator#154]
As of now, I see no possible way to setting a custom heap size on opensearch nodes. 

This cloud be a parameter in the spec or a ENV variable. 
Since this a pretty common setting, I think it would make more sense to have that option via the CRD.

This pr #149 would solve it, with the use of ENV vars. E.g `OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m`

**Comment by swoehrl-mw** [comment]
Hi @andloh. This is already possible today using the `jvm` option on nodePools:

```yaml
spec:
  # ...
  nodePools:
    - component: masters
      replicas: 3
      jvm: "-Xmx1024M -Xms1024M"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      # ...
```
You can also use it to set other Java options for the nodePool as the contents of `jvm` are supplied as `OPENSEARCH_JAVA_OPTS` to the nodePool.

Hope this helps.
