### ISSUE TITLE
Adding tolerations in values for operator helm chart has no effect. 

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#159]
Adding tolerations in values for operator helm chart has no effect. 

Even after adding values like below , helm chart install doesn't generate workload with tolerations

```
tolerations:
- key: "xxxxx"
  operator: "Exists"
  effect: "NoSchedule"
```
