### ISSUE TITLE
Persistence fields not recognized by operator 

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#169]
Persistence field not recognized by operator 

error from kubectl command 

```
k apply -f ./apps/opensearch-operator/os-cluster.yaml 
error: error validating "./apps/opensearch-operator/os-cluster.yaml": error validating data: ValidationError(OpenSearchCluster.spec.nodePools[0].persistence): unknown field "storageClass" in io.opster.opensearch.v1.OpenSearchCluster.spec.nodePools.persistence; if you choose to ignore these errors, turn validation off with --validate=false

```

operator helm chart version 1.0.1

below is the cluster manifest

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: example-cluster
spec:
  general:
    serviceName: example-cluster
    version: 1.3.1
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
  - component: masters
    nodeSelector: {"usedFor": "example"}
    jvm: "-Xmx1024M -Xms1024M"
    tolerations:
      - key: "usedFor"
        operator: "Exists"
        effect: "NoSchedule" 
    replicas: 3
    diskSize: "7Gi"
    resources:
       requests:
          memory: "2Gi"
          cpu: "500m"
       limits:
          memory: "2Gi"
          cpu: "500m"
    roles:
      - "master"
    persistence:
      storageClass: managed-standard-v1
      accessModes:
      - ReadWriteOnce
```

**Comment by swoehrl-mw** [comment]
Hi @KannappanSomu. Thanks for this report. Looks like we have an error in the docs. It should be:

```yaml
    persistence:
      pvc:
        storageClass: managed-standard-v1
        accessModes:
        - ReadWriteOnce
```

Can you try with that?
