### ISSUE TITLE
Volume re-sizing not compatible with azure disk ? 

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#170]
Hi , 

@prudhvigodithi @swoehrl-mw 

I have installed Opensearch operator on AKS  with custom storage classes & cluster manifest given below. 
Then I wanted to test the volume scaling as mentioned in the user guide  document  (allow volume expansion is set to true.) 
But it dint work as expected. 

**below is the message I get when I describe pvc :** 

```
$ k describe pvc data-devops-cluster-masters-0
Name:          data-devops-cluster-masters-0
Namespace:     opensearch-operator
StorageClass:  managed-standard-v1
Status:        Bound
Volume:        pvc-a5985da4-5604-4464-9d34-ceada29b667f
Labels:        opensearch.role=master
               opster.io/opensearch-cluster=devops-cluster
               opster.io/opensearch-nodepool=masters
Annotations:   pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: disk.csi.azure.com
               volume.kubernetes.io/storage-resizer: disk.csi.azure.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      7Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Used By:       devops-cluster-masters-0
Conditions:
  Type       Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----       ------  -----------------                 ------------------                ------  -------
  Resizing   True    Mon, 01 Jan 0001 00:00:00 +0000   Thu, 02 Jun 2022 10:57:55 +0200
Events:
  Type     Reason              Age                  From                                 Message
  ----     ------              ----                 ----                                 -------
  Normal   ExternalExpanding   2m37s                volume_expand                        CSI migration enabled for kubernetes.io/azure-disk; waiting for external resizer to expand the pvc
  Normal   Resizing            37s (x9 over 2m37s)  external-resizer disk.csi.azure.com  External resizer is resizing volume pvc-a5985da4-5604-4464-9d34-ceada29b667f
  Warning  VolumeResizeFailed  36s (x9 over 2m36s)  external-resizer disk.csi.azure.com  resize volume "pvc-a5985da4-5604-4464-9d34-ceada29b667f" by resizer "disk.csi.azure.com" failed: rpc error: code = Internal desc = failed to resize disk(/subscriptions/35c6af02-1a76-46b2-8da0-a80cca015920/resourceGroups/elastic-fluxv2-nrg/providers/Microsoft.Compute/disks/pvc-a5985da4-5604-4464-9d34-ceada29b667f) with error(Retriable: false, RetryAfter: 0s, HTTPStatusCode: 409, RawError: {
  "error": {
    "code": "OperationNotAllowed",
    "message": "Cannot resize disk pvc-a5985da4-5604-4464-9d34-ceada29b667f while it is attached to running VM /subscriptions/35c6af02-1a76-46b2-8da0-a80cca015920/resourceGroups/elastic-fluxv2-nrg/providers/Microsoft.Compute/virtualMachineScaleSets/aks-master1-22371257-vmss/virtualMachines/aks-master1-22371257-vmss_2. Resizing a disk of an Azure Virtual Machine requires the virtual machine 
to be deallocated. Please stop your VM and retry the operation."
  }
})
```

**storage class manifest :** 

```
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-premium-v1
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: Premium_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate
---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-standard-v1
parameters:
  cachingmode: ReadOnly
  kind: Managed
  storageaccounttype: StandardSSD_LRS
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Delete
volumeBindingMode: Immediate

```

**Cluster manifiest :** 

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: devops-cluster
spec:
  general:
    serviceName: devops-cluster
    version: 1.3.1
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
  - component: masters
    nodeSelector: {"usedFor": "Master"}
    jvm: "-Xmx1024M -Xms1024M"
    tolerations:
      - key: "usedFor"
        operator: "Exists"
        effect: "NoSchedule" 
    replicas: 3
    diskSize: "8Gi"
    resources:
       requests:
          memory: "2Gi"
          cpu: "500m"
       limits:
          memory: "2Gi"
          cpu: "500m"
    roles:
      - "master"
    persistence:
      pvc:
        storageClass: managed-standard-v1
        accessModes:
        - ReadWriteOnce
  - component: hot-datas
    additionalConfig:
      node.attr.temp: hot
    nodeSelector: {"usedFor": "Hot"}
    jvm: "-Xmx1024M -Xms1024M"
    tolerations:
      - key: "usedFor"
        operator: "Exists"
        effect: "NoSchedule" 
    replicas: 2
    diskSize: "50Gi"
    resources:
       requests:
          memory: "2Gi"
          cpu: "500m"
       limits:
          memory: "2Gi"
          cpu: "500m"
    roles:
      - "data"
    persistence:
      pvc:
        storageClass: managed-premium-v1
        accessModes:
        - ReadWriteOnce
  - component: warm-datas
    additionalConfig:
      node.attr.temp: warm
    nodeSelector: {"usedFor": "Warm"}
    jvm: "-Xmx1024M -Xms1024M"
    tolerations:
      - key: "usedFor"
        operator: "Exists"
        effect: "NoSchedule" 
    replicas: 2
    diskSize: "100Gi"
    resources:
       requests:
          memory: "2Gi"
          cpu: "500m"
       limits:
          memory: "2Gi"
          cpu: "500m"
    roles:
      - "data"
    persistence:
      pvc:
        storageClass: managed-standard-v1
        accessModes:
        - ReadWriteOnce
       
```

**Comment by prudhvigodithi** [comment]
Hey @KannappanSomu 
I was able to test the scaling in AWS with custom storage class and pass this to the `persistence.pvc` settings

StorageClass
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-test
provisioner: kubernetes.io/aws-ebs
allowVolumeExpansion: true
parameters:
  type: gp2
  fsType: ext4 
```

Cluster YAML
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: devops-cluster
spec:
  general:
    serviceName: devops-cluster
    version: 1.3.1
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
  nodePools:
  - component: masters
    jvm: "-Xmx1024M -Xms1024M"
    replicas: 1
    diskSize: "11Gi"
    roles:
      - "master"
    persistence:
      pvc:
        storageClass: gp2-test
        accessModes:
        - ReadWriteOnce
  - component: hot-datas
    additionalConfig:
      node.attr.temp: hot
    jvm: "-Xmx1024M -Xms1024M"
    replicas: 1
    diskSize: "11Gi"
    roles:
      - "data"
    persistence:
      pvc:
        storageClass: gp2-test
        accessModes:
        - ReadWriteOnce
  - component: warm-datas
    additionalConfig:
      node.attr.temp: warm
    jvm: "-Xmx1024M -Xms1024M"
    replicas: 1
    diskSize: "11Gi"
    roles:
      - "data"
    persistence:
      pvc:
        storageClass: gp2-test
        accessModes:
        - ReadWriteOnce
```
```
k  get pods
NAME                                                     READY   STATUS    RESTARTS       AGE
devops-cluster-dashboards-574cbcb7cc-ztwvl               1/1     Running   0              4m54s
devops-cluster-hot-datas-0                               1/1     Running   0              4m54s
devops-cluster-masters-0                                 1/1     Running   0              4m54s
devops-cluster-warm-datas-0                              1/1     Running   1 (4m1s ago)   4m54s
opensearch-operator-controller-manager-bc58884f6-cj9pl   2/2     Running   0              13m
```


<img width="1200" alt="Screen Shot 2022-06-02 at 7 02 09 AM" src="https://user-images.githubusercontent.com/28733332/171615752-067b0203-45ba-4c81-8d4e-119c6b4d9f43.png">

I have found support articles related to AKS, please check.
https://github.com/Azure/AKS/issues/1477
https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/master/docs/known-issues/sizegrow.md
