### ISSUE TITLE
OpenSearchCluster with adminCredentialsSecret only

### ISSUE THREAD

**Issue by elkh510** [Opster/opensearch-k8s-operator#182]
hi
try to deploy OpenSearchCluster with custom username and password 
but get error
```
1.654782696897091e+09	INFO	controller.opensearchcluster	Waiting for secret '' that contains the securityconfig to be created	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "opensearch", "namespace": "efk"}

```
cluster spec:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
spec:
  security:
    config:
      adminCredentialsSecret:
        name: opensearch-dashboard-admin-password
    tls:
      transport:
        generate: true
      http:
        generate: true
  confMgmt:
    VerUpdate: false
    autoScaler: false
    monitoring: false
    smartScaler: false
  general:
    serviceName: opensearch
    version: 1.3.2
    setVMMaxMapCount: true
  dashboards:
    enable: true
    version: 1.3.2
    replicas: 1
    opensearchCredentialsSecret:
      name: opensearch-dashboard-admin-password
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      additionalConfig:
        compatibility.override_main_response_version: "true"
        #plugins.security.ssl.http.enabled: "false"
      resources:
         limits:
            memory: "2Gi"
            cpu: "500m"
         requests:
            memory: "2Gi"
            cpu: "500m"
      jvm: "-Xmx1G -Xms1G"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - tooling
      roles:
        - "data"
        - "master"
      diskSize: "5Gi"
      persistence:
        pvc:
          storageClass: cluster-ssd
          accessModes:
            - ReadWriteOnce

```
