### ISSUE TITLE
opensearch dashboard additional config not working 

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#188]
Hi , 

As per documentation , added following additional config for dashboards, but looks like this is missing in CRD schema

```
dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    additionalConfig:
      opensearch_security.auth.type: "saml"
      opensearch.requestHeadersWhitelist: |
        ["securitytenant","Authorization","x-forwarded-for","x-auth-request-access-token", "x-auth-request-email", "x-auth-request-groups"]
      opensearch_security.multitenancy.enabled: "true"
```
      
      
      
Error: 

**dry-run failed, error: failed to create typed patch object: .spec.dashboards.additionalConfig: field not declared in schema.**
