### ISSUE TITLE
AdditionalConfig on nodePools or General is not being applied?

### ISSUE THREAD

**Issue by emil-jacero** [Opster/opensearch-k8s-operator#204]
Version image: v1.1 (built locally)
Version helm: v1.1 (built locally)

Hi,

I am trying to apply these settings to the cluster (opensearch.yml). I have tried adding them to the `general` config and the `nodePools`, as shown in the CRD documentation.

```
additionalConfig:
  s3.client.default.endpoint: "minio.example.com"
  s3.client.default.max_retries: "3"
  s3.client.default.protocol: "https"
```

This however does not apply the config to the ConfigMap but as env instead.
Is that the correct behavior?

Best regards,
Emil

**Comment by emil-jacero** [comment]
An update to this issue:

When adding the `additionalConfig` the operator seems to continuously terminating my nodes and rebuilding them. Cannot find anything in the operator log suggesting something is wrong, but that is not the behavior i am looking for. :)

My configuration:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: os-cluster-01
  namespace: opensearch
spec:
  general:
    serviceName: os-cluster-01
    version: 1.3.3
    imagePullPolicy: Always
    image: reg.example.com/opensearch:1.3.3-s3-plugin  # locally built image with the `repository-s3` plugin added and certificates
  security:
    tls:
      transport:
        perNode: true
        generate: true
      http:
        generate: true
    config:
      securityConfigSecret:
       name: security-config
      adminCredentialsSecret:
        name: admin-credentials
  dashboards:
    enable: true
    version: 1.3.3
    imagePullPolicy: Always
    image: reg.example.com/opensearch-dashboards:1.3.3  # locally built image with certificates
    replicas: 1
    tls:
      enable: true
      generate: true
    opensearchCredentialsSecret:
      name: kibanaserver-credentials
    additionalConfig:
      opensearch_security.cookie.secure: "true"
      opensearch.requestHeadersWhitelist: "['Authorization', 'securitytenant', 'security_tenant']"
      opensearch_security.multitenancy.enabled: "true"
      opensearch_security.multitenancy.tenants.enable_global: "true"
      opensearch_security.multitenancy.tenants.enable_private: "true"
      opensearch_security.multitenancy.tenants.preferred: "['Private', 'Global']"
      opensearch_security.multitenancy.enable_filter: "false"
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "5Gi"
      additionalConfig:
        s3.client.default.endpoint: "minio.example.com"
        s3.client.default.max_retries: "3"
        s3.client.default.protocol: "https"
      persistence:
        pvc:
          storageClass: longhorn
          accessModes:
            - ReadWriteOnce
      NodeSelector:
      env:
        - name: BACKUP_S3_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: backup-credentials
              key: access-key-id
        - name: BACKUP_S3_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: backup-credentials
              key: secret-access-key
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "1000m"
      roles:
        - "data"
        - "master"
```
