### ISSUE TITLE
Unable set node.role remote_cluster_client

### ISSUE THREAD

**Issue by chenyg0911** [Opster/opensearch-k8s-operator#208]
cluster.yml
```yaml
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "5Gi"
      persistence:
        emptyDir: {}
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
      - master
      - data
      - remote_cluster_client
      - ingest

```
pod env:
```
network.publish_host=test-elk-masters-0
OPENSEARCH_JAVA_OPTS=-Xmx512M -Xms512M -Dopensearch.transport.cname_in_publish_address=true
node.roles=master,data,ingest
OPENSEARCH_PASSWORD=admin
```
```
curl -u admin:admin -k https://localhost:9200/_cat/nodes?v
ip            heap.percent ram.percent cpu load_1m load_5m load_15m node.role master name
10.233.92.154           18          46  14    1.21    0.99     0.63 dim       -      test-elk-masters-1
10.233.96.139           32          46  12    0.53    0.64     0.63 dim       *      test-elk-masters-0
10.233.90.59            17          45  42    0.40    0.57     0.60 dim       -      test-elk-masters-2
```
