### ISSUE TITLE
Cluster won't start on ARM64 due to wrong init container

### ISSUE THREAD

**Issue by mtb-xt** [Opster/opensearch-k8s-operator#215]
Hi, trying to run an example cluster on AWS's ARM64 instances - I overrode images for cluster and for dashboards, but the cluster still fails because init container is hardcoded and is amd64 only :/ 

cluster.yaml:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: search-cluster
  namespace: logging
spec:
  general:
    serviceName: search-cluster
    version: 1.3.3
    image: opensearchproject/opensearch:1.3.3
  dashboards:
    enable: true
    version: 1.3.3
    image: opensearchproject/opensearch-dashboards:1.3.3 
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "20Gi"
      #image: opensearchproject/opensearch:1.3.3
      #NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
```

result:
```
  Normal   Started                 10m (x4 over 10m)    kubelet                  Started container init
  Normal   Pulling                 9m31s (x5 over 11m)  kubelet                  Pulling image "public.ecr.aws/opsterio/busybox:latest"

kubectl -n logging logs search-cluster-masters-0 -c init
standard_init_linux.go:228: exec user process caused: exec format error

❯ kubectl -n logging get statefulsets.apps search-cluster-masters -o yaml | grep -i image
        image: opensearchproject/opensearch:1.3.3
        imagePullPolicy: IfNotPresent
        image: public.ecr.aws/opsterio/busybox:latest
```
And it seems your repo images aren't multi-arch (hopefully, yet)...
