### ISSUE TITLE
Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING] & startupProbe error on dashboards verison 2.0.0

### ISSUE THREAD

**Issue by xikunyu** [Opster/opensearch-k8s-operator#219]
cluster.yaml
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
  namespace: opensearch-system
spec:
  general:
    serviceName: opensearch
    version: 2.0.0
    image: xxx.dkr.ecr.cn-northwest-1.amazonaws.com.cn/opensearch:2.0.0
  security:
    config:  # Everything related to the securityconfig
      securityConfigSecret:
        name:  securityconfig-secret
      #adminSecret:
      #  name:  # Name of a secret that contains the admin client certificate
      adminCredentialsSecret:
        name: admin-credentials-secret
    tls:
      transport:
        generate: true
      http:
        generate: true
  dashboards:
    enable: true
    version: 2.0.0
    image: xxx.dkr.ecr.cn-northwest-1.amazonaws.com.cn/opensearch-dashboards:2.0.0
    opensearchCredentialsSecret:
      name: admin-credentials-secret
    replicas: 1
    additionalConfig:
      #opensearch_security.auth.type: "proxy"
      opensearch.requestHeadersWhitelist: |
        ["securitytenant","Authorization","x-forwarded-for","x-auth-request-access-token", "x-auth-request-email", "x-auth-request-groups"]
      opensearch_security.multitenancy.enabled: "true"
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters-data-hot
      replicas: 2
      diskSize: "5Gi"
      NodeSelector:
      resources:
         requests:
            memory: "1Gi"
            cpu: "500m"
         limits:
            memory: "1Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
        - "ingest"
      additionalConfig:
        node.attr.type: hot
    - component: masters-data-cold
      replicas: 1
      diskSize: "5Gi"
      NodeSelector:
      resources:
         requests:
            memory: "1Gi"
            cpu: "500m"
         limits:
            memory: "1Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
        - "ingest"
      additionalConfig:
        node.attr.type: cold
```

pod status
```
[root@eks-test k8s_opensearch]# kubectl get pod -n opensearch-system 
NAME                                                      READY   STATUS      RESTARTS   AGE
opensearch-dashboards-67db4f7f79-wgmvw                    0/1     Running     1          4m52s
opensearch-masters-data-cold-0                            1/1     Running     0          41m
opensearch-masters-data-hot-0                             1/1     Running     0          41m
opensearch-masters-data-hot-1                             1/1     Running     0          38m
opensearch-operator-controller-manager-5df696864d-tkqrd   2/2     Running     0          42m
opensearch-securityconfig-update-qxvgq                    0/1     Completed   0          41m
```

dashboards log
```
[root@eks-test k8s_opensearch]# kubectl logs opensearch-dashboards-67db4f7f79-wgmvw -n opensearch-system 
{"type":"log","@timestamp":"2022-07-12T07:15:28Z","tags":["info","plugins-service"],"pid":7,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2022-07-12T07:15:29Z","tags":["warning","config","deprecation"],"pid":7,"message":"\"opensearch.requestHeadersWhitelist\" is deprecated and has been replaced by \"opensearch.requestHeadersAllowlist\""}
{"type":"log","@timestamp":"2022-07-12T07:15:30Z","tags":["info","plugins-system"],"pid":7,"message":"Setting up [37] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,inputControlVis,visualize,securityDashboards,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,discover,savedObjectsManagement,bfetch]"}
{"type":"log","@timestamp":"2022-07-12T07:15:33Z","tags":["info","savedobjects-service"],"pid":7,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
{"type":"log","@timestamp":"2022-07-12T07:15:34Z","tags":["info","savedobjects-service"],"pid":7,"message":"Starting saved objects migrations"}
{"type":"log","@timestamp":"2022-07-12T07:15:34Z","tags":["info","plugins-system"],"pid":7,"message":"Starting [37] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,inputControlVis,visualize,securityDashboards,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,discover,savedObjectsManagement,bfetch]"}
{"type":"log","@timestamp":"2022-07-12T07:15:36Z","tags":["listening","info"],"pid":7,"message":"Server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2022-07-12T07:15:37Z","tags":["info","http","server","OpenSearchDashboards"],"pid":7,"message":"http server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2022-07-12T07:15:41Z","tags":["error","plugins","securityDashboards"],"pid":7,"message":"StatusCodeError: OpenSearchException[java.util.concurrent.TimeoutException: Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)]; nested: TimeoutException[Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)];\n    at respond (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at HttpConnector.<anonymous> (/usr/share/opensearch-dashboards/node_modules/elasticsearch/src/lib/connectors/http.js:173:7)\n    at IncomingMessage.wrapper (/usr/share/opensearch-dashboards/node_modules/lodash/lodash.js:4991:19)\n    at IncomingMessage.emit (events.js:412:35)\n    at endReadableNT (internal/streams/readable.js:1334:12)\n    at processTicksAndRejections (internal/process/task_queues.js:82:21) {\n  status: 500,\n  displayName: 'InternalServerError',\n  path: '/_plugins/_security/tenantinfo',\n  query: {},\n  body: {\n    error: 'OpenSearchException[java.util.concurrent.TimeoutException: Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)]; nested: TimeoutException[Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)];'\n  },\n  statusCode: 500,\n  response: '{\"error\":\"OpenSearchException[java.util.concurrent.TimeoutException: Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)]; nested: TimeoutException[Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)];\"}',\n  toString: [Function (anonymous)],\n  toJSON: [Function (anonymous)]\n}"}
{"type":"log","@timestamp":"2022-07-12T07:15:41Z","tags":["warning","environment"],"pid":7,"message":"Detected an unhandled Promise rejection.\nOpenSearchException[java.util.concurrent.TimeoutException: Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)]; nested: TimeoutException[Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)]; :: {\"path\":\"/_plugins/_security/tenantinfo\",\"query\":{},\"statusCode\":500,\"response\":\"{\\\"error\\\":\\\"OpenSearchException[java.util.concurrent.TimeoutException: Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)]; nested: TimeoutException[Timeout after 5SECONDS while retrieving configuration for [ROLESMAPPING](index=.opendistro_security)];\\\"}\"}"}
{"type":"response","@timestamp":"2022-07-12T07:15:47Z","tags":[],"pid":7,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.139.244:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":10,"contentLength":9},"message":"GET /api/reporting/stats 404 10ms - 9.0B"}
```

**Comment by xikunyu** [comment]
**I solved this problem by changing config.yml with setting kibana server_username to admin.** 

```
dynamic:
            kibana:
              multitenancy_enabled: true
              server_username: admin
              index: '.kibana'
```

**But dashboards startupprobe always failed with 404.**

dashboards log
```
[root@eks-test k8s_opensearch]# kubectl logs opensearch-dashboards-67db4f7f79-25tkq -n opensearch-system  -f 
{"type":"log","@timestamp":"2022-07-12T08:42:53Z","tags":["info","plugins-service"],"pid":9,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2022-07-12T08:42:53Z","tags":["warning","config","deprecation"],"pid":9,"message":"\"opensearch.requestHeadersWhitelist\" is deprecated and has been replaced by \"opensearch.requestHeadersAllowlist\""}
{"type":"log","@timestamp":"2022-07-12T08:42:54Z","tags":["info","plugins-system"],"pid":9,"message":"Setting up [37] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,securityDashboards,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,inputControlVis,visualize,charts,visTypeTimeseries,visTypeVislib,visTypeTagcloud,visTypeMetric,discover,savedObjectsManagement,bfetch]"}
{"type":"log","@timestamp":"2022-07-12T08:42:57Z","tags":["info","savedobjects-service"],"pid":9,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
{"type":"log","@timestamp":"2022-07-12T08:42:58Z","tags":["info","savedobjects-service"],"pid":9,"message":"Starting saved objects migrations"}
{"type":"log","@timestamp":"2022-07-12T08:42:58Z","tags":["info","plugins-system"],"pid":9,"message":"Starting [37] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,securityDashboards,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,inputControlVis,visualize,charts,visTypeTimeseries,visTypeVislib,visTypeTagcloud,visTypeMetric,discover,savedObjectsManagement,bfetch]"}
{"type":"log","@timestamp":"2022-07-12T08:43:01Z","tags":["listening","info"],"pid":9,"message":"Server running at http://0.0.0.0:5601"}
{"type":"log","@timestamp":"2022-07-12T08:43:02Z","tags":["info","http","server","OpenSearchDashboards"],"pid":9,"message":"http server running at http://0.0.0.0:5601"}
{"type":"response","@timestamp":"2022-07-12T08:43:14Z","tags":[],"pid":9,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.135.86:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":5,"contentLength":9},"message":"GET /api/reporting/stats 404 5ms - 9.0B"}
{"type":"response","@timestamp":"2022-07-12T08:43:34Z","tags":[],"pid":9,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.135.86:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":3,"contentLength":9},"message":"GET /api/reporting/stats 404 3ms - 9.0B"}
{"type":"response","@timestamp":"2022-07-12T08:43:54Z","tags":[],"pid":9,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.135.86:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":2,"contentLength":9},"message":"GET /api/reporting/stats 404 2ms - 9.0B"}
{"type":"response","@timestamp":"2022-07-12T08:44:14Z","tags":[],"pid":9,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.135.86:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":6,"contentLength":9},"message":"GET /api/reporting/stats 404 6ms - 9.0B"}
{"type":"response","@timestamp":"2022-07-12T08:44:34Z","tags":[],"pid":9,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.135.86:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":3,"contentLength":9},"message":"GET /api/reporting/stats 404 3ms - 9.0B"}
{"type":"response","@timestamp":"2022-07-12T08:44:54Z","tags":[],"pid":9,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.135.86:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":3,"contentLength":9},"message":"GET /api/reporting/stats 404 3ms - 9.0B"}
{"type":"response","@timestamp":"2022-07-12T08:45:14Z","tags":[],"pid":9,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.135.86:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":3,"contentLength":9},"message":"GET /api/reporting/stats 404 3ms - 9.0B"}
{"type":"response","@timestamp":"2022-07-12T08:45:34Z","tags":[],"pid":9,"method":"get","statusCode":404,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.135.86:5601","user-agent":"kube-probe/1.21+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.132.217","userAgent":"kube-probe/1.21+"},"res":{"statusCode":404,"responseTime":4,"contentLength":9},"message":"GET /api/reporting/stats 404 4ms - 9.0B"}
```

**I try to get /api/reporting/stats using curl. And I found it always returns 404. Was this path deprecated in dashboards 2.x?**
```
[root@eks-test k8s_opensearch]# kubectl get pod -n opensearch-system -o wide
NAME                                                     READY   STATUS      RESTARTS   AGE     IP                NODE                                                 NOMINATED NODE   READINESS GATES
opensearch-dashboards-67db4f7f79-sk6g4                   0/1     Running     0          76s     192.168.142.178   ip-192-168-132-217.cn-northwest-1.compute.internal   <none>           <none>
[root@eks-test k8s_opensearch]# curl 192.168.142.178:5601
[root@eks-test k8s_opensearch]# curl 192.168.142.178:5601/api/reporting/stats
{"statusCode":404,"error":"Not Found","message":"Not Found"}
```

**Then I check the deployment manifest of dashboards, I found that httpget path is "/api/reporting/stats", should it be changed when using dashboards version 2.x ?**
```
startupProbe:
          failureThreshold: 10
          httpGet:
            path: /api/reporting/stats
            port: 5601
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 5
```

**Comment by dbason** [comment]
We're still in the process of shoring up the v2.0.0 support.  @prudhvigodithi may be able to provide some further insight into this.

**Comment by prudhvigodithi** [comment]
Hey @xikunyu I dont see any issue with latest helm chart that should support 2.x
```
helm install opensearch-operator opensearch-operator/opensearch-operator --version 2.0.0
```

**Cluster.yaml file**
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
spec:
  general:
    serviceName: opensearch
    version: 2.0.0
  security:
    config:  # Everything related to the securityconfig
      securityConfigSecret:
        name:  securityconfig-secret
      #adminSecret:
      #  name:  # Name of a secret that contains the admin client certificate
      adminCredentialsSecret:
        name: admin-credentials-secret
    tls:
      transport:
        generate: true
      http:
        generate: true
  dashboards:
    enable: true
    version: 2.0.0
    opensearchCredentialsSecret:
      name: admin-credentials-secret
    replicas: 1
    additionalConfig:
      #opensearch_security.auth.type: "proxy"
      opensearch.requestHeadersWhitelist: |
        ["securitytenant","Authorization","x-forwarded-for","x-auth-request-access-token", "x-auth-request-email", "x-auth-request-groups"]
      opensearch_security.multitenancy.enabled: "true"
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters-data-hot
      replicas: 1
      diskSize: "5Gi"
      roles:
        - "data"
        - "master"
        - "ingest"
      additionalConfig:
        node.attr.type: hot
    - component: masters-data-cold
      replicas: 1
      diskSize: "5Gi"
      roles:
        - "data"
        - "master"
        - "ingest"
      additionalConfig:
        node.attr.type: cold
```

**kubectl get pods**
```
k get pods
NAME                                                      READY   STATUS      RESTARTS   AGE
opensearch-dashboards-6c79bd597f-q8fth                    1/1     Running     0          2m27s
opensearch-masters-data-cold-0                            1/1     Running     0          2m27s
opensearch-masters-data-hot-0                             1/1     Running     0          2m27s
opensearch-operator-controller-manager-7477cf9cd5-95drm   2/2     Running     0          30m
opensearch-securityconfig-update--1-hbjwj                 0/1     Completed   0          2m27s
```

**Dashboard logs**
```
/api/reporting/stats 200 8ms - 9.0B"}
{"type":"response","@timestamp":"2022-07-13T13:27:29Z","tags":[],"pid":1,"method":"get","statusCode":200,"req":{"url":"/api/reporting/stats","method":"get","headers":{"host":"192.168.42.158:5601","user-agent":"kube-probe/1.22+","accept":"*/*","connection":"close"},"remoteAddress":"192.168.59.91","userAgent":"kube-probe/1.22+"},"res":{"statusCode":200,"responseTime":2,"contentLength":9},"message":"GET /api/reporting/stats 200 2ms - 9.0B"}
```
`k port-forward pod/opensearch-dashboards-6c79bd597f-q8fth 5601:5601`

<img width="1415" alt="Screen Shot 2022-07-13 at 9 29 43 AM" src="https://user-images.githubusercontent.com/28733332/178745383-018df169-64b9-4102-8d7e-95f2219f8ea8.png">
