### ISSUE TITLE
Rework CRD to avoid the Os abbreviation

### ISSUE THREAD

**Issue by swoehrl-mw** [Opster/opensearch-k8s-operator#24]
Currently the kind for the operator CRD is `Os`. That abbreviation is also used in other places in the CRD.

Using the `Os` abbreviation is not optimal for two reasons:

* `OS` is already widely known and used for Operating System, so using it here differently can confuse people
* A leading member of the OpenSearch community has asked in a discussion thread ([OpenSearch name: abbreviation?](https://discuss.opendistrocommunity.dev/t/opensearch-name-abbreviation/5804/3)) not to abbreviate the name to establish a clear brand

As such I suggest renaming the kind of the CRD and also any mention of `Os` in the CRD fields. 
Note: `os` can still be configured as a shortName for the CRD so a user can still do a quick `kubectl get os`

This is my suggestion of how the example definition could look like with new names:

```yaml
apiVersion: opensearch.opster.io/v1 # Renamed
kind: OpenSearchCluster # Renamed
metadata:
  name: opster-opensearch
  namespace: operator-opensearch
spec:
  general:
    clusterName: my-opensearch
    httpPort: 9200 # renamed from osPort
    transportPort: 9300 # Introduced to make both ports configurable
    vendor: opensearch
    version: latest
    serviceName: es-svc
  dashboards: # Renamed from osConfMgmt and moved to make kibana/dashboards a top-level member, later we can add other dashboards-related config options here
    enabled: true
  nodePools: # renamed from osNodes
    - component: masters
      replicas: 3
      diskSize: 30
      NodeSelector:
      cpu: 4
      memory: 16
      ingest: "false"
    - component: nodes
      replicas: 3
      diskSize: 100
      NodeSelector:
      cpu: 4
      memory: 16
      ingest: "true"
    - component: coordinators
      replicas: 3
      diskSize: 100
      NodeSelector:
      cpu: 4
      memory: 16
      ingest: "false"
```
