### ISSUE TITLE
pluginslist - schema missing

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#249]
@idanl21 @swoehrl-mw ;

as per #201 , Tried installing plugins by mentioning list under spec.general section for latest version of operator ( 2.02, 2.03), and all version says not supported in schema, is this a bug ? I also looked at the crd file that is applied by helm chart and plugins list field is missing, is this a bug in helm chart ? 

`OpenSearchCluster/opensearch-operator/devops-cluster dry-run failed, error: failed to create typed patch object: .spec.general.pluginsList: field not declared in schema...`

```
general:
    serviceName: devops-cluster
    version: 1.3.1
    pluginsList: ["repository-s3","https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/1.3.0.0/prometheus-exporter-1.3.0.0.zip"]

```
