### ISSUE TITLE
Operator > 2.0.0 fails to create Bootstrap Pod

### ISSUE THREAD

**Issue by edwardsmit** [Opster/opensearch-k8s-operator#251]
Using the following ResourceDefinition

```yaml
---
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: our-cluster
  namespace: our-namespace
spec:
  general:
    serviceName: open-search
    version: 2.2.0
    setVMMaxMapCount: true
  security:
    tls:
      transport:
        generate: true
        perNode: true
      http:
        generate: true
  dashboards:
    enable: true
    tls:
      enable: true
      generate: true
    version: 2.2.0
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: open-search-nodes
      replicas: 3
      diskSize: "5Gi"
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      tolerations:
        - key: cloud.google.com/gke-spot
          operator: Equal
          value: "true"
          effect: NoSchedule
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      persistence:
        pvc:
          storageClass: standard
          accessModes:
            - ReadWriteOnce
      roles:
        - "data"
        - "master"
```

and the 2.0.3, 2.0.2 and 2.0.1 operator, the bootstrap pod isn't created, and the Operator fails to create a working OpenSearch cluster.
Using the 2.0.0 operator, the bootstrap-pod is created successfully, however, the 2.0.0 operator does not support  OpenSearch 2.x
