### ISSUE TITLE
Rework CRD to make it more congruent with kubernetes and opensearch terminology

### ISSUE THREAD

**Issue by swoehrl-mw** [Opster/opensearch-k8s-operator#26]
After looking at the CRD and having worked with the opensearch helm chart I have some suggestions on how to rework the CRD to make it more congruent with kubernetes and opensearch terminology.

Note: This builds on the changes I proposed in #24.

To start a discussion this is my suggestion of a reworked example definition (all changes commented):

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opster-opensearch
  namespace: operator-os
spec:
  general:
    clusterName: os-from-operator  # Could be optional, if not set the operator can just use metadata.name
    httpPort: 9200
    transportPort: 9300 # Introduced to make both ports configurable
    #vendor: opensearch # Do we need that? Managing both opensearch and elasticsearch would likely become very hard due to the different implementations. I'd say remove field until we really have a use for it
    version: latest
    serviceName: es-svc  # Could be optional, if not set the operator can just use clusterName
  dashboards:
    enabled: true
  nodePools:
    - name: masters  # Renamed from component, use it as just a name, the component will be defined by the roles
      replicas: 3
      storage: # renamed and introduced substructure
        size: "30Gi" # Switch to using kubernetes resource units
        storageClassName: "default" # Optional to e.g. use local disks or fast SSDs
      nodeSelector:  # start with lowercase letter to be consistent
      resources: # Switch to resource definition structure and units as is used for pods/containers in kubernetes
        requests:
          cpu: "4"
          memory: "16Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
      roles: # Removed ingest parameter and made it more generic 
        - master
    - name: data
      replicas: 3
      storage:
        size: "100Gi"
      nodeSelector:
      resources:
        requests:
          cpu: "4"
          memory: "16Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
      roles:
        - ingest
        - data
    - name: coordinators
      replicas: 3
      storage:
        size: "100Gi"
      nodeSelector:
      resources:
        requests:
          cpu: "4"
          memory: "16Gi"
        limits:
          cpu: "4"
          memory: "16Gi"
      roles: []  # No roles means the node is a coordinator node
```

Looking forward to your ideas.
