### ISSUE TITLE
plugin installation not working

### ISSUE THREAD

**Issue by KannappanSomu** [Opster/opensearch-k8s-operator#260]
After merging #250 , and with the latest version of chart 2.0.4 , I tried fresh installation of cluster , and there were no complaints regarding missing schema, but the plugin is not installed. 

```

general:
    serviceName: devops-cluster
    version: 2.2.0
    pluginsList: ["repository-s3","https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.2.0.0/prometheus-exporter-2.2.0.0.zip"]
```
    
both repositorys3  and Prometheus plugin not installed. 

when I try to list plugins after the pod is up , the prometheus and s3 plugin is missing

![image](https://user-images.githubusercontent.com/55806176/185611743-cca41e5c-105c-48ef-b11a-59569e4a320c.png)

@idanl21 can you have a look ?

**Comment by KannappanSomu** [comment]
@idanl21  apart from adding the plugin list in spec.general section , is there something else we need to do for the plugin to be installed ? Am I missing something ?

**Comment by idanl21** [comment]
Hey, you are not missing anything. can you please send the YAML that you deployed? we will check it again internally

**Comment by KannappanSomu** [comment]
@idanl21  , below is the yaml file   &  I m using operator version 2.0.4
cluster deployment is successful , but the plugin is not installed. checked with plugin list command 

![image](https://user-images.githubusercontent.com/55806176/185879445-b1b23ff0-0bb9-4db7-a93e-2cac93a9b796.png)

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: devops-cluster1
spec:
  security:
    tls:  # Everything related to TLS configuration
      transport:  # Configuration of the transport endpoint
        generate: true  # Have the operator generate and sign certificates
        perNode: true
      http:  # Configuration of the HTTP endpoint
        generate: true
    config:
      securityConfigSecret:
        name:  security-config
      adminCredentialsSecret:
        name:  adminsecret
  general:
      serviceName: devops-cluster1
      version: 2.2.0
      pluginsList: ["repository-s3","https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.2.0.0/prometheus-exporter-2.2.0.0.zip"]
  dashboards:
    enable: true
    tls:
      enable: true  # Configure TLS
      generate: true 
    version: 1.3.3
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
    additionalConfig:
      opensearch_security.auth.type: "saml"
      opensearch.requestHeadersWhitelist: |
        ["securitytenant","Authorization","x-forwarded-for","x-auth-request-access-token", "x-auth-request-email", "x-auth-request-groups"]
      opensearch_security.multitenancy.enabled: "true"
      server.xsrf.whitelist: |
        ["/_plugins/_security/api/authtoken", "/_opendistro/_security/api/authtoken", "/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout", "/_plugins/_security/saml/acs/idpinitiated", "/_plugins/_security/saml/acs", "/_plugins/_security/saml/logout"]
  nodePools:
    - component: masters
      jvm: "-Xms1g -Xmx1g"
      tolerations:
      - key: "bakery.io/app"
        operator: "Exists"
        effect: "NoSchedule" 
      # nodeSelector: {"instancegroup": "os-master"}
      replicas: 3
      diskSize: "5Gi"
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
      persistence:
        pvc:
          storageClass: gp2
          accessModes:
          - ReadWriteOnce
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: instancegroup
                operator: In
                values: ["os-master"]
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                opster.io/opensearch-nodepool: masters
            topologyKey: kubernetes.io/hostname
```

**Comment by idanl21** [comment]
Thanks @KannappanSomu, I will test it today

**Comment by KannappanSomu** [comment]
@idanl21  @prudhvigodithi , did u get a chance to test this ? 

I don't see the plugin installation working .

**Comment by prudhvigodithi** [comment]
Hey @KannappanSomu I can see the installation works
```k logs my-first-cluster-masters-0    -f
Defaulted container "opensearch" out of: opensearch, init (init)
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.NetPermission setDefaultAuthenticator
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission opensearch.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed repository-s3 with folder name repository-s3
-> Installing https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.2.0.0/prometheus-exporter-2.2.0.0.zip
-> Downloading https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.2.0.0/prometheus-exporter-2.2.0.0.zip
```


```
bin/opensearch-plugin list
opensearch-alerting
opensearch-anomaly-detection
opensearch-asynchronous-search
opensearch-cross-cluster-replication
opensearch-geospatial
opensearch-index-management
opensearch-job-scheduler
opensearch-knn
opensearch-ml
opensearch-notifications
opensearch-notifications-core
opensearch-observability
opensearch-performance-analyzer
opensearch-reports-scheduler
opensearch-security
opensearch-sql
prometheus-exporter
repository-s3
```

Can you please try with my sample cluster yaml and with latest version of the operator 
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  security:
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9400
    serviceName: my-first-cluster
    version: 2.2.0
    pluginsList: ["repository-s3","https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.2.0.0/prometheus-exporter-2.2.0.0.zip"]
    drainDataNodes: true
  dashboards:
    version: 2.2.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      resources:
         requests:
            memory: "1Gi"
            cpu: "550m"
         limits:
            memory: "1Gi"
            cpu: "550m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}
```

**Comment by KannappanSomu** [comment]
@prudhvigodithi , Okay , When I manually install the chart , the operator deployment gets the image version tag v2.1.0 , and the plugin gets installed successfully , 

`image: public.ecr.aws/opsterio/opensearch-operator:v2.0.1`

Whereas when I deploy the chart with argocd or fluxcd, it seems to apply the operator deployment image with latest tag ? and this latest tag seems to be old and does not have plugin implementation. 

`image: public.ecr.aws/opsterio/opensearch-operator:latest`

Any ideas what could be the reason ?  When I describe helm release resource , it says pulled 2.0.4 version of chart. but still applied latest image tag that is old. 

![image](https://user-images.githubusercontent.com/55806176/188507371-dce4f615-1898-4aca-8375-4a559a11d861.png)

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opensearch-operator
  namespace: opensearch-operator
spec:
  releaseName: opensearch-release
  chart:
    spec:
      chart: opensearch-operator
      sourceRef:
        kind: HelmRepository
        name: opensearch-ops
        namespace: flux-system
      version: "2.0.4"
  interval: 2m
  install:
    remediation:
      retries: 3
```
