### ISSUE TITLE
Documented Additional Volumes field not supported by CRD.

### ISSUE THREAD

**Issue by dobharweim** [Opster/opensearch-k8s-operator#279]
### Description

The [documented](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#additional-volumes) Additional Volumes field is not working. The operator is unable to validate manifests containing additionalVolumes.

### Steps to reproduce
1. Install the latest version of the operator.
2. Deploy the following YAML:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  security:
    config:
      securityConfigSecret:
        ##Pre create this secret with required security configs, to override the default settings
        name: securityconfig-secret
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9400
    serviceName: my-first-cluster
    version: 2.2.1
    pluginsList: ["repository-s3"]
    drainDataNodes: true
    additionalVolumes:
      - name: log4j2-properties
        path: /usr/share/opensearch/config/log4j2.properties
        configMap:
          name: log4j2-properties
        restartPods: true
  dashboards:
    tls:
      enable: true
      generate: true
    version: 2.2.1
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
    additionalConfig:
      opensearch_security.auth.type: 'openid'
      opensearch_security.openid.connect_url: REDACTED'
      opensearch_security.openid.client_id: 'REDACTED'
      opensearch_security.openid.client_secret: 'REDACTED'
      opensearch_security.openid.base_redirect_url: 'REDACTED'
  nodePools:
    - component: masters
      replicas: 3
      resources:
         requests:
            memory: "4Gi"
            cpu: "1000m"
         limits:
            memory: "4Gi"
            cpu: "1000m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}
--- 
apiVersion: v1
data:
  log4j2.properties: |-
    status = error

    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n

    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
    sh-4.2$ readlink -f ./config/log4j2.properties
    /usr/share/opensearch/config/log4j2.properties
kind: ConfigMap
metadata:
  name: log4j2-properties
  namespace: default
```

### Expected behaviour

I expected the operator to validate and create the resources above.

### Actual behaviour

An error from the API 

```error: error validating "OpenSearchCluster.yaml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards): unknown field "additionalVolumes" in io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards; if you choose to ignore these errors, turn validation off with --validate=false```

**Comment by KannappanSomu** [comment]
This looks like problem with helm chart crd template file . The template file is missing Additional Volumes field under general section . 

```
general:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "make" to regenerate code after modifying this file'
                properties:
                  additionalConfig:
                    additionalProperties:
                      type: string
                    description: Extra items to add to the opensearch.yml
                    type: object
                  defaultRepo:
                    type: string
                  drainDataNodes:
                    description: Drain data nodes controls whether to drain data notes
                      on rolling restart operations
                    type: boolean
                  httpPort:
                    default: 9200
                    format: int32
                    type: integer
                  image:
                    type: string
                  imagePullPolicy:
                    description: PullPolicy describes a policy for if/when to pull
                      a container image
                    type: string
                  imagePullSecrets:
                    items:
                      description: LocalObjectReference contains enough information
                        to let you locate the referenced object inside the same namespace.
                      properties:
                        name:
                          description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                            TODO: Add other useful fields. apiVersion, kind, uid?'
                          type: string
                      type: object
                    type: array
                  pluginsList:
                    items:
                      type: string
                    type: array                  
                  serviceAccount:
                    type: string
                  serviceName:
                    type: string
                  setVMMaxMapCount:
                    type: boolean
                  vendor:
                    enum:
                    - Opensearch
                    - Op
                    - OP
                    - os
                    - opensearch
                    type: string
                  version:
                    type: string
                required:
                - serviceName
                type: object
```
