### ISSUE TITLE
Init:CrashLoopBackOff

### ISSUE THREAD

**Issue by jtqfaire** [Opster/opensearch-k8s-operator#283]
Hi :)

I'am trying to deploy for the first time a opensearch cluster with the operator.

After the deployment of the operator with theses following commands:

`helm repo add opensearch-operator https://opster.github.io/opensearch-k8s-operator/`
`helm install opensearch-operator opensearch-operator/opensearch-operator`

All seem be OK:

```bash
k get pods

NAME                                                      READY   STATUS                  RESTARTS        AGE
opensearch-operator-controller-manager-749cbc65fd-cfhvh   2/2     Running                 0               45m
```

Next, i'am trying to deploy the cluster with this configuration:

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
    version: 1.3.1
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 1
      diskSize: "5Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
```

But the init jobs of boostrap and master pods crashed:

```bash
k get pods

NAME                                                      READY   STATUS                  RESTARTS          AGE
my-first-cluster-bootstrap-0                              0/1     Init:CrashLoopBackOff   5 (102s ago)      4m56s
my-first-cluster-dashboards-866c5fd7c5-m47mz              0/1     Running                 1 (26s ago)       4m56s
my-first-cluster-masters-0                                0/1     Init:CrashLoopBackOff   5 (114s ago)      4m56s
opensearch-operator-controller-manager-749cbc65fd-cfhvh   2/2     Running                 0                 47m
```

I don't find the root cause of theses crashes.

Some logs to help:

```yaml
k describe pods my-first-cluster-masters-0 

Name:         my-first-cluster-masters-0
Namespace:    default
Priority:     0
Node:         scw-k8s-vld-default-a868e277d4704b4489db69f621/10.74.60.61
Start Time:   Wed, 07 Sep 2022 15:08:41 +0200
Labels:       controller-revision-hash=my-first-cluster-masters-7d64b9f464
              opensearch.role=master
              opster.io/opensearch-cluster=my-first-cluster
              opster.io/opensearch-nodepool=masters
              statefulset.kubernetes.io/pod-name=my-first-cluster-masters-0
Annotations:  opster.io/config: 
Status:       Pending
IP:           100.64.3.176
IPs:
  IP:           100.64.3.176
Controlled By:  StatefulSet/my-first-cluster-masters
Init Containers:
  init:
    Container ID:  containerd://a5bdd04e86fad93a5d925f6c418969f39a944be7247a4929ee8b16eb8e43e4b8
    Image:         public.ecr.aws/opsterio/busybox:1.27.2-buildx
    Image ID:      public.ecr.aws/opsterio/busybox@sha256:054c85801c4cb41511b176eb0bf13a2c4bbd41611ddd70594ec3315e88813524
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      chown -R 1000:1000 /usr/share/opensearch/data
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 07 Sep 2022 15:14:26 +0200
      Finished:     Wed, 07 Sep 2022 15:14:26 +0200
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /usr/share/opensearch/data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ftkqk (ro)
Containers:
  opensearch:
    Container ID:  
    Image:         docker.io/opensearchproject/opensearch:1.3.1
    Image ID:      
    Ports:         9200/TCP, 9300/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      /bin/bash
      -c
      ./opensearch-docker-entrypoint.sh
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     500m
      memory:  2Gi
    Requests:
      cpu:      500m
      memory:   2Gi
    Liveness:   tcp-socket :9200 delay=10s timeout=5s period=20s #success=1 #failure=10
    Readiness:  exec [/bin/bash -c curl -k -u "${OPENSEARCH_USER}:${OPENSEARCH_PASSWORD}" --silent --fail https://localhost:9200] delay=30s timeout=1s period=30s #success=1 #failure=3
    Startup:    tcp-socket :9200 delay=10s timeout=5s period=20s #success=1 #failure=10
    Environment:
      cluster.initial_master_nodes:  my-first-cluster-bootstrap-0
      discovery.seed_hosts:          my-first-cluster-discovery
      cluster.name:                  my-first-cluster
      network.bind_host:             0.0.0.0
      network.publish_host:          my-first-cluster-masters-0 (v1:metadata.name)
      OPENSEARCH_JAVA_OPTS:          -Xmx512M -Xms512M -Dopensearch.transport.cname_in_publish_address=true
      node.roles:                    data,master
      http.port:                     9200
      OPENSEARCH_USER:               admin
      OPENSEARCH_PASSWORD:           <set to the key 'password' in secret 'my-first-cluster-admin-password'>  Optional: false
    Mounts:
      /usr/share/opensearch/data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ftkqk (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-my-first-cluster-masters-0
    ReadOnly:   false
  kube-api-access-ftkqk:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                    From                     Message
  ----     ------                  ----                   ----                     -------
  Warning  FailedScheduling        7m13s                  default-scheduler        0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled               7m12s                  default-scheduler        Successfully assigned default/my-first-cluster-masters-0 to scw-k8s-vld-default-a868e277d4704b4489db69f621
  Normal   SuccessfulAttachVolume  7m10s                  attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-9aaaa747-fda8-4913-bcd7-ca93adae0462"
  Normal   Pulled                  5m32s (x5 over 7m4s)   kubelet                  Container image "public.ecr.aws/opsterio/busybox:1.27.2-buildx" already present on machine
  Normal   Created                 5m32s (x5 over 7m4s)   kubelet                  Created container init
  Normal   Started                 5m32s (x5 over 7m4s)   kubelet                  Started container init
  Warning  BackOff                 111s (x24 over 6m59s)  kubelet                  Back-off restarting failed container
```

```yaml
k describe pods my-first-cluster-bootstrap-0 

Name:         my-first-cluster-bootstrap-0
Namespace:    default
Priority:     0
Node:         scw-k8s-vld-default-a868e277d4704b4489db69f621/10.74.60.61
Start Time:   Wed, 07 Sep 2022 15:08:40 +0200
Labels:       opster.io/opensearch-cluster=my-first-cluster
Annotations:  banzaicloud.com/last-applied:
                UEsDBBQACAAIAAAAAAAAAAAAAAAAAAAAAAAIAAAAb3JpZ2luYWzMVFtv4joQ/itonpMQ0sLpyRtqe3S0UhcE3apSVSHHGRovjh35wkUo/31lJxsC23Zf9mGFRHyZyzfffJ4jlGhITg...
Status:       Pending
IP:           100.64.3.219
IPs:
  IP:           100.64.3.219
Controlled By:  OpenSearchCluster/my-first-cluster
Init Containers:
  init:
    Container ID:  containerd://34acdd9cf816d13081b1832c7973ab3433c59cf346c18c68066aad478ad86933
    Image:         public.ecr.aws/opsterio/busybox:1.27.2-buildx
    Image ID:      public.ecr.aws/opsterio/busybox@sha256:054c85801c4cb41511b176eb0bf13a2c4bbd41611ddd70594ec3315e88813524
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
    Args:
      chown -R 1000:1000 /usr/share/opensearch/data
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 07 Sep 2022 15:14:45 +0200
      Finished:     Wed, 07 Sep 2022 15:14:45 +0200
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /usr/share/opensearch/data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xznlz (ro)
Containers:
  opensearch:
    Container ID:   
    Image:          docker.io/opensearchproject/opensearch:1.3.1
    Image ID:       
    Ports:          9200/TCP, 9300/TCP
    Host Ports:     0/TCP, 0/TCP
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Liveness:       tcp-socket :9200 delay=10s timeout=5s period=20s #success=1 #failure=10
    Startup:        tcp-socket :9200 delay=10s timeout=5s period=20s #success=1 #failure=10
    Environment:
      cluster.initial_master_nodes:  my-first-cluster-bootstrap-0
      discovery.seed_hosts:          my-first-cluster-discovery
      cluster.name:                  my-first-cluster
      network.bind_host:             0.0.0.0
      network.publish_host:          my-first-cluster-bootstrap-0 (v1:metadata.name)
      OPENSEARCH_JAVA_OPTS:          -Xmx512M -Xms512M
      node.roles:                    master
      http.port:                     9200
    Mounts:
      /usr/share/opensearch/data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-xznlz (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-xznlz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m37s                   default-scheduler  Successfully assigned default/my-first-cluster-bootstrap-0 to scw-k8s-vld-default-a868e277d4704b4489db69f621
  Normal   Pulled     7m59s (x5 over 9m37s)   kubelet            Container image "public.ecr.aws/opsterio/busybox:1.27.2-buildx" already present on machine
  Normal   Created    7m59s (x5 over 9m37s)   kubelet            Created container init
  Normal   Started    7m59s (x5 over 9m37s)   kubelet            Started container init
  Warning  BackOff    4m24s (x25 over 9m34s)  kubelet            Back-off restarting failed container
```

```
k logs -f opensearch-operator-controller-manager-749cbc65fd-cfhvh operator-controller-manager

1.6625567818791103e+09	INFO	controller.opensearchcluster	Reconciling OpenSearchCluster	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "cluster": "default/my-first-cluster"}
1.6625567819347954e+09	INFO	controller.opensearchcluster	No security specified. Not doing anything	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.662556781939044e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6625567819414628e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-discovery", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.662556781942984e+09	DEBUG	controller.opensearchcluster	resource diff	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.6625567819435472e+09	DEBUG	controller.opensearchcluster	updating resource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.662556781957856e+09	DEBUG	controller.opensearchcluster	resource updated	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.662556781981492e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-bootstrap-0", "namespace": "default", "apiVersion": "v1", "kind": "Pod"}
1.6625567819833755e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-masters", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6625567819835763e+09	INFO	controller.opensearchcluster	The existing statefulset VolumeClaimTemplate disk size is: 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.6625567819835978e+09	INFO	controller.opensearchcluster	The cluster definition nodePool disk size is: 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.6625567819836035e+09	INFO	controller.opensearchcluster	The existing disk size 5Gi is same as passed in disk size 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.6625567819972875e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-masters", "namespace": "default", "apiVersion": "apps/v1", "kind": "StatefulSet"}
1.662556781999446e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards-config", "namespace": "default", "apiVersion": "v1", "kind": "ConfigMap"}
1.6625567820142534e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards", "namespace": "default", "apiVersion": "apps/v1", "kind": "Deployment"}
1.662556782015751e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6625567830798342e+09	INFO	controller.opensearchcluster	Reconciling OpenSearchCluster	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "cluster": "default/my-first-cluster"}
1.6625567831480978e+09	INFO	controller.opensearchcluster	No security specified. Not doing anything	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.6625567831518643e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.662556783155525e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-discovery", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6625567831571124e+09	DEBUG	controller.opensearchcluster	resource diff	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.6625567831589577e+09	DEBUG	controller.opensearchcluster	updating resource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.6625567831765285e+09	DEBUG	controller.opensearchcluster	resource updated	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.662556783183837e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-bootstrap-0", "namespace": "default", "apiVersion": "v1", "kind": "Pod"}
1.6625567831859338e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-masters", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6625567831861484e+09	INFO	controller.opensearchcluster	The existing statefulset VolumeClaimTemplate disk size is: 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.662556783186171e+09	INFO	controller.opensearchcluster	The cluster definition nodePool disk size is: 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.6625567831861775e+09	INFO	controller.opensearchcluster	The existing disk size 5Gi is same as passed in disk size 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.662556783193517e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-masters", "namespace": "default", "apiVersion": "apps/v1", "kind": "StatefulSet"}
1.6625567831944184e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards-config", "namespace": "default", "apiVersion": "v1", "kind": "ConfigMap"}
1.66255678320033e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards", "namespace": "default", "apiVersion": "apps/v1", "kind": "Deployment"}
1.6625567832024148e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6625567887393668e+09	INFO	controller.opensearchcluster	Reconciling OpenSearchCluster	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "cluster": "default/my-first-cluster"}
1.6625567888094509e+09	INFO	controller.opensearchcluster	No security specified. Not doing anything	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.6625567888130748e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6625567888149517e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-discovery", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.662556788815826e+09	DEBUG	controller.opensearchcluster	resource diff	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.6625567888160555e+09	DEBUG	controller.opensearchcluster	updating resource	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.6625567888297055e+09	DEBUG	controller.opensearchcluster	resource updated	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-admin-password", "namespace": "default", "apiVersion": "v1", "kind": "Secret"}
1.6625567888522904e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-bootstrap-0", "namespace": "default", "apiVersion": "v1", "kind": "Pod"}
1.6625567888562274e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-masters", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
1.6625567888624427e+09	INFO	controller.opensearchcluster	The existing statefulset VolumeClaimTemplate disk size is: 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.6625567888624828e+09	INFO	controller.opensearchcluster	The cluster definition nodePool disk size is: 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.662556788862487e+09	INFO	controller.opensearchcluster	The existing disk size 5Gi is same as passed in disk size 5Gi	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default"}
1.662556788875472e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "cluster", "name": "my-first-cluster-masters", "namespace": "default", "apiVersion": "apps/v1", "kind": "StatefulSet"}
1.662556788878669e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards-config", "namespace": "default", "apiVersion": "v1", "kind": "ConfigMap"}
1.6625567888874946e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards", "namespace": "default", "apiVersion": "apps/v1", "kind": "Deployment"}
1.6625567888890553e+09	DEBUG	controller.opensearchcluster	resource is in sync	{"reconciler group": "opensearch.opster.io", "reconciler kind": "OpenSearchCluster", "name": "my-first-cluster", "namespace": "default", "reconciler": "dashboards", "name": "my-first-cluster-dashboards", "namespace": "default", "apiVersion": "v1", "kind": "Service"}
```

My kubernetes cluster version:

`Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}`

Thanks for your help
