### ISSUE TITLE
Enable pod antiaffinity by default

### ISSUE THREAD

**Issue by anubisg1** [Opster/opensearch-k8s-operator#285]
When installing a cluster via the operator, pod antiaffinity should be enabled by default (and user should be allowed to override it) so that each opensearch cluster node runs on a separate k8s node in order to provide an appropriate level of HA and fault tolerance

something similar to the following should exist by default (without any user configuration)

```
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    opster.io/opensearch-cluster: secure-cluster
                topologyKey: kubernetes.io/hostname
```
