### ISSUE TITLE
Failed installing any official plugin always failes with error Unknonw [plugin]

### ISSUE THREAD

**Issue by ahmedrshdy** [Opster/opensearch-k8s-operator#286]
Hi,
I am using the following yaml to deploy a cluster:
```

apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: doha-opsearch
  namespace: open-search

spec:
  general:
    serviceName: doha-dic-poc
    setVMMaxMapCount: true
    version: 2.2.1
    pluginsList: ["opensearch-alerting"]
  dashboards:
    enable: true
    version: 2.2.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "5Gi"
      jvm: -Xmx8g -Xms8g
      NodeSelector:
      resources:
         requests:
            memory: "4Gi"
            cpu: "2"
        #  limits:
        #     memory: "2Gi"
        #     cpu: "500m"
      roles:
        - "data"
        - "cluster_manager"
  ```

Cluster failed to operate with CrashLoopbackOff, in logs I see the error:
`ERROR: Unknown plugin opensearch-alerting`

Changing the pluginList with any official plugin raises same error.

When tried to use the git repo zip url, Java raises error: `Exception in thread "main" java.nio.file.NoSuchFileException: /usr/share/opensearch/plugins/`

Chart version: 2.0.1

``
