### ISSUE TITLE
Failure to boostrap shutdown or evicted nodes

### ISSUE THREAD

**Issue by ahmedrshdy** [Opster/opensearch-k8s-operator#287]
How to reproduce:

Use the following yaml to deploy a new cluster

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: doha-opsearch
  namespace: open-search

spec:
  general:
    serviceName: doha-dic-poc
    setVMMaxMapCount: true
    version: 2.2.1
    # pluginsList: ["opensearch-knn", "opensearch-ml", "opensearch-notifications", "opensearch-alerting"]
    # pluginsList: ["opensearch-alerting"]
  dashboards:
    enable: true
    version: 2.2.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "6Gi"
      jvm: -Xmx8g -Xms8g
      NodeSelector:
      resources:
         requests:
            memory: "8Gi"
            cpu: "2"
        #  limits:
        #     memory: "2Gi"
        #     cpu: "500m"
      roles:
        - "data"
        - "cluster_manager"
 ```

After successful deployment, manually terminate any of the master nodes. 

The terminated node is re-provisioned as expected but stuck in unready state. 

Digging into logs of this unready node reveals the following error:

`luster-manager not discovered or elected yet, an election requires a node with id [jP-5_H9nSEyqCcrTEuX3sg]z
