### ISSUE TITLE
Setting cluster routing to primaries before deleting pod causes forbidden replica allocation error

### ISSUE THREAD

**Issue by aarontams** [Opster/opensearch-k8s-operator#293]
After we added the `jvm` setting for all OS nodes to the opensearachcluster CR, only the coordinator pods bounced as expected. The master pods won't bounce because of the following allocations error and the OS cluster stays yellow after all the coordinator pods bounced hours ago.
```
"explanation" : "replica allocations are forbidden due to cluster setting [cluster.routing.allocation.enable=primaries]"
```

Is that an expected behavior? Is there any reason why we need to move the cluster routing to `primary` instead of keeping the default (all) setting before deleting the pods?

Should we also add a new field in opensearchcluster CR to let the user customize that behavior.
May be consider the new field calls `ClusterShardAllocationBeforePodDelete` or `ClusterRoutingBeforePodDelete`.

**Comment by idanl21** [comment]
@prudhvigodithi, facing that issue again, we need to remove the `cluster.routing.allocation.enable=primaries` at the end of the process .

**Comment by Prashantpv** [comment]
@prudhvigodithi Facing this issue, can you please look into this

**Comment by prudhvigodithi** [comment]
Hey sure let me take a look at this today and I will post some updates, thanks

**Comment by prudhvigodithi** [comment]
Hey @aarontams to help further can you please share your yaml file used?

**Comment by aarontams** [comment]
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  finalizers:
  - Opster
  generation: 7
  name: opensearch-cluster
  namespace: logging
spec:
  confMgmt:
    smartScaler: true
  dashboards:
    enable: true
    image: .../opensearch-dashboards:1.2.3
    opensearchCredentialsSecret: {}
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    version: 1.2.0
  general:
    httpPort: 9200
    image: .../opensearch:1.2.3
    serviceName: opensearch-cluster
    vendor: opensearch
    version: 1.2.3
  nodePools:
  - component: masters
    diskSize: 2000Gi
    jvm: -Xms6g -Xmx6g
    persistence:
      pvc:
        accessModes:
        - ReadWriteOnce
        storageClass: oci-bv
    replicas: 5
    resources:
      limits:
        cpu: 3000m
        memory: 8Gi
      requests:
        cpu: 1000m
        memory: 8Gi
    roles:
    - master
    - data
  - component: nodes
    diskSize: 2000Gi
    jvm: -Xms4g -Xmx4g
    persistence:
      pvc:
        accessModes:
        - ReadWriteOnce
        storageClass: oci-bv
    replicas: 3
    resources:
      limits:
        cpu: 3000m
        memory: 6Gi
      requests:
        cpu: 1000m
        memory: 6Gi
    roles:
    - data
  - component: coordinators
    diskSize: 50Gi
    jvm: -Xms2g -Xmx2g
    persistence:
      pvc:
        accessModes:
        - ReadWriteOnce
        storageClass: oci-bv
    replicas: 2
    resources:
      limits:
        cpu: 500m
        memory: 3Gi
      requests:
        cpu: 500m
        memory: 3Gi
    roles:
    - ingest
```
