### ISSUE TITLE
OpenSearch Dashboard failing with TLS setting

### ISSUE THREAD

**Issue by ElAndree** [Opster/opensearch-k8s-operator#299]
Hey there,

as soon as i enable the tls generate option, my dashboard is not connecting anymore and throwing a tons of errors (see attached log).
Could you maybe have a look into it and tell me what i am doing wrong? That would be awesome!

Kind regards
Andre

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch
  namespace: opensearch
spec:
  general:
    serviceName: opensearch
    version: 1.3.1
  security:
    tls: # Everything related to TLS configuration
      transport: # Configuration of the transport endpoint
        generate: true # Have the operator generate and sign certificates
    config: # Everything related to the securityconfig
      securityConfigSecret:
        name: opensearch-config
      adminCredentialsSecret:
        name: opensearch-admin-account
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    additionalConfig:
      server.ssl.enabled: "false"
      opensearch_security.multitenancy.enabled: "true"
      opensearch.ssl.verificationMode: "none"
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  nodePools:
    - component: masters
      replicas: 1
      diskSize: "25Gi"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "data"
        - "master"
      persistence:
        pvc:
          storageClass: openebs-hostpath
          accessModes:
            - ReadWriteOnce

```

```
{"type":"log","@timestamp":"2022-09-22T19:51:13Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2022-09-22T19:51:14Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
{"type":"log","@timestamp":"2022-09-22T19:51:14Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
{"type":"log","@timestamp":"2022-09-22T19:51:14Z","tags":["info","plugins-system"],"pid":1,"message":"Setting up [44] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,alertingDashboards,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,dashboard,visualizations,visTypeVega,visTypeTable,visTypeTimeline,timeline,visTypeMarkdown,tileMap,regionMap,inputControlVis,visualize,ganttChartDashboards,reportsDashboards,securityDashboards,indexManagementDashboards,anomalyDetectionDashboards,queryWorkbenchDashboards,bfetch,charts,visTypeVislib,visTypeTagcloud,visTypeTimeseries,visTypeMetric,discover,savedObjectsManagement,observabilityDashboards]"}
{"type":"log","@timestamp":"2022-09-22T19:51:17Z","tags":["info","savedobjects-service"],"pid":1,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
{"type":"log","@timestamp":"2022-09-22T19:51:17Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:17Z","tags":["error","savedobjects-service"],"pid":1,"message":"Unable to retrieve version information from OpenSearch nodes."}
{"type":"log","@timestamp":"2022-09-22T19:51:20Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:22Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wr
{"type":"log","@timestamp":"2022-09-22T19:51:27Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:30Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:32Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:35Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:37Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:40Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:42Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:45Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:47Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:50Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:52Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:55Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:51:57Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
{"type":"log","@timestamp":"2022-09-22T19:52:00Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: write EPROTO 140096213624640:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n"}
```

**Comment by swoehrl-mw** [comment]
Hi @ElAndree. The operator currently doesn't support single-instance clusters. So please use `replicas: 3` for the master nodepool.
I was able to reproduce your problem. 
Can you please add `security.tls.http.generate` to your clusterspec and try again?
```yaml
  security:
    tls:
      transport:
        generate: true
      http:
        generate: true
```
If any of the `tls` settings is present in the config, opensearch does not install the demo certificates and configuration, thereby disabling TLS on the http/rest layer, which leads to the dashboards tls error. 
In the operator when configuring Dashboards we currently assume TLS is always enabled for the http layer. So we either need to configure that based on if TLS is actually enabled or always generate and configure TLS certificates for both layers as soon as the user configures TLS for either of the transport or http layer (which I prefer to always have encrypted communication).

**Comment by ElAndree** [comment]
Hey @swoehrl-mw 

thanks for your fast response!
Okay that makes sense, i activated http generation and now changed the replicas to 3.
Now i have 3 nodes setup but the dashboard is logging the following error.

```
{"type":"log","@timestamp":"2022-09-23T18:06:58Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2022-09-23T18:06:58Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
{"type":"log","@timestamp":"2022-09-23T18:06:58Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
{"type":"log","@timestamp":"2022-09-23T18:06:59Z","tags":["info","plugins-system"],"pid":1,"message":"Setting up [44] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,alertingDashboards,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,apmOss,console,management,indexPatternManagement,advancedSettings,savedObjects,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,inputControlVis,visualize,ganttChartDashboards,securityDashboards,reportsDashboards,indexManagementDashboards,anomalyDetectionDashboards,queryWorkbenchDashboards,charts,visTypeMetric,visTypeVislib,visTypeTimeseries,visTypeTagcloud,discover,savedObjectsManagement,observabilityDashboards,bfetch]"}
{"type":"log","@timestamp":"2022-09-23T18:07:01Z","tags":["info","savedobjects-service"],"pid":1,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
{"type":"log","@timestamp":"2022-09-23T18:07:01Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:01Z","tags":["error","savedobjects-service"],"pid":1,"message":"Unable to retrieve version information from OpenSearch nodes."}
{"type":"log","@timestamp":"2022-09-23T18:07:04Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:06Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:09Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:11Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:14Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:16Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:19Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:21Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:24Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:26Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
{"type":"log","@timestamp":"2022-09-23T18:07:29Z","tags":["error","opensearch","data"],"pid":1,"message":"[ResponseError]: Response Error"}
```

Am i still missing some config or what am i doing wrong?
Many many thanks already

Kind regards
Andre

**Comment by ElAndree** [comment]
Okay, i managed it to fix it by mself
```
    opensearchCredentialsSecret:
      name: opensearch-admin-account
```

i was missing this in the dashboard config

**Comment by sfisli** [comment]
@swoehrl-mw Hey,  this did not fix my issue ! : 
```
    opensearchCredentialsSecret:
      name: opensearch-admin-account
```
Here is the full config : 
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: adeiz-opensearch-cluster
  namespace: labadeiz
spec:
  security:
     tls:
       transport:
         generate: true
         perNode: true
       http:
          generate: true
     config:
       adminCredentialsSecret: # these are the admin credentials for the Operator to use
         name: admin-credentials-secret
       securityConfigSecret:  # this is the whole security configuration for OpenSearch
         name: securityconfig-secret
  general:
    setVMMaxMapCount: true
    serviceName: adeiz-opensearch-cluster
    version: 2.3.0
  dashboards:
    opensearchCredentialsSecret:
      name: admin-credentials-secret
    enable: true
    tls:
      enable: true
      generate: true
    version: 2.3.0
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: nodes
      replicas: 2
      diskSize: "3Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "1000m"
         limits:
           # memory: "2Gi"
            #cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
```
