### ISSUE TITLE
unknown field "additionalVolumes"

### ISSUE THREAD

**Issue by anubisg1** [Opster/opensearch-k8s-operator#303]
According to https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#additional-volumes i should be able to mount an additional volume to my dashboard by providing `spec.dashboards.additionalVolumes` 

unfortunately this doesn't seem to be the case

```
operator@azure:~/opensearch/opensearch-deployment$ kubectl apply -f opensearch.yaml 
error: error validating "opensearch.yaml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards): unknown field "additionalVolumes" in io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards; if you choose to ignore these errors, turn validation off with --validate=false
```

relevant piece of config is the following

```
spec:
  dashboards:
    additionalVolumes:
    - name: dashboard-images
      path: /usr/share/opensearch-dashboards/assets
      configMap:
        name: dashboard-images
      restartPods: true 
```
