### ISSUE TITLE
Operator does not upgrade cluster from 1.3.4 to 2.3.0

### ISSUE THREAD

**Issue by gigallucci** [Opster/opensearch-k8s-operator#311]
# Environment

- Opster-Operator: 2.0.4
- Kubernetes: v1.23.6
- Opensearch: 1.3.4 to 2.3.0

# What we tried to do

We have a cluster running with following configuration:

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: demo
  namespace: opensearch
spec:
  general:
    serviceName: demo
    version: 1.3.4
    setVMMaxMapCount: true
    additionalConfig:
      compatibility.override_main_response_version: "true"
  security:
    tls:  
      transport:  
        generate: true  
        perNode: true  
      http:  
        generate: true  
    config:  
      securityConfigSecret:
        name: opensearch-config 
      adminCredentialsSecret:
        name: opensearch-creds
  confMgmt:
    smartScaler: true
  dashboards:
    enable: true
    opensearchCredentialsSecret:
      name: opensearch-creds
    version: 1.3.4
    replicas: 1
    resources:
      requests:
         memory: "4Gi"
         cpu: "4"
      limits:
         memory: "4Gi"
         cpu: "4"
    additionalConfig:
      savedObjects.maxImportPayloadBytes: "104857600"
      opensearch.requestHeadersWhitelist: |
        ["securitytenant","Authorization"]
      opensearch_security.multitenancy.enabled: "true"
      opensearch_security.multitenancy.tenants.enable_global: "true"
      opensearch_security.multitenancy.tenants.enable_private: "true"
      opensearch_security.multitenancy.tenants.preferred: |
        ["Private", "Global"]
      opensearch_security.multitenancy.enable_filter: "false"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "100Gi"
      jvm: "-Xmx4096M -Xms4096M"
      NodeSelector:
      resources:
         requests:
            memory: "8Gi"
            cpu: "4"
         limits:
            memory: "8Gi"
            cpu: "4"
      roles:
        - "data"
        - "master"
   ```
For upgrading our OS-Cluster  to 2.3.0 we changed the role "master" to "cluster_manager" and changed the Version for dashboards and opensearch to 2.3.0

# Current behavior

After deployment of the new CRD nothing happens. 
The operator does not kicked in and upgraded the nodes.

When you install a brand new cluster with this configuration (Version to 2.3.0 and roles "data, cluster_manger" everithing works fine. 

Also definen both roles "master" and "cluster_manager" didn't help.

# Expected behavior

The operator should recognize the new role when upgrading the cluster.

# Possible Workaround

For an upgrade leave the master-role untouched. Then the operator will upgrade the nodes.

# Possible Solution

I am not familiar with go or programming operator but by looking into the source i found following codeline which maybe could be the problem:
https://github.com/Opster/opensearch-k8s-operator/blob/72c308eb9c3e8fb98fc2eae28f1cd8f81c8776df/opensearch-operator/pkg/reconcilers/upgrade.go#L196
