### ISSUE TITLE
Operator terminates nodes via restart after k8s node removed via spot request termination.

### ISSUE THREAD

**Issue by mleklund** [Opster/opensearch-k8s-operator#312]
I have been toying with Opensearch on spot nodes.  When a spot k8s node gets recalled, the opensearch node gets rescheduled as expected.  What is unusual is that a rolling restart gets issued by the controller and any opensearch nodes with an index lower then the rescheduled node also are restarted.  I expected the opensearch node to get rescheduled and go about it's normal business instead.

**Comment by prudhvigodithi** [comment]
Hey @mleklund can you share your cluster yaml file?

**Comment by idanl21** [comment]
Hey @mleklund, can you please share your cluster yaml file? also, are you running all of the
 nodes on the same spot?

**Comment by mleklund** [comment]
No pods were all on separate nodes and even in separate AZs.

Nothing earth shattering here:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: content
  namespace: opensearch
spec:
  general:
    version: 2.2.1
    httpPort: 9200
    vendor: opensearch
    serviceName: content
    pluginsList: ["repository-s3"," https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.2.1.0/prometheus-exporter-2.2.1.0.zip"]
    setVMMaxMapCount: true
  dashboards:
    version: 2.2.1
    enable: false
    tls:
      enable: true
      generate: true
    opensearchCredentialsSecret:
      name: content-credentials 
    replicas: 1
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: false
  security:
    config:  # Everything related to the securityconfig
      securityConfigSecret:
        name: content-securityconfig 
      adminCredentialsSecret:
        name: content-credentials 
    # TLS is required, if you do not let it generate it used pre-defined certs from docker image.
    tls:
      transport:
        generate: true  # Have the operator generate and sign certificates
        perNode: false
      http:
        generate: true
  nodePools:
    - component: manager
      replicas: 3
      diskSize: "1Gi"
      resources:
        requests:
          memory: "1Gi"
          cpu: "550m"
      roles:
        - cluster_manager
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              opster.io/opensearch-cluster: content
              opster.io/opensearch-nodepool: manager
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              opster.io/opensearch-cluster: content
              opster.io/opensearch-nodepool: manager
    - component: data
#      jvm: -Xmx8G -Xms8G
      replicas: 6
      diskSize: "5Gi"
#     diskSize: "20Gi"
      resources:
        requests:
          memory: "1Gi"
          cpu: "550m"
#            memory: "12Gi"
#            cpu: "3.5"
      roles:
        - "data"
      nodeSelector:
        nodeType: opensearch
      tolerations:
        - key: "nodeType"
          operator: "Equal"
          value: "opensearch"
          effect: "NoSchedule"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "topology.kubernetes.io/zone"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              opster.io/opensearch-cluster: content
              opster.io/opensearch-nodepool: data
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              opster.io/opensearch-cluster: content
              opster.io/opensearch-nodepool: data
```

After the new node joins the cluster and the pod is assigned to that new node, the stateful set appears to scale to zero and scale back up.
