### ISSUE TITLE
unknown field "spec.nodePools[0].NodeSelector"

### ISSUE THREAD

**Issue by anubisg1** [Opster/opensearch-k8s-operator#315]
This is strange and i cannot understand what's going on ...

```
[ADMFLORIOA@de1leelastk8p01 opensearch]$ helm list -n opensearch-operator
NAME                    NAMESPACE               REVISION        UPDATED                                         STATUS          CHART                           APP VERSION
opensearch-operator     opensearch-operator     4               2022-10-14 12:01:27.210798092 +0200 CEST        deployed        opensearch-operator-2.0.4       v2.0.1
```

i have installed this already on different clusters and didn't get this before...
when i apply the manifest i get:

```
 OpenSearchCluster in version "v1" cannot be handled as a OpenSearchCluster: strict decoding error: unknown field "spec.nodePools[0].NodeSelector", unknown field "spec.nodePools[1].NodeSelector"
```

this is the manifest

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: opensearch
spec:
  general:
    version: 2.3.0
    httpPort: 9200
    vendor: opensearch
    serviceName: opensearch-cluster
    additionalConfig:
      compatibility.override_main_response_version: "true"
    pluginsList: []
  dashboards:
    version: 2.3.0
    enable: true
    replicas: 2
    opensearchCredentialsSecret:
      name: opensearch-admin-user
    additionalConfig:
      server.maxPayloadBytes: "8388608"
      wizard.enabled: "true"
      opensearch.requestHeadersWhitelist: |
        ["securitytenant","Authorization"]
      opensearch_security.multitenancy.enabled: "true"
      opensearch_security.multitenancy.tenants.enable_global: "true"
      opensearch_security.multitenancy.tenants.enable_private: "false"
      opensearch_security.multitenancy.tenants.preferred: |
        ["Global"]
      opensearch_security.multitenancy.enable_filter: "false"
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  security:
    config:
      securityConfigSecret:
       name: securityconfig-secret
      adminCredentialsSecret:
        name: opensearch-admin-user
    tls:
      transport:
        generate: true
      http:
        generate: true
  nodePools:
    - component: masters
      jvm: -Xmx2g -Xms2g
      replicas: 3
      diskSize: "10Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "4Gi"
            cpu: "2"
      roles:
        - "cluster_manager"
    - component: nodes
      jvm: -Xmx5g -Xms5g
      replicas: 3
      diskSize: "90Gi"
      NodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "10Gi"
            cpu: "2"
      roles:
        - "data"
        - "ingest"
```
