### ISSUE TITLE
Changing passwords of OpensearchUser

### ISSUE THREAD

**Issue by CodeGlitcher** [Opster/opensearch-k8s-operator#335]
We have created a few user with the OpensearchUser for some service accounts.
We have a requirement that passwords are changed every year so we want to automate this where possible.
During testing we have found dat when changing the password inside the passwordFrom secret of a user the operator does not update the account.

Repro steps:
Crete a user and secert:
kubectl apply:
```
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: opensearch-configurator
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: opensearch
spec:
  opensearchCluster:
    name: opensearch-cluster
  passwordFrom:
    name: opensearch-configurator-credentials
    key: password
``` 

```
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-configurator-credentials
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: opensearch
data:
  password: "dGVzdCA=" # test for demo 
```

Update the password secert:
```
apiVersion: v1
kind: Secret
metadata:
  name: opensearch-configurator-credentials
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: opensearch
data:
  password: "bmV3cGFzc3dvcmQ=" # newsecert for demo 
```

We expetcted the operator to update the user to reflect the password change.
The operator does not log anything about even trying to update the user.
