### ISSUE TITLE
Setting additional config in dashboards is not working

### ISSUE THREAD

**Issue by albgus** [Opster/opensearch-k8s-operator#341]
I'm trying to set some additional config for the OpenSearch Dashboards container, specifically to enable SSO.

As I understand, this is supposed to be valid config:
```
spec:
  dashboards:   
    additionalConfig:
      opensearch_security.multitenancy.enabled: "true"
      #opensearch_security.auth.type: "saml"
      server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/logout"]
```
However, that is not allowed by the CRD, returning the following error: `error: error validating "cluster.yml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards.additionalConfig.server.xsrf.allowlist): invalid type for io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards.additionalConfig: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false`

The only possible configuration seems to be this:
```
spec:
  dashboards:
    additionalConfig:
      additionalProperties: |
        opensearch_security.multitenancy.enabled: "true"
        #opensearch_security.auth.type: "saml"
        server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/logout"]
```

But that generates the following in the container, which is obviously invalid and places the dashboard Pod in a crash loop:
```
sh-4.2$ cat config/opensearch_dashboards.yml
additionalProperties: opensearch_security.multitenancy.enabled: "true"
#opensearch_security.auth.type: "saml"
server.xsrf.allowlist: ["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/logout"]

opensearch.ssl.verificationMode: none
server.name: op-cluster-dashboards
```

**Comment by albgus** [comment]
An additional bug: Seems that the operator doesn't care about any changes to the `additionalConfig` field. Is there any way to force a refresh if this happens?

**Comment by swoehrl-mw** [comment]
Hi @albgus
Can you try to specify it as:
```
spec:
  dashboards:   
    additionalConfig:
      opensearch_security.multitenancy.enabled: "true"
      #opensearch_security.auth.type: "saml"
      server.xsrf.allowlist: '["/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/logout"]' # Surround value with single quotes
```
Basically put the entire value in quotes so yaml sees it as a string

> An additional bug: Seems that the operator doesn't care about any changes to the additionalConfig field. Is there any way to force a refresh if this happens?

There is an open PR (#316) to deal with this. In the meantime you can just delete the running dashboards pod via kubectl to trigger a restart.
