### ISSUE TITLE
[Suggestion] Add support for custom kubeRbacProxy in helm template

### ISSUE THREAD

**Issue by tomheijmans** [Opster/opensearch-k8s-operator#344]
We're currently creating an opensearch cluster using this operator which works fine. As we are deploying into an air gapped environment we do have the requirement to get all docker images from a local repository. This is possible for all images except one (using the helm chart), `kubeRbacProxy`.  

I can provide a pull request to add support for this. Suggested configuration added to helm chart:
```yaml
kubeRbacProxy:
  image: 
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    tag: "v0.8.0"
```
This will fit nicely with the already existing configuration for the manager image ([values.yaml](https://github.com/Opster/opensearch-k8s-operator/blob/main/charts/opensearch-operator/values.yaml)):
```yaml
manager:
  image:
    repository: public.ecr.aws/opsterio/opensearch-operator
    ## tag default uses appVersion from Chart.yaml, to override specify tag tag: "v1.1"
    tag: ""
```

Are you willing to accept a pull request with the suggested extension of helm chart configuration? If so, I will provide one.
