### ISSUE TITLE
Upgrade from 2.2 to 2.3 fails 

### ISSUE THREAD

**Issue by ervikrant06** [Opster/opensearch-k8s-operator#347]
Tried to upgrade the cluster from opensearch version 2.2 to 2.3: 

~~~
$ kubectl get pod
NAME                                                      READY   STATUS             RESTARTS   AGE
my-cluster-dashboards-69f459c5b5-65t4b                    0/1     Running            3          11m
my-cluster-masters-0                                      1/1     Running            0          3h28m
my-cluster-masters-1                                      1/1     Running            0          3h25m
my-cluster-masters-2                                      0/1     CrashLoopBackOff   6          10m
my-cluster-nodes-0                                        1/1     Running            0          3m6s
my-cluster-nodes-1                                        1/1     Running            0          5m56s
my-cluster-securityconfig-update-wpxmq                    0/1     Completed          0          3h28m
opensearch-operator-controller-manager-68d79686f4-hdfg2   2/2     Running            3          14d
~~~

checking the logs of master-2 showing.

~~~
-> Installing repository-s3
-> Downloading repository-s3 from opensearch
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.net.NetPermission setDefaultAuthenticator
* java.net.SocketPermission * connect,resolve
* java.util.PropertyPermission opensearch.allow_insecure_settings read,write
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed repository-s3 with folder name repository-s3
-> Installing  https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.3.0.0/prometheus-exporter-2.3.0.0.zip
-> Downloading  https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.3.0.0/prometheus-exporter-2.3.0.0.zip
-> Failed installing  https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.3.0.0/prometheus-exporter-2.3.0.0.zip
-> Rolling back repository-s3
-> Rolled back repository-s3
-> Rolling back  https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.3.0.0/prometheus-exporter-2.3.0.0.zip
-> Rolled back  https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.3.0.0/prometheus-exporter-2.3.0.0.zip
Exception in thread "main" java.lang.IllegalArgumentException: Plugin [prometheus-exporter] was built for OpenSearch version 2.3.0 but version 2.2.0 is running
        at org.opensearch.plugins.PluginsService.verifyCompatibility(PluginsService.java:394)
        at org.opensearch.plugins.InstallPluginCommand.loadPluginInfo(InstallPluginCommand.java:820)
        at org.opensearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:875)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:275)
        at org.opensearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:249)
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
        at org.opensearch.cli.Command.main(Command.java:101)
        at org.opensearch.plugins.PluginCli.main(PluginCli.java:60)
~~~

image of master-2 and (master-1 or master-0) is exactly same which means plugins updated but the image stays on 2.2 which makes the master-2 node not able to come up successfully. Manually changing the image of master-2 is making the things work for other two master nodes also. 

~~~
docker.io/opensearchproject/opensearch@sha256:597907e7d80ed6b532d2a64efd4f50daec5258511a1c71d6d911ebe3849bc059
~~~

Data nodes upgraded with docker opensearch image 2.3 which looks good. 

~~~
imageID: docker.io/opensearchproject/opensearch@sha256:ed2f42861daedd95d7c52ac67b88bec40904d31bd55ff730d5158db8d0cb3f33
~~~

Summarize:
- Requires manual intervention to change the image of first master node. 
- opensearch dashboard remain unavailable during whole upgrade as 2.3 version of dashboard couldn't work existing 2.2 nodes unless all nodes upgraded to 2.3. may be we can do the upgrade of opensearch-dashboard at last once all the nodes upgraded.

**Comment by ervikrant06** [comment]
Also looks like after the upgrade this setting is left behind. 

~~~
  "transient" : {
    "cluster" : {
      "routing" : {
        "allocation" : {
          "enable" : "primaries"
        }
      }
    }
  }
~~~

**Comment by swoehrl-mw** [comment]
Hi @ervikrant06 Can you please provide the cluster yaml that you are using?

Regarding

> opensearch dashboard remain unavailable during whole upgrade

We recently merged a PR that switches dashboards to rolling restart. That way the old dashboards pod remains up until the new one gets healthy (which it only does after the upgrade is completed).

**Comment by ervikrant06** [comment]
BTW this issue https://github.com/Opster/opensearch-k8s-operator/issues/291 looks with similar issue. my cluster yaml is from repo only with self-signed certs (Nothing customized) 3 master and 2 data nodes.

**Comment by swoehrl-mw** [comment]
Hi @ervikrant06 . I was not able to reproduce your problem. I tried with below example. There was some weird double restart in the middle but after a few minutes the pods were all on 2.3.0 and running. Can you check for any differences in your configuration and try with my example?

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    httpPort: 9200
    serviceName: my-first-cluster
    version: 2.2.0
    pluginsList: ["repository-s3"]
  security:
      tls:
        http:
          generate: true 
        transport:
          generate: true
          perNode: true
  dashboards:
    version: 2.2.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "5Gi"
      resources:
         requests:
            memory: "512Mi"
            cpu: "100m"
         limits:
            memory: "2Gi"
            cpu: "1000m"
      roles:
        - "cluster_manager"
    - component: nodes
      replicas: 2
      diskSize: "5Gi"
      resources:
         requests:
            memory: "512Mi"
            cpu: "100m"
         limits:
            memory: "2Gi"
            cpu: "1000m"
      roles:
        - "data"
```
