### ISSUE TITLE
Sensitive configuration in the OpenSearch Dashboards configuration

### ISSUE THREAD

**Issue by albgus** [Opster/opensearch-k8s-operator#350]
I'm looking into implementing OpenID Connect authentication. In this scenario the IdP client secret should be configured in Kibana: https://opensearch.org/docs/latest/security-plugin/configuration/openid-connect/#configuration-example

The only way I can see to inject values from a secret is using the `env:` section with `secretKeyRef`, but unfortunately it seems that the dashboards security plugin doesn't support reading configuration from the environment.

I tried using the keystore as well but that generated an error that `opensearch_security.openid.client_secret` is not a supported key, and it seems to only be mounted into the OpenSearch nodes anyway.

**Comment by swoehrl-mw** [comment]
Hi @albgus.
AFAIK You can use environment variables inside the dashboards.yml config. So you should be able to inject the sensitive information as environment variables from a secret via the `env` option and then reference that in the `additionalConfig`.
Something like:
```yaml
# ...
dashboards:
  env:
    - name: OPENID_CLIENT_SECRET
      valueFrom:
        secretKeyRef: ...
  additionalConfig:
    opensearch_security.openid.client_secret: "${OPENID_CLIENT_SECRET}"
```

Can you try that?

> I tried using the keystore as well [...] and it seems to only be mounted into the OpenSearch nodes anyway.

Correct, the keystore is only used in the opensearch pods, not in dashboards.
