### ISSUE TITLE
Dashboard does not start ([ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200)

### ISSUE THREAD

**Issue by archeious** [Opster/opensearch-k8s-operator#369]
I am starting a simple cluster but the dashboard pod errors out.  When I check the logs I see 

```
{"type":"log","@timestamp":"2022-11-16T18:37:29Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2022-11-16T18:37:29Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
{"type":"log","@timestamp":"2022-11-16T18:37:29Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
{"type":"log","@timestamp":"2022-11-16T18:37:29Z","tags":["info","plugins-system"],"pid":1,"message":"Setting up [44] plugins: [alertingDashboards,usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,embeddable,legacyExport,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,securityDashboards,reportsDashboards,indexManagementDashboards,anomalyDetectionDashboards,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,inputControlVis,ganttChartDashboards,visualize,queryWorkbenchDashboards,charts,visTypeTimeseries,visTypeVislib,visTypeMetric,visTypeTagcloud,observabilityDashboards,discover,savedObjectsManagement,bfetch]"}
{"type":"log","@timestamp":"2022-11-16T18:37:30Z","tags":["info","savedobjects-service"],"pid":1,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
{"type":"log","@timestamp":"2022-11-16T18:37:30Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:30Z","tags":["error","savedobjects-service"],"pid":1,"message":"Unable to retrieve version information from OpenSearch nodes."}
{"type":"log","@timestamp":"2022-11-16T18:37:33Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:35Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:38Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:40Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:43Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:45Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:48Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:50Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
{"type":"log","@timestamp":"2022-11-16T18:37:53Z","tags":["error","opensearch","data"],"pid":1,"message":"[ConnectionError]: connect ECONNREFUSED 174.52.94.221:9200"}
```

I am not sure where the 174.52.94.221 address is coming from (granted I am still new to kubernetes) but the services are as follows
```
my-first-cluster                                         ClusterIP      10.108.203.167   <none>        9200/TCP,9300/TCP,9600/TCP,9650/TCP   54m
my-first-cluster-dashboards                              ClusterIP      10.99.36.90      <none>        5601/TCP                              54m
my-first-cluster-discovery                               ClusterIP      None             <none>        9300/TCP                              54m
my-first-cluster-masters                                 ClusterIP      None             <none>        9200/TCP,9300/TCP                     54m
opensearch-operator-controller-manager-metrics-service   ClusterIP      10.105.159.171   <none>        8443/TCP                              21h
```

and the pods are 

```
my-first-cluster-dashboards-65cdb457f5-zt2v9              0/1     Running   6 (2m40s ago)   24m     10.244.4.189   k8s-worker-2   <none>           <none>
my-first-cluster-masters-0                                1/1     Running   1 (40m ago)     55m     10.244.4.182   k8s-worker-2   <none>           <none>
my-first-cluster-masters-1                                1/1     Running   0               53m     10.244.5.213   k8s-worker-3   <none>           <none>
my-first-cluster-masters-2                                1/1     Running   0               44m     10.244.5.221   k8s-worker-3   <none>           <none>
opensearch-operator-controller-manager-7887f95766-65gb5   2/2     Running   0               21h     10.244.3.212   k8s-worker-1   <none>           <none>
```

My gut feeling is the dashboard would connect to 10.108.203.167.  Do I need to specify something in the dashboards config to point to the right cluster?

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
    version: 1.3.1
  dashboards:
    enable: true
    version: 1.3.1
    replicas: 1
    resources:
      requests:
         memory: "4Gi"
         cpu: "2"
      limits:
         memory: "8Gi"
         cpu: "4"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      resources:
         requests:
            memory: "4Gi"
            cpu: "2"
         limits:
            memory: "8Gi"
            cpu: "4"
      roles:
        - "data"
        - "master"
      persistence:
        pvc:
          storageClass: rook-ceph-block
          accessModes:
          - ReadWriteOnce
```
