### ISSUE TITLE
Unable to mount additional volume under subPath

### ISSUE THREAD

**Issue by anubisg1** [Opster/opensearch-k8s-operator#377]
I'm running operator 2.1.1

mounting an additional volume fails with 

```
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:75: mounting "/var/lib/kubelet/pods/010b52da-0eeb-46d0-9b52-8b0107890342/volumes/kubernetes.io~configmap/log4j2-properties" to rootfs at "/usr/share/opensearch/config/log4j2.properties" caused: mount through procfd: not a directory: unknown
```

configmap i want to mount

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: log4j2-properties
  namespace: opensearch-dev
data:
  log4j2.properties: |-
    status = error

    appender.console.type = Console
    appender.console.name = console
    appender.console.layout.type = PatternLayout
    appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c{1.}] [%node_name]%marker %m%n

    rootLogger.level = info
    rootLogger.appenderRef.console.ref = console
    logger.token.name = com.amazon.dlic.auth.http.saml.Token
    logger.token.level = debug
```

opensearch.yaml file

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: opensearch-dev
spec:
  general:
    version: 2.4.0
    httpPort: 9200
    vendor: opensearch
    serviceName: opensearch-cluster
    additionalConfig:
      compatibility.override_main_response_version: "true"
    additionalVolumes:
      - name: log4j2-properties
        path: /usr/share/opensearch/config/log4j2.properties
        configMap:
          name: log4j2-properties
        restartPods: true
    keystore:
    - secret:
        name: email-notification
    pluginsList: []
  dashboards:
    version: 2.4.0
    enable: true
    tls:
      enable: true
      generate: true
    replicas: 1
    opensearchCredentialsSecret:
      name: opensearch-admin-user
    additionalConfig:
      opensearch_security.auth.multiple_auth_enabled: "true"
      opensearch_security.auth.type: |
        ["basicauth","saml"]
      server.xsrf.allowlist: |
        ["/_opendistro/_security/saml/acs/idpinitiated", "/_opendistro/_security/saml/acs", "/_opendistro/_security/saml/logout"]
      # Multi Tenancy
      opensearch.requestHeadersAllowlist: |
        ["securitytenant","Authorization"]
    resources:
      requests:
         memory: "1Gi"
         cpu: "100m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  security:
    config:
      securityConfigSecret:
       name: securityconfig-secret
      adminCredentialsSecret:
        name: opensearch-admin-user
    tls:
      transport:
        generate: true
      http:
        generate: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "15Gi"
      nodeSelector:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                opster.io/opensearch-cluster: opensearch-cluster
                opster.io/opensearch-nodepool: masters
            topologyKey: kubernetes.io/hostname
      resources:
         requests:
            memory: "2Gi"
            cpu: "200m"
         limits:
            memory: "8Gi"
            cpu: "2"
      roles:
        - "cluster_manager"
        - "data"
        - "ingest"
```

the issue seems to be rekated to https://github.com/Opster/opensearch-k8s-operator/issues/218 and https://github.com/Opster/opensearch-k8s-operator/issues/279
