### ISSUE TITLE
users . roles and rolemappings CRD to not support namespaces

### ISSUE THREAD

**Issue by anubisg1** [Opster/opensearch-k8s-operator#381]
According to the documentation, namespace keys are available in users, roles and role mapping CRDs, like in the example

```
apiVersion: opensearch.opster.io/v1
kind: OpensearchUser
metadata:
  name: sample-user
spec:
  opensearchCluster:
    name: my-first-cluster
    namespace: default
  passwordFrom:
    name: sample-user-password
    key: password
    namespace: default
  backendRoles:
  - kibanauser
```

unfortuantely specifying namespaces results in a validation error:

 ```
error: error validating "local_users.yaml": error validating data: [ValidationError(OpensearchUser.spec.opensearchCluster): unknown field "namespace" in io.opster.opensearch.v1.OpensearchUser.spec.opensearchCluster, ValidationError(OpensearchUser.spec.passwordFrom): unknown field "namespace" in io.opster.opensearch.v1.OpensearchUser.spec.passwordFrom]; if you choose to ignore these errors, turn validation off with --validate=false
```

the issue is simply a documentation one as namespace should be under "metadata" instead
