### ISSUE TITLE
scaling down a cluster (by merging nodepool components) doesn't delete remove nodes

### ISSUE THREAD

**Issue by anubisg1** [Opster/opensearch-k8s-operator#386]
Original configuration applied:

```
  nodePools:
    - component: masters
      replicas: 3
      jvm: -Xmx4g -Xms4g
      diskSize: "15Gi"
      nodeSelector:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                opster.io/opensearch-cluster: opensearch-cluster
                opster.io/opensearch-nodepool: masters
            topologyKey: kubernetes.io/hostname
      resources:
         requests:
            memory: "2Gi"
            cpu: "100m"
         limits:
            memory: "8Gi"
            cpu: "2"
      roles:
        - "cluster_manager"
    - component: nodes
      replicas: 3
      jvm: -Xmx3g -Xms3g
      diskSize: "5000Gi"
      nodeSelector:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                opster.io/opensearch-cluster: opensearch-cluster
                opster.io/opensearch-nodepool: nodes
            topologyKey: kubernetes.io/hostname
      resources:
         requests:
            memory: "2Gi"
            cpu: "100m"
         limits:
            memory: "6Gi"
            cpu: "2"
      roles:
        - "data"
    - component: coordinators
      replicas: 3
      jvm: -Xmx4g -Xms4g
      diskSize: "15Gi"
      nodeSelector:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                opster.io/opensearch-cluster: opensearch-cluster
                opster.io/opensearch-nodepool: coordinators
            topologyKey: kubernetes.io/hostname
      resources:
         requests:
            memory: "2Gi"
            cpu: "100m"
         limits:
            memory: "8Gi"
            cpu: "2"
      roles:
        - "ingest"
```

New configuration applied (merging ingest and data nodes)

```
  nodePools:
    - component: masters
      replicas: 3
      jvm: -Xmx3g -Xms3g
      diskSize: "15Gi"
      nodeSelector:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                opster.io/opensearch-cluster: opensearch-cluster
                opster.io/opensearch-nodepool: masters
            topologyKey: kubernetes.io/hostname
      resources:
         requests:
            memory: "2Gi"
            cpu: "100m"
         limits:
            memory: "6Gi"
            cpu: "2"
      roles:
        - "cluster_manager"
    - component: nodes
      replicas: 3
      jvm: -Xmx7g -Xms7g
      diskSize: "5000Gi"
      nodeSelector:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                opster.io/opensearch-cluster: opensearch-cluster
                opster.io/opensearch-nodepool: nodes
            topologyKey: kubernetes.io/hostname
      resources:
         requests:
            memory: "2Gi"
            cpu: "100m"
         limits:
            memory: "14Gi"
            cpu: "2"
      roles:
        - "data"
        - "ingest"
```

After changes are applied, the component `masters` and `nodes` are updates, but the component `coordinators` isn't deleted.
This is easily fixed by manually deleting the statefulset but i would expect this to be done by the operator (or at the very least, the operator should scale the statefulset to 0 )
