### ISSUE TITLE
Documented dashboards.spec.basepath property not recognised by operator

### ISSUE THREAD

**Issue by dobharweim** [Opster/opensearch-k8s-operator#388]
### Description
The [documented](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#configuring-a-basepath) Dashboard base path property is not working. The operator is unable to validate manifests containing `spec.dashboards.basePath`.

### Steps to reproduce
1. Install the latest version of the operator.
2. Deploy the following YAML:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
spec:
  security:
    tls:
       http:
         generate: true 
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9200
    serviceName: my-first-cluster
    version: 2.3.0
    pluginsList: ["repository-s3"]
    drainDataNodes: true
  dashboards:
    basePath: "logs"
    tls:
      enable: true
      generate: true
    version: 2.3.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      resources:
         requests:
            memory: "4Gi"
            cpu: "1000m"
         limits:
            memory: "4Gi"
            cpu: "1000m"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
         emptyDir: {}
```

### Expected Outcome
I expect the dashboards url (and liveness + readiness probes) to be updated to point to `/logs`

### Actual outcome
Error:

> error: error validating "/Users/davidoconnor/Git/opensearch-k8s-operator/opensearch-operator/examples/opensearch-v2-cluster.yaml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards): unknown field "basePath" in io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards; if you choose to ignore these errors, turn validation off with --validate=false
