### ISSUE TITLE
Securityconfig update job does not use configured Kubernetes Serviceaccount

### ISSUE THREAD

**Issue by swoehrl-mw** [Opster/opensearch-k8s-operator#392]
From [#197](https://github.com/Opster/opensearch-k8s-operator/issues/197#issuecomment-1348585687)

Configuring a serviceaccount in the cluster spec will see that serviceaccount configured for the nodepools and the bootstrap pod but not for the securityconfig-update job.

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: simple-test
  namespace: default
spec:
  general:
    serviceAccount: some-serviceaccount # <-configured here
# ...
```

This needs to be added to `NewSecurityconfigUpdateJob` in `pkg/builders/cluster.go`. 
And while we are at it, the serviceaccount should also be used for the dashboards pods.
