### ISSUE TITLE
Using reindex API with a repository having a remote source causes an HTTP 400, no possibility to provide the CA certificate

### ISSUE THREAD

**Issue by balpert89** [Opster/opensearch-k8s-operator#393]
Hi,

we are currently evaluating ways to move our data from elasticsearch to opensearch. To move our data asynchronously we want to use the reindex API (https://opensearch.org/docs/latest/opensearch/reindex-data/#reindex-from-a-remote-cluster), where the source repository points to the elasticsearch cluster:

```
{
   "conflicts":"proceed",
   "source":{
      "remote":{
         "host":"https://elasticsearch-es-http:9200",
         "username":"elastic",
         "password":"<redacted>"
      },
      "index":"..._log-ns-9_9"
   },
   "dest":{
      "index":"_log-ns-9_9",
      "op_type":"index"
   }
}
```

The POST to `_reindex/` causes the following (expected) error:
```
elasticsearch API error: POST https://localhost:9201/_reindex 500: {"error":{"root_cause":[{"type":"s_s_l_handshake_exception","reason":"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"}],"type":"s_s_l_handshake_exception","reason":"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target","caused_by":{"type":"validator_exception","reason":"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target","caused_by":{"type":"sun_cert_path_builder_exception","reason":"unable to find valid certification path to requested target"}}},"status":500}
```

The problem is not the error, its how to provide the CA certificate so opensearch will trust the self-signed certificate provided by elasticsearch. Any recommendations?

Operator version: 2.1.1
Opensearch version: 1.3.6

I have read https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#add-secrets-to-keystore but I believe this is not the place to look for.

Best regards

**Comment by balpert89** [comment]
Short update, I may have found a way to provide the CA.

I have configured the cluster with:
```
  general:
    additionalConfig:
      reindex.remote.whitelist: 'elasticsearch-es-http:9200'
      reindex.ssl.certificate_authorities: /var/run/secrets/elasticsearch/elasticsearch-http-ca.crt
    additionalVolumes:
      - name: elasticsearch-ca
        path: /var/run/secrets/elasticsearch
        secret:
          defaultMode: 511
          secretName: opensearch-elasticsearch-ca
```

This configuration mounts the secret correctly, however opensearch has problems with it:
```
Caused by: java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/run/secrets/elasticsearch/elasticsearch-http-ca.crt" "read")
```

I am not sure why this is the case, I can successfully `cat` the content from said secret:
```
sh-4.2$ ls -la /var/run/secrets/elasticsearch/elasticsearch-http-ca.crt 
lrwxrwxrwx. 1 root root 32 Dec 16 13:26 /var/run/secrets/elasticsearch/elasticsearch-http-ca.crt -> ..data/elasticsearch-http-ca.crt

sh-4.2$ cat /var/run/secrets/elasticsearch/elasticsearch-http-ca.crt 
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
```
