### ISSUE TITLE
Setting a default admin username and password broken in v2.2.0?

### ISSUE THREAD

**Issue by darkpixel** [Opster/opensearch-k8s-operator#409]
Deploy a brand new cluster:
```
---                                                                                                                                                                                                                                             
apiVersion: v1                                                                                                                                                                                                                                  
kind: Secret                                                                                                                                                                                                                                    
metadata:                                                                                                                                                                                                                                       
  name: test-admin-password                                                                                                                                                                                                                   
  namespace: test-elastic                                                                                                                                                                                                                     
data:                                                                                                                                                                                                                                           
  username: YWRtaW4= #admin
  password: <an encoded secret password>
 ---                                                                                                                                                                                                                                             
apiVersion: v1                                                                                                                                                                                                                                  
kind: Secret                                                                                                                                                                                                                                    
metadata:                                                                                                                                                                                                                                       
  name: securityconfig-secret                                                                                                                                                                                                                   
  namespace: test-elastic                                                                                                                                                                                                                     
type: Opaque                                                                                                                                                                                                                                    
stringData:                                                                                                                                                                                                                                     
      internal_users.yml: |-                                                                                                                                                                                                                    
        _meta:                                                                                                                                                                                                                                  
          type: "internalusers"                                                                                                                                                                                                                 
          config_version: 2                                                                                                                                                                                                                     
        admin:                                                                                                                                                                                                                                  
          hash: "$2a$<an encoded secret password>"                                                                                                                                                                  
          reserved: true                                                                                                                                                                                                                        
          backend_roles:                                                                                                                                                                                                                        
          - "admin"                                                                                                                                                                                                                             
          description: "Admin user"                                                                                                                                                                                                             
      config.yml: |-                                                                                                                                                                                                                            
        _meta:                                                                                                                                                                                                                                  
          type: "config"                                                                                                                                                                                                                        
          config_version: "2"                                                                                                                                                                                                                   
        config:                                                                                                                                                                                                                                 
          dynamic:                                                                                                                                                                                                                              
            http:                                                                                                                                                                                                                               
              anonymous_auth_enabled: false                                                                                                                                                                                                     
            authc:                                                                                                                                                                                                                              
              basic_internal_auth_domain:                                                                                                                                                                                                       
                http_enabled: true                                                                                                                                                                                                              
                transport_enabled: true                                                                                                                                                                                                         
                order: "4"                                                                                                                                                                                                                      
                http_authenticator:                                                                                                                                                                                                             
                  type: basic                                                                                                                                                                                                                   
                  challenge: true                                                                                                                                                                                                               
                authentication_backend:                                                                                                                                                                                                         
                  type: intern   

---                                                                                                                                                                                                                                             
apiVersion: opensearch.opster.io/v1                                                                                                                                                                                                             
kind: OpenSearchCluster                                                                                                                                                                                                                         
metadata:                                                                                                                                                                                                                                       
  name: test                                                                                                                                                                                                                                  
  namespace: test-elastic                                                                                                                                                                                                                     
spec:                                                                                                                                                                                                                                           
  general:                                                                                                                                                                                                                                      
    serviceName: test-elastic                                                                                                                                                                                                                 
    version: 2.3.0                                                                                                                                                                                                                              
    setVMMaxMapCount: true                                                                                                                                                                                                                      
  security:                                                                                                                                                                                                                                     
    config:                                                                                                                                                                                                                                     
      securityConfigSecret:                                                                                                                                                                                                                     
        name: securityconfig-secret                                                                                                                                                                                                             
      adminCredentialsSecret:                                                                                                                                                                                                                   
        name: test-admin-password                                                                                                                                                                                                             
  dashboards:                                                                                                                                                                                                                                   
    enable: true                                                                                                                                                                                                                                
    version: 2.3.0                                                                                                                                                                                                                              
    replicas: 1                                                                                                                                                                                                                                 
    opensearchCredentialsSecret:                                                                                                                                                                                                                
      name: test-admin-password                                                                                                                                                                                                               
    resources:                                                                                                                                                                                                                                  
      requests:                                                                                                                                                                                                                                 
         memory: "512Mi"                                                                                                                                                                                                                        
         cpu: "200m"                                                                                                                                                                                                                            
      limits:                                                                                                                                                                                                                                   
         memory: "512Mi"                                                                                                                                                                                                                        
         cpu: "200m"                                                                                                                                                                                                                            
  nodePools:                                                                                                                                                                                                                                    
    - component: nodes                                                                                                                                                                                                                          
      replicas: 3                                                                                                                                                                                                                               
      diskSize: "5Gi"                                                                                                                                                                                                                           
      NodeSelector:                                                                                                                                                                                                                             
      resources:                                                                                                                                                                                                                                
         requests:                                                                                                                                                                                                                              
            memory: "2Gi"                                                                                                                                                                                                                       
            cpu: "500m"                                                                                                                                                                                                                         
         limits:                                                                                                                                                                                                                                
            memory: "2Gi"                                                                                                                                                                                                                       
            cpu: "500m"                                                                                                                                                                                                                         
      roles:                                                                                                                                                                                                                                    
        - "cluster_manager"                                                                                                                                                                                                                     
        - "data"    
```

The default username is 'admin' and the password is 'admin'.  The password can't be changed from the dashboard because the 'admin' user is 'read only'.

**Comment by darkpixel** [comment]
Also, the link to ```internal_users.yml``` in the docs is dead here: https://github.com/Opster/opensearch-k8s-operator/blame/main/docs/userguide/main.md#L711

**Comment by darkpixel** [comment]
Also the demo securityconfig link: https://github.com/Opster/opensearch-k8s-operator/blame/main/docs/userguide/main.md#L721

**Comment by swoehrl-mw** [comment]
Hi @darkpixel. Could you please describe what result you expected and what actually happened in detail? So that others can try to reproduce your problem.

**Comment by darkpixel** [comment]
Apologies.  I decided to test the OpenSearch operator a few days ago.  I followed the docs describing how to change the default username and password when spinning up a new cluster.

No matter what, my cluster comes up with the username 'admin', and the password 'admin'.

**Comment by swoehrl-mw** [comment]
Hi @darkpixel. Can you please also set the tls generate settings as described in the docs (https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#custom-admin-user) and try again? This is currently a limitation that either generated or provided certs must be used for setting securityconfig.

**Comment by idanl21** [comment]
Hey @darkpixel 
In order to create your cluster with custom admin user you should do these 3 steps:

1. Create a pre secret with your username and password, and provide it under  `adminCredentialsSecret` like you did.
2. take the default Security config secret from our examples dir, and edit the lines under `admin.hash`, you should encrypt your new password (you can use that https://bcrypt-generator.com/). and supply it under securityConfigSecret.
3. add under security :
    tls:
      transport:
        generate: true
      http:
        generate: true


after creating these 2 secrets, you can can create your cluster, it should work.

**Comment by idanl21** [comment]
You should also specify the `adminCredentialsSecret` name under `dashboards.opensearchCredentialsSecret` so dashboard will also be able to connect to the cluster with the new creds :)

**Comment by RyanIveyQ6** [comment]
I've complete all 3 steps @idanl21 and can verify the password in step 1 is set via `curl localhost:9200`, however the readiness probe fails, except for dashboards, it's successful and the pod is running.
The readiness probe failure doesn't provide much information: 
`Warning   Unhealthy                pod/my-first-cluster-masters-0                      Readiness probe failed:`
I can find from describing the pod:
`OPENSEARCH_PASSWORD:     <set to the key 'password' in secret 'my-first-cluster-admin-password'>  Optional: false`
However I've set my updated password in a different secret and updated `adminCredentialsSecret` to it.

**Comment by idanl21** [comment]
Closing the issue :)
let me know if you need any thing else

**Comment by darkpixel** [comment]
Apologies.  I've been pretty busy.
I did attempt to get it going one more time and failed.
At the moment, the elastic-operator was a lot easier to use, so I went that route for a temporary (3-4 month project).

**Comment by gautamgadipudi-hpe** [comment]
> Hey @darkpixel In order to create your cluster with custom admin user you should do these 3 steps:
> 
> 1. Create a pre secret with your username and password, and provide it under  `adminCredentialsSecret` like you did.
> 2. take the default Security config secret from our examples dir, and edit the lines under `admin.hash`, you should encrypt your new password (you can use that https://bcrypt-generator.com/). and supply it under securityConfigSecret.
> 3. add under security :
>    tls:
>    transport:
>    generate: true
>    http:
>    generate: true
> 
> after creating these 2 secrets, you can can create your cluster, it should work.

@idanl21 Thanks, this seems quite straight-forward, but I couldn't get it to work. The steps I followed:

1. Come up with a username/password and encode them (base64)
2. Put these base64 encoded username/password in `adminCredentialsSecret` secret - named `admin-password`
3. Take the plain password (not encoded), and encrypt it using https://bcrypt-generator.com/ with 12 rounds.
4. Use the [securityconfig-secret.yaml](https://github.com/Opster/opensearch-k8s-operator/blob/main/opensearch-operator/examples/securityconfig-secret.yaml), and edit `admin.hash` under `internal_users.yml`.
5. Add this spec to my CRD:
```
security:
    config:
      securityConfigSecret:
        name: securityconfig-secret
      adminCredentialsSecret:
        name: admin-password
    tls:
      transport:
        generate: true
      http:
        generate: true
```
6. Deploy the helm chart on my k8s cluster

**Error logs from security update pod:**
```
Security Admin v7
Will connect to my-cluster-t.default.svc.cluster.local:9200 ... done
Connected as "CN=admin,OU=osc"
OpenSearch Version: 2.3.0
Contacting opensearch cluster 'opensearch' and wait for YELLOW clusterstate ...
Cannot retrieve cluster state due to: 30,000 milliseconds timeout on connection http-outgoing-2 [ACTIVE]. This is not an error, will keep on trying ...
  Root cause: java.net.SocketTimeoutException: 30,000 milliseconds timeout on connection http-outgoing-2 [ACTIVE] (java.net.SocketTimeoutException/java.net.SocketTimeoutException)
   * Try running securityadmin.sh with -icl (but no -cl) and -nhnv (If that works you need to check your clustername as well as hostnames in your TLS certificates)
   * Make sure that your keystore or PEM certificate is a client certificate (not a node certificate) and configured properly in opensearch.yml
   * If this is not working, try running securityadmin.sh with --diagnose and see diagnose trace log file)
   * Add --accept-red-cluster to allow securityadmin to operate on a red cluster.
```

**Error logs from bootstrap node:**
```
[2023-10-26T17:04:20,298][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [osc-bootstrap-0] Failure No shard available for [org.opensearch.action.get.MultiGetShardRequest@6d97c307] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, ALLOWLIST, AUDIT] (index=.opendistro_security)
[2023-10-26T17:04:22,528][ERROR][o.o.s.a.BackendRegistry  ] [osc-bootstrap-0] Not yet initialized (you may need to run securityadmin)
```

**Error logs from data node:**
```
[2023-10-26T16:56:37,701][WARN ][o.o.s.a.BackendRegistry  ] [osc-masters-0] Authentication finally failed for admin from 127.0.0.1:49344
```

Would you happen to know what I might be missing?
