### ISSUE TITLE
ValidationError while adding custom branding in opensearch_dashboards.yml

### ISSUE THREAD

**Issue by mohammadzahid525** [Opster/opensearch-k8s-operator#416]
When I add custom branding in additionalConfig section it throws error.

`dashboards:
    version: 2.5.0
    enable: true
    
    additionalConfig:
      server.basePath: "/opensearch"
      server.rewriteBasePath: "false"
      opensearch_security.multitenancy.enabled: "true"
      opensearchDashboards.branding:
        logo:
          defaultUrl: "https://example.com/sample.svg"
          darkModeUrl: "https://example.com/dark-mode-sample.svg"
        mark:
          defaultUrl: "https://example.com/sample1.svg"
          darkModeUrl: "https://example.com/dark-mode-sample1.svg"
        loadingLogo:
          defaultUrl: "https://example.com/sample2.svg"
          darkModeUrl: "https://example.com/dark-mode-sample2.svg"
        faviconUrl: "https://example.com/sample3.svg"
        applicationTitle: "My Custom Title"`

Error Received:

**error: error validating "opensearch-cluster.yaml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards.additionalConfig.opensearchDashboards.branding): invalid type for io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards.additionalConfig: got "map", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false**

**Comment by therus000** [comment]
did u fix it ?

**Comment by ne0zum1** [comment]
For me if i put all of the config it doesn't work, i got `strict decoding error: unknown field`

```
additionalConfig:
  opensearchDashboards.branding:
    logo:
      defaultUrl: "https://example.com/sample.svg"
      darkModeUrl: "https://example.com/dark-mode-sample.svg"
    mark:
      defaultUrl: "https://example.com/sample1.svg"
      darkModeUrl: "https://example.com/dark-mode-sample1.svg"
    loadingLogo:
      defaultUrl: "https://example.com/sample2.svg"
      darkModeUrl: "https://example.com/dark-mode-sample2.svg"
    faviconUrl: "https://example.com/sample3.svg"
    applicationTitle: "My Custom Title"
```

so, i tried like this and it works, i don't know why the previous one doesn't work

```
additionalConfig:
  opensearchDashboards.branding.logo.defaultUrl: "https://example.com/sample.svg"
  opensearchDashboards.branding.logo.darkModeUrl: "https://example.com/dark-mode-sample.svg"
  opensearchDashboards.branding.mark.defaultUrl: "https://example.com/sample1.svg"
  opensearchDashboards.branding.mark.darkModeUrl: "https://example.com/dark-mode-sample1.svg"
  opensearchDashboards.branding.loadingLogo.defaultUrl: "https://example.com/sample2.svg"
  opensearchDashboards.branding.loadingLogo.darkModeUrl: "https://example.com/dark-mode-sample2.svg"
  opensearchDashboards.branding.faviconUrl: "https://example.com/sample3.svg"
  opensearchDashboards.branding.applicationTitle: "My Custom Title"
```
