### ISSUE TITLE
Operator not creating an OpenSearch cluster in EKS with Kubernetes 1.24.9

### ISSUE THREAD

**Issue by beejaygee** [Opster/opensearch-k8s-operator#427]
Hi, 

I'm getting the same issue as in: https://github.com/Opster/opensearch-k8s-operator/issues/295 which was closed seemingly without confirming with @KeithMHughesRoteraAI that the issue was resolved. 

I get the error "exec /bin/sh: exec format error" in my init container for my bootstrap pod and Opensearch cluster never creates. I am using arm64 as my build. 

Can you please assist? Not sure what's going on. Is there a way to manually specify the architecture somehow?

**Comment by beejaygee** [comment]
I've figured out how to manually specify an initHelper and when I set it to "arm64v8/busybox" then it works as normal. For some reason when using your container build, K8s isn't able to determine the correct architecture. Not sure why.

**Comment by KeithMHughesRoteraAI** [comment]
Awesome! Can you please share your descriptor?

Keith Hughes
CTO, Rotera, AI

**Comment by beejaygee** [comment]
Hi Keith,

It's pretty simple. Please see below:

`apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  initHelper:
    image: "arm64v8/busybox"
  general:
    serviceName: my-first-cluster
    version: 2.3.0
  dashboards:
    enable: true
    version: 2.3.0
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "5Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"`

**Comment by KeithMHughesRoteraAI** [comment]
Thanks!

**Comment by beejaygee** [comment]
I have found that the OMC has the same issue. Instead of finding a specific ARM64 image, I've had to use a nodeSelector to make it use AMD64 only. Otherwise the container that is used contains a Java version which is not ARM64.

**Comment by beejaygee** [comment]
> Hey @beejaygee, do you have ARM64 and AMD arch nodes on your k8s cluster ?
Prior to having to work around the issue with OMC, I was on pure ARM64 nodes. I worked around the issue with bootstrap by setting an ARM64 only image. I didn't have an ARM64 only image for OMC so to work around that I set up a nodeSelector to require AMD64, at which point Karpenter in AWS EKS set up a new AMD64 node and scheduled the OMC pod/s onto it and then OMC worked without issue.

**Comment by rhys-evans** [comment]
Be careful with this as when running multi arch k8s clusters the, the bootstrap pods node affinity also needs to be set to the relevant architecture, otherwise you may get the same issue on that

IE

```
spec:
   bootstrap:
       nodeSelector:
           kubernetes.io/arch: amd64 / arm64
```

**Comment by swoehrl-mw** [comment]
Hi @beejaygee. Thanks for reporting this. Looks like there was a problem when the busybox image was originally uploaded and the arm variant was not included correctly. We are working on pushing a fixed image to the registry.

**Comment by Amos-85** [comment]
Same issue for me on AKS `v1.24.6`, the cluster do not bootstrap

crd:
```
- apiVersion: opensearch.opster.io/v1
  kind: OpenSearchCluster
  metadata:
    name: opensearch-cluster
    namespace: opensearch
  spec:
    general:
      serviceName: opensearch-cluster
      version: 2.3.0
    security:
      config:
        securityConfigSecret:
          name: opensearch-secrets
      tls:
        transport:
          generate: true
        http:
          generate: true
    dashboards:
      enable: true
      version: 2.3.0
      replicas: 1
      basePath: /opensearch
      resources:
        requests:
          memory: "512Mi"
          cpu: "200m"
        limits:
          memory: "512Mi"
          cpu: "200m"
    nodePools:
    - component: nodes
      replicas: 3
      diskSize: "5Gi"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
      - "cluster_manager"
      - "data"
```
