### ISSUE TITLE
OS 2.3 dashboards failing: Startup probe failed

### ISSUE THREAD

**Issue by llermaly** [Opster/opensearch-k8s-operator#434]
Hi,

I'm trying to run the following yml: 

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: os-cluster
  namespace: default
spec:
  security:
    config:
    tls:
      http:
        generate: true
      transport:
        generate: true
        perNode: true
  general:
    httpPort: 9200
    serviceName: os-cluster
    version: 2.3.0
    pluginsList: ["repository-s3"]
    drainDataNodes: true
  dashboards:
    tls:
      enable: true
      generate: true
    version: 2.3.0
    enable: true
    replicas: 1
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "512Mi"
        cpu: "200m"
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 1
      diskSize: "10Gi"
      nodeSelector:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      roles:
        - "master"
        - "data"
    - component: nodes
      replicas: 1
      diskSize: "10Gi"
      nodeSelector:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "data"
    - component: coordinators
      replicas: 1
      diskSize: "10Gi"
      nodeSelector:
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
      roles:
        - "ingest"
```

OpenSearch nodes run fine, but dashboards are having issues:

`pod observe`

```
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  27m                  default-scheduler  Successfully assigned default/os-cluster-dashboards-59bd69557b-q7lht to docker-desktop
  Normal   Pulling    27m                  kubelet            Pulling image "docker.io/opensearchproject/opensearch-dashboards:2.3.0"
  Normal   Pulled     23m                  kubelet            Successfully pulled image "docker.io/opensearchproject/opensearch-dashboards:2.3.0" in 3m15.334664379s
  Normal   Killing    20m                  kubelet            Container dashboards failed startup probe, will be restarted
  Normal   Created    19m (x2 over 23m)    kubelet            Created container dashboards
  Normal   Started    19m (x2 over 23m)    kubelet            Started container dashboards
  Normal   Pulled     19m                  kubelet            Container image "docker.io/opensearchproject/opensearch-dashboards:2.3.0" already present on machine
  Warning  Unhealthy  19m                  kubelet            Startup probe failed: Get "https://10.1.0.41:5601/api/reporting/stats": dial tcp 10.1.0.41:5601: connect: connection refused
  Warning  Unhealthy  105s (x60 over 23m)  kubelet            Startup probe failed: HTTP probe failed with statuscode: 503
```

`pod logs`
```
{"type":"log","@timestamp":"2023-02-14T23:03:31Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"visTypeXy\" is disabled."}
{"type":"log","@timestamp":"2023-02-14T23:03:31Z","tags":["info","plugins-service"],"pid":1,"message":"Plugin \"wizard\" is disabled."}
{"type":"log","@timestamp":"2023-02-14T23:03:31Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpu.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuPath\""}
{"type":"log","@timestamp":"2023-02-14T23:03:31Z","tags":["warning","config","deprecation"],"pid":1,"message":"\"cpuacct.cgroup.path.override\" is deprecated and has been replaced by \"ops.cGroupOverrides.cpuAcctPath\""}
{"type":"log","@timestamp":"2023-02-14T23:03:32Z","tags":["info","plugins-system"],"pid":1,"message":"Setting up [46] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,alertingDashboards,share,opensearchUiShared,expressions,data,home,console,apmOss,management,indexPatternManagement,advancedSettings,savedObjects,securityDashboards,reportsDashboards,indexManagementDashboards,anomalyDetectionDashboards,queryWorkbenchDashboards,notificationsDashboards,legacyExport,embeddable,dashboard,visualizations,visTypeVega,visTypeTimeline,timeline,visTypeTable,visTypeMarkdown,tileMap,regionMap,customImportMapDashboards,inputControlVis,visualize,ganttChartDashboards,bfetch,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,discover,savedObjectsManagement,observabilityDashboards]"}
{"type":"log","@timestamp":"2023-02-14T23:03:33Z","tags":["info","savedobjects-service"],"pid":1,"message":"Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations..."}
{"type":"log","@timestamp":"2023-02-14T23:03:33Z","tags":["info","savedobjects-service"],"pid":1,"message":"Starting saved objects migrations"}
{"type":"log","@timestamp":"2023-02-14T23:04:03Z","tags":["error","opensearch","data"],"pid":1,"message":"[TimeoutError]: Request timed out"}
{"type":"log","@timestamp":"2023-02-14T23:04:03Z","tags":["warning","savedobjects-service"],"pid":1,"message":"Unable to connect to OpenSearch. Error: Request timed out"}
{"type":"log","@timestamp":"2023-02-14T23:04:36Z","tags":["error","opensearch","data"],"pid":1,"message":"[TimeoutError]: Request timed out"}
{"type":"log","@timestamp":"2023-02-14T23:05:08Z","tags":["error","opensearch","data"],"pid":1,"message":"[TimeoutError]: Request timed out"}
{"type":"log","@timestamp":"2023-02-14T23:05:41Z","tags":["error","opensearch","data"],"pid":1,"message":"[TimeoutError]: Request timed out"}
```

Thanks
