### ISSUE TITLE
ISM Policies Support

### ISSUE THREAD

**Issue by Amos-85** [Opster/opensearch-k8s-operator#435]
Hi,
I've wonder what is the proper way to manage ism policies after cluster initialization ?

Is there any workaround until the operator will be formally supported to mange ISM policies by the operator ?

**Comment by swoehrl-mw** [comment]
Hi @Amos-85. The only way currently is to manage the policies yourself using the normal OpenSearch APIs.

**Comment by Amos-85** [comment]
Hi @swoehrl-mw ,
Is it possible to add pod lifecycle hooks to node pools crd as workaround solution before implementing ism policies solution as part of the crd's ?
I saw it's part of the opensearch roadmap in [dev-plan.md](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/dev-plan.md)

I ran a shell script to invoke ism api within the helm chart of opensearch by using pod lifecycle `postStart`, it might be much more convenient to run a post script instead of running k8s job and mounting the certs.

**Comment by swoehrl-mw** [comment]
> Is it possible to add pod lifecycle hooks to node pools crd as workaround solution before implementing ism policies solution as part of the crd's ?

There are no plans for it. I'm also unsure if this would be a good workaround. But if someone wants to implement such hooks, we can talk about a possible integration.

**Comment by AndersBennedsgaard** [comment]
@idanl21 can we open this again?
As ISM policies is a part of the [dev-plan](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/dev-plan.md), it makes sense to have an issue open for discussing the design and tracking progress. That also makes it easier for others to open PRs (we could be interested in doing this, as we would like to remove the dependency to the `security-admin.sh` as much as possible)

**Comment by idanl21** [comment]
Hey @AndersBennedsgaard, i will reopen the ticket.
Can you please explain the connection to `security-admin.sh` ?

**Comment by AndersBennedsgaard** [comment]
I thought that ISM policies was a part of the security plugin, which is obviously not the case, sorry..

The reason we want to remove as much use of `security-admin.sh` as possible, is that each time you run `security-admin.sh`, you might lose data/configuration which you have done using the REST API/OpenSearch Dashboards.
Additionally, we would like to remove the requirement for the OS nodes to have TLS enabled for the REST API, since we want to use Istio for mTLS instead

**Comment by IshaGirdhar** [comment]
Initial thoughts
1. Create a Custom Resource Definition (CRD) that represents the ISM policies, ensuring that it includes fields corresponding to the configuration structure.
For that, we can dynamically convert the [JSON schema for the ISM policy configuration](https://github.com/opensearch-project/index-management/blob/main/src/main/resources/mappings/opendistro-ism-config.json) into an openAPI V3 Schema. This converted schema will be utilized in the CRD. Although there are available tools for conversion(e.g https://www.npmjs.com/package/@openapi-contrib/json-schema-to-openapi-schema), none of them are perfect. Therefore, it may be necessary to use some tool as a starting point and build upon it. 

2. Improve the operator's logic to handle the CR for ISM policies.
This entails implementing functionality to monitor changes in ISM policy objects, validate the provided configurations, and execute the required actions based on the defined policies.

**Comment by cthtrifork** [comment]
Can someone elaborate on the dev-plan for this? Is there any expected timeline such as 2023Q4, end of 2023 or similar. Are you expecting to solve this yourself or is it reliant on opensource contributions?

**Comment by gaurav-05** [comment]
> 

@idanl21 @swoehrl-mw The idea being proposed here is like we will have ISMPolicy CRD which is to define ISMPolicy CR and then ISMPolicyTemplate CRD which will be to attach ISM policy to a index pattern or particular index which is consumed by operator call required ISM API.

We can come up with a detail design and POC but would want to understand your views on this approach.

**Comment by gaurav-05** [comment]
> Initial thoughts
> 
>     1. Create a Custom Resource Definition (CRD) that represents the ISM policies, ensuring that it includes fields corresponding to the configuration structure.
>        For that, we can dynamically convert the [JSON schema for the ISM policy configuration](https://github.com/opensearch-project/index-management/blob/main/src/main/resources/mappings/opendistro-ism-config.json) into an openAPI V3 Schema. This converted schema will be utilized in the CRD. Although there are available tools for conversion(e.g https://www.npmjs.com/package/@openapi-contrib/json-schema-to-openapi-schema), none of them are perfect. Therefore, it may be necessary to use some tool as a starting point and build upon it.
> 
>     2. Improve the operator's logic to handle the CR for ISM policies.
>        This entails implementing functionality to monitor changes in ISM policy objects, validate the provided configurations, and execute the required actions based on the defined policies.

@idanl21 @swoehrl-mw The idea being proposed here is like we will have ISMPolicy CRD which is to define ISMPolicy CR and then ISMPolicyTemplate CRD which will be to attach ISM policy to a index pattern or particular index which is consumed by operator call required ISM API.

We can come up with a detail design and POC but would want to understand your views on this approach.

**Comment by swoehrl-mw** [comment]
@gaurav-05 @IshaGirdhar A CRD for ISMPolicy sounds fine. 
I'm not sure about a separate CRD for ISMPolicyTemplate. Opensearch itself has `ism_template` as part of the policy so I think the CRD should behave similar and have it as part of the policy.
I'd say the main usecase is attaching a policy to an index pattern. Attaching it to specific indices sounds like something I wouldn't want to do via the operator as its more of a one-time thing (normal workflow would be to have the policy with a defined pattern and then create indices).

@cthtrifork 
> Can someone elaborate on the dev-plan for this? Is there any expected timeline such as 2023Q4, end of 2023 or similar

There is no specific timeline. This feature is basically waiting for someone to implement it (looks like @IshaGirdhar and @gaurav-05 want to give it a shot) but we don't plan timelines.

**Comment by IshaGirdhar** [comment]
@swoehrl-mw I have a draft CRD and sample CR ready. Shall I post it here or discuss it in the next features sync up call ?

**Comment by swoehrl-mw** [comment]
@IshaGirdhar Feel free to post it here, having something written makes it easier to read and review in advance.

**Comment by IshaGirdhar** [comment]
ISM Polciies CRD
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ismpolicies.opensearch.opster.io
spec:
  conversion:
    strategy: None
  group: opensearch.opster.io
  names:
    kind: ISMPolicy
    listKind: ISMPolicyList
    plural: ismpolicies
    shortNames:
    - isp
    singular: ismpolicy
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              default_state:
                type: string
              description:
                type: string
              error_notification:
                properties:
                  destination:
                    type: string
                  channel:
                    type: string
                  message_template:
                    properties:
                      source: 
                        type: string
                    type: object
                type: object
              ism_template:
                properties:
                  index_patterns:
                    items:
                      type: string
                    type: array
                  priority:
                    type: integer
                type: object
              policy_id:
                type: string
              last_updated_time:
                type: string
              states:
                items:
                  properties:
                    actions:
                      items:
                        properties:
                          allocation:
                            properties:
                              exclude:
                                type: string
                              include:
                                type: string
                              require:
                                type: string
                              wait_for:
                                type: string
                            required:
                            - require
                            - include
                            - exclude
                            - wait_for
                            type: object
                          close:
                            type: object
                          delete:
                            type: object
                          force_merge:
                            properties:
                              max_num_segments:
                                type: number
                            type: object
                          index_priority:
                            properties:
                              priority:
                                type: number
                            type: object
                          name:
                            type: string
                          notification:
                            properties:
                              destination:
                                type: string
                              message_template:
                                type: object
                            type: object
                          open:
                            type: object
                          read_only:
                            type: string
                          read_write:
                            type: string
                          replica_count:
                            properties:
                              number_of_replicas:
                                type: number
                            type: object
                          retry:
                            properties:
                              backoff:
                                type: string
                              count:
                                type: number
                              delay:
                                type: string
                            type: object
                          rollover:
                            properties:
                              min_doc_count:
                                type: number
                              min_index_age:
                                type: string
                              min_primary_shard_size:
                                type: string
                              min_size:
                                type: string
                            type: object
                          rollup:
                            type: object
                          shrink:
                            properties:
                              aliases:
                                items:
                                  type: object
                                type: array
                              force_unsafe:
                                type: boolean
                              max_shard_size:
                                type: string
                              num_new_shards:
                                type: integer
                              percentage_of_source_shards:
                                type: number
                              target_index_name_template:
                                type: string
                            type: object
                          snapshot:
                            properties:
                              repository:
                                type: string
                              snapshot:
                                type: string
                            type: object
                          timeout:
                            type: string
                        type: object
                      type: array
                    name:
                      type: string
                    transitions:
                      items:
                        properties:
                          conditions:
                            items:
                              properties:
                                cron:
                                  properties:
                                    expression:
                                      type: string
                                    timezone:
                                      type: string
                                  type: object
                                min_doc_count:
                                  type: number
                                min_index_age:
                                  type: string
                                min_rollover_age:
                                  type: string
                                min_size:
                                  type: string
                              type: object
                            type: array
                          state_name:
                            type: string
                        type: object
                      type: array
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```
ISM policy sample CR
```
apiVersion: opensearch.opster.io/v1
kind: ISMPolicy
metadata:
  name: example-policy
spec:
  policy_id: example-policy
  description: Example policy
  default_state: hot
  states:
    - name: hot            
      actions:              
        - name: rollover
          rollover:
            min_primary_shard_size: "10gb"
            min_index_age: "7d"
      transitions:
        - state_name: warm
    - name: warm
      actions:
        - name : replicas
          replica_count:
            number_of_replicas: 5
      transitions:
        - state_name: delete
          conditions:
          - min_index_age: "30d"
    - name: delete
      actions:
        - name : delete
          delete: {}
  ism_template:
    index_patterns:
      - "logs-*"
    priority: 5
```
