### ISSUE TITLE
Not explicitly defining storageClass for the pvc causes the pvc to be always pending 

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#440]
Issue - The docs mention that we can explicitly define the storageClass if needed. But if we only define the accessMode and not the storageClass then the PVC is always stuck in PENDING state.

Config applied:

```
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "2Gi"
      resources:
         requests:
            memory: "1Gi"
      roles:
        - "data"
        - "cluster_manager"
      persistence:
        pvc:
          accessModes: # You can change the accessMode
          - ReadWriteOnce
```
I think the PVC should use `standard` storageClass when not explicitly defined in the CR.
