### ISSUE TITLE
Feature: Create symlink for repository-s3 plugin to read ServiceAccount token

### ISSUE THREAD

**Issue by DimitrisChristinakis** [Opster/opensearch-k8s-operator#442]
I am running an Opensearch cluster using Opensearch Operator in AWS EKS. I have created a ServiceAccount in order to access an AWS S3 bucket to use for my snapshot but i get the following error:

"reason" : "amazon_client_exception: java.security.AccessControlException: access denied ("java.io.FilePermission" "/var/run/secrets/eks.amazonaws.com/serviceaccount/token" "read")",
"caused_by" : {
"type" : "security_exception",
"reason" : "access denied ("java.io.FilePermission" "/var/run/secrets/eks.amazonaws.com/serviceaccount/token" "read")"

The token has the following permissions:
lrwxrwxrwx 1 root root 12 Feb 13 18:21 /var/run/secrets/eks.amazonaws.com/serviceaccount/token -> ..data/token

If i copy this token under the plugin's directory it works normally:
/usr/share/opensearch/plugins/repository-s3/token

To Reproduce

Deploy an Opensearch cluster (image version 2.4.1) with repository-s3 plugin installed
Configure a Kubernetes service account to assume an IAM role
Configure s3.client.default.identity_token_file: /var/run/secrets/eks.amazonaws.com/serviceaccount/token

Expected behavior
Be able to instruct Opensearch Operator to create a symlink as described [here](https://github.com/opensearch-project/OpenSearch/issues/6312)

Plugins
repository-s3 plugin

Host/Environment (please complete the following information):

AWS EKS version 1.21
Opensearch cluster (image version 2.5.0) deployed with Opensearch Operator (version 2.2.0)

**Comment by reta** [comment]
Just to clarify the feature request, when running in k8s on AWS, there is a possibility to use the IRSA (IAM roles for service accounts) for `repository-s3` plugin but it needs access to a web identity token file located at `/var/run/secrets/eks.amazonaws.com/serviceaccount/token`. Then OpenSearch plugins have no access to FS outside its own location or `config` folder (configured by `OPENSEARCH_PATH_CONF`), but creating of the symlink is sufficient:

```
ln -s $AWS_WEB_IDENTITY_TOKEN_FILE "${OPENSEARCH_PATH_CONFIG}/aws-web-identity-token-file"
```

The feature request (or clarification if that is feasible) is to have a way to create a symlink once the OpenSearch is deployed.

**Comment by swoehrl-mw** [comment]
Hi @DimitrisChristinakis. This is a very specific issue so I don't think we can provide a specific fix for this. 
We might be able to add support for some sort of init scripts, but I have a bad feeling about this as it would likely add complexity and make the startup process more unstable.

As a workaround: Could you mount the serviceaccount secret using the additionalVolumes feature (https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#additional-volumes) into a reachable path?

**Comment by rhysxevans** [comment]
Hi

So I don't think this is a specific usecase per say, but I understand the logic in the statement. I am having the same issue, around the use of IAM roles as service accounts. I have done a basic hack , needs more thorough testing and cleanup, but what I have is below (and yes the idea was shamelessly stolen from somewhere else).

Some fields need to be configure to what your infra looks like, IE namespace, cluster

you also need to set the additionalConfig 

`s3.client.default.identity_token_file: /usr/share/opensearch/plugins/repository-s3/token`

```

cat <<EOF | kubectl apply -f -
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: opensearch
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
EOF

cat <<EOF | kubectl apply -f -
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: opensearch
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
EOF


cat <<"EOF" | kubectl apply -f -
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-backupscript
  namespace: opensearch
data:
  backupscript.sh: | 
    #!/bin/bash
    echo 'getting pod name'
    podNames=$(kubectl -n opensearch get pods --selector='opster.io/opensearch-cluster=cluster' --field-selector=status.phase=Running --output=jsonpath={.items..metadata.name})
    echo $podNames
    for podName in $podNames
    do 
      kubectl -n opensearch exec -i $podName -c opensearch -- ln -sf /var/run/secrets/eks.amazonaws.com/serviceaccount/token /usr/share/opensearch/plugins/repository-s3/token
    done
    echo 'done'
EOF

cat <<'EOF' | kubectl apply -f -
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-cron
  namespace: opensearch
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                    - amd64
          volumes:
          - name: backup-script
            configMap:
              name: cm-backupscript
              defaultMode: 0777
          containers:
          - name: kubectl
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - /mnt/scripts/backupscript.sh
            volumeMounts:
            - name: backup-script
              mountPath: "/mnt/scripts"
          restartPolicy: Never
EOF
```

Your mileage may vary, hopefully a more longer term solution can be found

Thanks
