### ISSUE TITLE
Recovery for cluster using emptyDir as persistence

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#443]
Issue - We have a dev profile (mostly used for testing and development) in which we don't have PVC as persistence and generally just use emptyDir. So, when the majority pods (or all pods) go down, the pods are not able to initialize again. 

Error - The error is about the master election as the pods are not able to reach quorum. But even if that is fixed, I think it would complain that the security indices are not created. As there is no persistence, the security-config job probably needs to run again.

Config used - 
```
nodePools:
  - component: masters
       replicas: 3
       resources:
         requests:
           memory: "1Gi"
       roles:
       - "data"
       - "cluster_manager"
       persistence:
         emptyDir: { }
```
The simplest way around this would be to just delete the cluster and apply the yaml again but IMO the cluster should be able to at least start back up again no matter the persistence being used.
