### ISSUE TITLE
Parallel recovery for nodePool with 2 replicas

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#444]
Config - 
```
  nodePools:
    - component: masters
      replicas: 2
      resources:
         requests:
            memory: "1Gi"
      roles:
        - "data"
        - "cluster_manager"
      diskSize: "1Gi"
```
When I delete only one pod, the pod starts up again and the 2 pods are able to form quorum again. But if I delete both the pods, only one pod comes up at a time as sts has `OrderedReady` podManagementPolicy so the single pod is not able to form a quorum. The parallel recovery should also kick in in this case and allow both the pods to come up together.
