### ISSUE TITLE
Keystore configuration causes endless rolling restart

### ISSUE THREAD

**Issue by maxpschonder** [Opster/opensearch-k8s-operator#446]
Hey folks,

I'm facing a strange issue where pods in the cluster constantly restart when I add a keystore configuration. My general config looks like this:

```
  general:
    drainDataNodes: true
    httpPort: 9200
    pluginsList:
      - https://github.com/aiven/encrypted-repository-opensearch/releases/download/v2.4.1.0/encrypted-repository-2.4.1.0.zip
      - https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.4.1.0/prometheus-exporter-2.4.1.0.zip
      - repository-s3
    keystore:
      - keyMappings:
          accessKeyId: s3.client.default.access_key
          secretAccessKey: s3.client.default.secret_key
        secret:
          name: s3-credentials-snapshots
      - keyMappings:
          private_key: encrypted.s3.default.private_key
          public_key: encrypted.s3.default.public_key
        secret:
          name: snapshot-encryption-keypair
    serviceName: opensearch-cluster
    vendor: opensearch
    version: 2.4.1
```

I think the operator is incorrectly detecting a change in all stateful sets and is trying to patch that. I'm receiving messages like this:
```
2023-02-23T14:39:40.233887716Z 1.6771631802336226e+09	DEBUG	resource diff	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"opensearch-cluster","namespace":"opensearch"}, "namespace": "opensearch", "name": "opensearch-cluster", "reconcileID": "d99b19f4-4c37-4c71-b8ec-488e0d309572", "reconciler": "cluster", "name": "opensearch-cluster-manager", "namespace": "opensearch", "apiVersion": "apps/v1", "kind": "StatefulSet", "patch": "{\"spec\":{\"template\":{\"spec\":{\"$setElementOrder/initContainers\":[{\"name\":\"init\"},{\"name\":\"keystore\"}],\"initContainers\":[{\"$setElementOrder/volumeMounts\":[{\"mountPath\":\"/tmp/keystore\"},{\"mountPath\":\"/tmp/keystoreSecrets/s3-credentials-snapshots/s3.client.default.access_key\"},{\"mountPath\":\"/tmp/keystoreSecrets/s3-credentials-snapshots/s3.client.default.secret_key\"},{\"mountPath\":\"/tmp/keystoreSecrets/snapshot-encryption-keypair/encrypted.s3.default.private_key\"},{\"mountPath\":\"/tmp/keystoreSecrets/snapshot-encryption-keypair/encrypted.s3.default.public_key\"}],\"name\":\"keystore\"}]}}}}"}
```

It would be great if someone could tell me what's happening here.
