### ISSUE TITLE
Operator  does not create cluster

### ISSUE THREAD

**Issue by Jeansen** [Opster/opensearch-k8s-operator#447]
I've deployed the operator:
```
helm repo add opensearch-operator https://opster.github.io/opensearch-k8s-operator
helm repo update
helm install opensearch-operator opensearch-operator/opensearch-operator
```

I then tried to create an example cluster:

```
cat <<EOF | kubectl apply -f -
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster
  namespace: default
spec:
  general:
    version: "2.5.0"
    httpPort: 9200
    vendor: opensearch
    serviceName: my-cluster
  security:
    config:
      adminCredentialsSecret:
        name: admin-credentials-secret
      securityConfigSecret:
       name: securityconfig-secret
    tls:
      transport:
        generate: true
      http:
        generate: true
  dashboards:
    version: "2.6.0"
    enable: true
    replicas: 2
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "30Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
EOF
```

But nothing happens.

Logs of the opensearch-operator-controller-manager show repetitions of:

```
1.6772267614334307e+09	INFO	Reconciling OpenSearchCluster	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"my-cluster","namespace":"default"}, "namespace": "default", "name": "my-cluster", "reconcileID": "05ef994f-b242-42e9-932c-e68e22e35966", "cluster": "default/my-cluster"}
1.677226761531804e+09	INFO	Generating certificates	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"my-cluster","namespace":"default"}, "namespace": "default", "name": "my-cluster", "reconcileID": "05ef994f-b242-42e9-932c-e68e22e35966", "interface": "transport"}
1.677226761531903e+09	INFO	Generating certificates	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"my-cluster","namespace":"default"}, "namespace": "default", "name": "my-cluster", "reconcileID": "05ef994f-b242-42e9-932c-e68e22e35966", "interface": "http"}
1.6772267615319405e+09	INFO	Waiting for secret 'securityconfig-secret' that contains the securityconfig to be created	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"my-cluster","namespace":"default"}, "namespace": "default", "name": "my-cluster", "reconcileID": "05ef994f-b242-42e9-932c-e68e22e35966"}
E0224 08:19:21.531964       1 event.go:340] Unsupported event type: 'Info'
```
