### ISSUE TITLE
Dashboards does not work for single-node cluster

### ISSUE THREAD

**Issue by pkutakov** [Opster/opensearch-k8s-operator#450]
For a simple testing purposes I would like to deploy minimal single-node cluster. While it seems to be OK from kubernetes point of view, Dashboards cannot open after login and failed with "Internal server error":
![image](https://user-images.githubusercontent.com/7010549/221851821-47fc903a-c332-449a-82bc-bc3423b1158a.png)

When checking the dashboard pod logs, I can see another error - "Request timeout":
![image](https://user-images.githubusercontent.com/7010549/221852039-5f0d57ec-e5f4-443e-ad98-5b64641cc47e.png)

This is NOT happening when number of nodes in the cluster is >=2. So if I will just change number of replicas for a nodes in the following file to 2, it works!

Here is my yaml:
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: oss-small
  namespace: default
spec:
  general:
    version: 2.5.0
    httpPort: 9200
    vendor: opensearch
    serviceName: oss-small
    pluginsList: ["repository-s3","https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.5.0.0/prometheus-exporter-2.5.0.0.zip"]
  dashboards:
    version: 2.5.0
    enable: true
    replicas: 1
    resources:
      requests:
         memory: "1Gi"
         cpu: "500m"
      limits:
         memory: "1Gi"
         cpu: "500m"
  confMgmt:
    smartScaler: true
  nodePools:
    - component: nodes
      replicas: 1
      diskSize: "30Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
        - "cluster_manager"
        - "ingest"
```
