### ISSUE TITLE
SKIP_INIT_CONTAINER not working. 

### ISSUE THREAD

**Issue by hgoura** [Opster/opensearch-k8s-operator#452]
Hi, 

I'm trying to deploy opensearch cluser and ran into the below issue. Can you please share the opensearch-cluster.yaml with working SKIP_INIT_CONTAINER section. 
We have strict permissions for containers to not run as root. 

I have tried to update SKIP_INIT_CONTAINER under values.yaml and tried to deploy the cluster, but that didn't help. still the init container is trying to get created and is assigned runAsUser: 0

Thanks in advance!

**Comment by idanl21** [comment]
Hey @hgoura 
can you please share your yaml file ?

**Comment by hgoura** [comment]
```
nodeSelector: {}
tolerations: []
manager:
  extraEnv:
    - name: SKIP_INIT_CONTAINER
      value: "true"
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 350Mi

  livenessProbe:
    failureThreshold: 3
    httpGet:
      path: /healthz
      port: 8081
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10

  readinessProbe:
    failureThreshold: 3
    httpGet:
      path: /readyz
      port: 8081
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10

  # Set this to false to disable the experimental parallel recovery in case you are experiencing problems
  parallelRecoveryEnabled: true

  image:
    repository: public.ecr.aws/opsterio/opensearch-operator
    ## tag default uses appVersion from Chart.yaml, to override specify tag tag: "v1.1"
    tag: "2.2.1"
    pullPolicy: "Always"

  dnsBase: cluster.local

  # If a watchNamespace is specified, the manager's cache will be restricted to
  # watch objects in the desired namespace. Defaults is to watch all namespaces.
  watchNamespace:

kubeRbacProxy:
  resources:
    limits:
      cpu: 50m
      memory: 50Mi
    requests:
      cpu: 25m
      memory: 25Mi

  livenessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 8443
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10

  readinessProbe:
    failureThreshold: 3
    tcpSocket:
      port: 8443
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    initialDelaySeconds: 10

  image: 
    repository: "gcr.io/kubebuilder/kube-rbac-proxy"
    tag: "v0.13.1"
```
