### ISSUE TITLE
Single pod termination in Statefulset causes all lower ordinal pods to terminate which can cause yellow state if highest ordinal pod is terminated

### ISSUE THREAD

**Issue by ccben87** [Opster/opensearch-k8s-operator#464]
Single pod termination in Statefulset causes all lower ordinal pods to terminate which can cause cluster yellow status if the original terminated pod is the highest ordinal in the Statefulset which results in termination of all pods in the node group. I have found that this happens on version 2.4.1 and onwards but not on 2.4.0 and earlier. When testing by terminating a pod in a cluster of 3 nodes, all pods with a lower ordinal number terminate (all pods in the node group terminate) which causes a yellow cluster state. I have also found that disabling the dashboard results in an odd behaviour in versions 2.4.0 and below when terminating the highest ordinal pod in a node group's Statefulset. When this is done in a Statefulset with 3 replicas, the middle ordinal numbered pod gets terminated as well as the highest ordinal pod number but the lowest ordinal number pod remains up and working properly. Not sure why changing dashboard from true to false would cause the middle ordinal pod in a Statefulset of 3 replicas to incorrectly terminate when the highest ordinal pod gets terminated with the lowest ordinal working normally.

I can replicate this using the default config provided in your guide with the version number increased to 2.4.1:

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
    version: 2.4.1
  dashboards:
    enable: true
    version: 2.4.1
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "5Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
```

With the above configuration (version 2.4.1), when running "kubectl delete pod/my-first-cluster-nodes-2" the following happens:

![image](https://user-images.githubusercontent.com/128038118/225584805-8a90a239-ddc9-4628-b142-ab65f9e336df.png)

With the same configuration but with version 2.4.0 this happens (which is expected):

![image](https://user-images.githubusercontent.com/128038118/225587242-3c5e5de5-3cd0-4999-883e-a95a8ade7470.png)

This is what happens when running "kubectl delete pod/my-first-cluster-nodes-1", you can see that only the lower ordinal numbered pods get terminated.

![image](https://user-images.githubusercontent.com/128038118/225589258-82ff3a24-79ad-4551-bfb0-4d6d08ab0405.png)

I'm not sure if this is a bug in Opensearch or a bug in Opensearch Operator or how to troubleshoot this further.
