### ISSUE TITLE
Support for creating/managing index templates

### ISSUE THREAD

**Issue by gaurav-05** [Opster/opensearch-k8s-operator#465]
Can we have some option to create index templates and/or ISM policies OOB once a OS cluster is created. As we may have a usecase where we want fluentbit to start pushing logs to OS cluster as soon as it is up but would thus want that there is an index template created before OS starts ingesting.

_Originally posted by @gaurav-05 in https://github.com/Opster/opensearch-k8s-operator/discussions/455_

**Comment by idanl21** [comment]
Hey @gaurav-05 
ISM is an applicative mechanism of OpenSearch, unfortunately the Operator is not supporting it yet.
we already have an open Issue for it, [https://github.com/Opster/opensearch-k8s-operator/issues/435](url).
closing the issue, please take a look at the details that are on the attached issue.

**Comment by gaurav-05** [comment]
@idanl21 The current ask is more generic not only limited to ISM policies but index templates too, if we want to create something at the initial setup. I see the issue you pointed is for ISM support but one WA is discussed which is close to what we want to achieve. Can you please confirm are you referring to same.

**Comment by AndersBennedsgaard** [comment]
@idanl21 can we open this again, and perhaps have @gaurav-05 to change the title to only include templates since https://github.com/Opster/opensearch-k8s-operator/issues/435 already exists?
As index/component/other templates is a part of the [dev-plan](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/dev-plan.md), it makes sense to have an issue open for discussing the design and tracking progress.

**Comment by AndersBennedsgaard** [comment]
@idanl21 sorry if this is unnecessary, but have you seen my question above?

**Comment by swoehrl-mw** [comment]
@AndersBennedsgaard changed the title and reopened issue

**Comment by AndersBennedsgaard** [comment]
FYI @swoehrl-mw I am currently looking at this. Atm. I have created two CRDs: OpensearchComponentTemplate and OpensearchIndexTemplate.
An instance of the OpensearchComponentTemplate could (currently) look like:

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpensearchComponentTemplate
metadata:
  name: sample-component-template
spec:
  opensearchCluster:
    name: my-first-cluster

  template: # required
    aliases: # optional
      my_alias: {}
    settings: # optional
      number_of_shards: 2
      number_of_replicas: 1
    mappings: # optional
      properties:
        timestamp:
          type: date
          format: yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis
        value:
          type: double
  version: 1 # optional
  allowAutoCreate: false # optional
  _meta: # optional
    description: example description
```

An OpensearchIndexTemplate instance could currently look like:

```yaml
```
