### ISSUE TITLE
Document usage of setVMMaxMapCount

### ISSUE THREAD

**Issue by swoehrl-mw** [Opster/opensearch-k8s-operator#474]
From #241.

The usage of setVMMaxMapCount is not documented in the userguide. 

```yaml
spec:
  general:
    setVMMaxMapCount: true
```

This helps with errors like ` max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]`.
