### ISSUE TITLE
CRD for Action Groups

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#485]
Following up on #254 , this issue is track adding CRD for the action_groups.yml in the securityconfig-secret. Similar to existing CRDs like opensearchusers, opensearchroles etc. a new CRD for action groups i.e. opensearchactiongroups will be added. 

The proposed API:

```
apiVersion: opensearch.opster.io/v1
kind: OpensearchActionGroup
metadata:
  name: sample-action-group
  namespace: default
spec:
  opensearchCluster:
    name: my-first-cluster
  allowedActions:                                #type []string
    - "indices:admin/aliases/get",
    - "indices:admin/aliases/exists"
  type: "index"                                  #type string
  description: "Sample action group"             #type string
```

These fields were decided based on the OS API and what it supports for the action groups via REST API. [Reference](https://opensearch.org/docs/2.6/security/access-control/api/#action-groups).
