### ISSUE TITLE
CRD for Tenants

### ISSUE THREAD

**Issue by saketmht** [Opster/opensearch-k8s-operator#491]
Following up on https://github.com/Opster/opensearch-k8s-operator/issues/254 , this issue is track adding CRD for the tenants.yml in the securityconfig-secret. Similar to existing CRDs like opensearchusers, opensearchroles etc. a new CRD for tenants i.e. opensearchtenants will be added.

The proposed API:
```
apiVersion: opensearch.opster.io/v1
kind: OpensearchTenant
metadata:
  name: sample-tenant
  namespace: default
spec:
  opensearchCluster:
    name: my-first-cluster
  description: "Sample tenant"             #type string
```

These fields were decided based on the OS API and what it supports for the tenants via REST API. [Reference](https://opensearch.org/docs/2.6/security/access-control/api/#create-tenant).
