### ISSUE TITLE
Compatibility with HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by akarX23** [Opster/opensearch-k8s-operator#510]
Since the autoscaling feature is in development, I attempted to autoscale the cluster manually. If the number of `replicas` are changed in the `OpenSearchCluster` configuration, the StatefulSets will work without issues since the operator directly controls them. 

However, using `k scale statefulset --replicas 10 -n opensearch-operator akarx-cluster-data` the StatefulSets don't respond with a new number of replicas since the Operator resets them to the `replicas` value. Configuring a `HorizontalPodAutoscaler` also doesn't work because of these reasons. But if we have some scaling policies in the HPA to not decrease the number of Pods by a large amount, I think that should be allowed.

Here is how my HPA configuration looks like:

```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: opensearch-data-scaler
  namespace: opensearch-operator
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: akarx-cluster-data
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 100
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60
    scaleUp:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 25
```
We can limit the `scaleDown` to allow only 1 Pod termination in a 60 second window. This will give time to the operator to rebalance the cluster. 

Could you please guide me on how I can experiment with this feature in the Operator configuration, specifically which files would I need to change? Thanks for all the help!
