### ISSUE TITLE
[Proposal] Add autoscaling capability to the operator.

### ISSUE THREAD

**Issue by Moss-CG** [Opster/opensearch-k8s-operator#517]
## Background:
As part of the [next phase roadmap](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/designs/dev-plan.md) automatic scaling capability will be added to the operator; to allow configuration of autoscaling logic via a new CRD.

## Proposal:
<details open>
  <summary>Autoscaler CRD example</summary>

```
apiVersion: opensearch.opster.io/v1
kind: Autoscaler
metadata:
  name: my-cluster-autoscaler
  namespace: default
spec:
  cluster: my-cluster
  rules:
    - items:
      - metric: 'opensearch_os_cpu_percent'
        operator: ">"
        threshold: "75.0"
        queryOptions:
          labelMatchers:
            - 'name="parent"'
          interval: "10m"
          function: "avg_over_time"
      - metric: 'opensearch_os_mem_used_percent'
        operator: ">"
        threshold: "90.0"
        queryOptions:
          labelMatchers:
            - 'name="parent"'
          interval: "10m"
          function: "avg_over_time"
      nodeRole: "data"
      behavior:
        scaleUp:
          enable: true
          minReplicas: 1
          maxReplicas: 3
    - items:
      - metric: 'opensearch_os_cpu_percent'
        operator: "<"
        threshold: "40.0"
        queryOptions:
          labelMatchers:
            - 'name="parent"'
          interval: "10m"
          function: "avg_over_time"
      nodeRole: "data"
      behavior:
        scaleDown:
          enable: true
          minReplicas: 1
          maxReplicas: 3
``` 
</details>

### Autoscaler Custom Resource Reference Guide  
<details open>
  <summary>Autoscaler</summary>

The Autoscaler CRD is defined by kind: `Autoscaler`, group: `opensearch.opster.io` and version `v1`.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| apiVersion | string | opensearch.opster.io/v1 | true |
| kind | string | Autoscaler | true |
| metadata | object | Refer to the Kubernetes API documentation for the fields of the `metadata` field. | true |
| spec | object | AutoscalerSpec defines the desired configuration of the autoscaler. | true |

</details>
<details open>
  <summary>Autoscaler.spec</summary>

### Autoscaler.spec
AutoscalerSpec defines the desired configuration of the autoscaler.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| cluster | string |  | A specific cluster to bundle with the ruleset. | false
| rules | []Rule | The container for lists of type Rule, defining scaling logic. | true |

</details>
<details open>
  <summary>Rule</summary>

### Rule
Rule defines a single rule.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| items | []Item | A list of type Item, defining conditions for scaling. | true |
| nodeRole | string | The role of the Opensearch node type you would like to target for scaling. | true |
| behavior | Scale | The container for the scaling behavior of the ruleset. | true |

</details>
<details open>
  <summary>Item</summary>

### Item
Item defines a singular item in a rule.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| metric | string | A prometheus metric to target for performing conditional operations. | true |
| operator | string | The operator to use for comparing the prometheus query result and threshold. | true |
| threshold | string | The threshold value for taking scaling action. | true |
| queryOptions | QueryOptions | Optional additions to the prometheus query. | false |

</details>
<details open>
  <summary>QueryOptions</summary>

### QueryOptions
QueryOptions defined additional query configurations.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| labelMatchers | []string | A prometheus supported label matcher to limit results. | false |
| interval | string | A prometheus supported interval of time over which to query. | false |
| function | string | A prometheus supported function wrapper. | false |

</details>
<details open>
  <summary>Behavior</summary>

### Behavior
Behavior defines a scaling behavior for a rule.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| scaleUp | ScaleConf | Container for upscaling behavior. | false |
| scaleDown | ScaleConf | Container for downscaling behavior. | false |

</details>
<details open>
  <summary>ScaleConf</summary>

### ScaleConf
Scaling behavior for scaling up or down.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| enable | boolean | Container for upscaling behavior. | false |
| minReplicas | int32 | Minimum amount of replicas to scale down to. | false |
| maxReplicas | int32 | Maximum amount of replicas to scale up to. | false |

</details>

In addition to the new autoscaler CRD, changes to the existing OpensearchCluster CRD are desired, specifically the generalConfig and nodePools.

<details open>
  <summary>OpensearchCluster.General.Autoscaler</summary>

### OpensearchCluster.General.Autoscaler
Addition of an `Autoscaler` section under generalConfig.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| enable | boolean | Enables or disables autoscaling functionality. | false |
| prometheusEndpoint | string | A prometheus endpoint to monitor. | false |
| scaleTimeout | int | The amount of time to wait before scaling since last scale or cluster creation in minutes. | false |
| clusterPolicy | string | The override to set a cluster specific autoscale policy. | false |

</details>
<details open>
  <summary>OpensearchCluster.nodePools</summary>

### OpensearchCluster.nodePools
Addition of `AutoScalePolicy` to nodePools.
| Name | Type | Description | Required |
|--------|--------|--------|--------|
| autoScalePolicy | string | The name of an autoscaler that the user has applied. | false |

</details>

<br>

## Design
The two main components of the autoscaler are 1.) the logic behind scaling actions and 2.) the design of queries to be sent to prometheus.

### Logical considerations
- The Autoscaler CRD is created with a cluster level resource scope. This is to allow it to be available from any namespace the user places an OpenSearch cluster in.
- Opensearch nodes of type `master` or `cluster_manager` will be excluding from being allowed to scale. This may change in the future, but for now I have omitted these types for safety.
- The addition of the `AutoScalePolicy` field to `nodePools` is designed to allow users to create a singular autoscaler and assign it to multiple clusters nodePools. This nodePool level policy can be overridden/omitted if users instead want to have autoscaling policies set at the cluster level via the `clusterPolicy` field in the AutoscalerConfig added to the OpenSearchCluster spec.
- If the user omits or enters a negative value for `minReplicas` in a scaling rule, the scaler will default to `minReplicas` of 1 as we should never want to scale to zero nodes. If `maxReplicas` is 0, I plan to default to an acceptable number of nodes max, but have not decided on a number yet.
- Scaling decisions will only ever increment or decrement the number of nodes by 1 at a time.
- A timestamp will be recorded to the nodes stateful-set when a scaling decision is made via annotations. This value will then be used to compare how long it has been since the last scaling decision to disallow scaling until the `scaleTimeout` is exceeded. If it is the first scaling attempt, the existing stateful-set creation timestamp will be used. If `scaleTimeout` is undefined the scaling logic will not delay; it may be worthwhile to default in this case to 5-10 minutes?
- The actual update to the number of replicas for the nodePool occurs by updating the OpensearchCluster object because just changing the stateful-sets values will cause the scaling action to be immediately reverted the next time the cluster reconciliation loop runs.
- A scaling rule can be made of many individual rules. All rules comprising a scaling rule must evaluate as true for a scaling decision to occur. (For example in the example autoscaler CRD there is a rule comprised of two items. Both must evaluate as true for scaling to occur.) 

### Prometheus considerations
I have listed under assumptions below that opensearch metrics will need to be stored in prometheus to some degree. This is because if we were to only use the global endpoint at _prometheus/metrics on port 9200, we only would get the latest values of a metric. By storing the values in prometheus we can leverage the inbuilt ability to perform aggregations in prometheus for values over time. 

#### Service Discovery
For testing I set up individual service monitors for each nodePool type and set the following values in my prometheus values.yaml.
```
prometheus:
  prometheusSpec:
    ruleSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
```

<details open>
  <summary>ServiceMonitors Example</summary>

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    opster.io/opensearch-nodepool: nodes
  name: my-cluster-nodes
  namespace: monitoring
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: my-cluster-admin-password
      username:
        key: username
        name: my-cluster-admin-password
    bearerTokenSecret:
      key: ""
    interval: 30s
    tlsConfig:
      insecureSkipVerify: true
    scheme: https
    targetPort: 9200
    path: /_prometheus/metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      opster.io/opensearch-nodepool: nodes
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    opster.io/opensearch-nodepool: masters
  name: my-cluster-masters
  namespace: monitoring
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: my-cluster-admin-password
      username:
        key: username
        name: my-cluster-admin-password
    bearerTokenSecret:
      key: ""
    interval: 30s
    tlsConfig:
      insecureSkipVerify: true
    scheme: https
    targetPort: 9200
    path: /_prometheus/metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      opster.io/opensearch-nodepool: masters
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    opster.io/opensearch-nodepool: coordinators
  name: my-cluster-coordinators
  namespace: monitoring
spec:
  endpoints:
  - basicAuth:
      password:
        key: password
        name: my-cluster-admin-password
      username:
        key: username
        name: my-cluster-admin-password
    bearerTokenSecret:
      key: ""
    interval: 30s
    tlsConfig:
      insecureSkipVerify: true
    scheme: https
    targetPort: 9200
    path: /_prometheus/metrics
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      opster.io/opensearch-nodepool: coordinators
```

</details>

#### Querying Prometheus

For ease of use my original idea for the design for the value of the `metric` field(originally labeled `query`) was to take any query that was valid in prometheus and allow it to be used. The benefit of this would be that users would be able to query prometheus outside of operator via the GUI or other and be able to effectively copy and paste functional queries in to the autoscaler. I moved away from this idea however for a few reasons:

- More often than not a label matcher is required to limit the results of a query to the specific OpenSearch node type. While this is something that could be documented for users to do, it seemed messy.
- I wanted to leverage Prometheus' ability to perform comparisons with binary operators, this meant taking whatever query the user provided and appending the operator and threshold to the query before querying prometheus.

It felt cleaner to specifically define query components with `queryOptions` and limit users to a smaller set of queries with the following design:

`function ( metric {matchLabels} [interval] ) booleanOperator threshold`

This of course provides a few limitations:
- A single function wrapper allowed
- A single metric allowed
- Requires more effort from users when defining scaling rules

Overall I believe this approach to be cleaner in terms of defining rules in the autoscaler and manipulating the query under the hood. My primary fear was having users present one query that they have tested via the prometheus gui, and then needing to manipulate it in the operator resulting in an unexpected result. Of course it could simply be documented and left entirely up to the user which would bypass this issue, which would omit the need for all values of type `Item` except for `metric`(which would likely revert to `query`). 
I am curious to hear what others think of requiring users to provide exact queries, versus providing guardrails for what users can and cannot do.

<br>

## Assumptions
- Metrics will need to be stored in prometheus to be able to perform aggregations over time.
- Metrics will need to be gathered via service discovery because of the dynamic nature of nodes.

<br>

## Open Questions
1. As explained above in the Prometheus considerations above, I am interested to hear peoples thoughts on the best way to have users define their queries to Prometheus; either directly via a query of their own design or if the operator should construct it for them.
2. I currently have a field named `prometheusEndpoint` to target a prometheus endpoint as part of the autoscaler config added to the OpenSearchCluster CRD. Do we foresee a need for other connection options for credentialing/certs/etc?
3. Should scaling be handled as a composite of all nodes or on a per node basis?
```
If we have 2 data nodes and want to scale on CPU utilization percentage:
node1 is at 100% 
node2 is at 0%
scaling threshold is 60%
```
If each node is evaluated individually, 100% is greater than 60% so we would scale, however if we evaluate them together as an average we would not scale. I don't think an imbalance between nodes will occur often but doesn't seem so far outside the realm of possibility to not take in to account.
