### ISSUE TITLE
TLS transport generate set to 'true' results in a SIGSEGV in the operator-controller-manager

### ISSUE THREAD

**Issue by iamtanmay** [Opster/opensearch-k8s-operator#540]
cluster.yaml:

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: opensearch-cluster
  namespace: default
spec:
  initHelper:
    image: 'busybox:latest'
  general:
    serviceName: als
    image: 'opensearchproject/opensearch:2.7.0'
    httpPort: 9200
    vendor: opensearch
    monitoring:
      enable: true
  security:
    config:
      securityConfigSecret:
        name: als-security-config
      adminCredentialsSecret:
        name: als-admin-credentials
    tls:
      transport:
        generate: true
        perNode: true
        secret:
          name: null
        caSecret:
          name: null
        nodesDn: []
        adminDn: []
      http:
        generate: true
        secret:
          name: null
        caSecret:
          name: null
  dashboards:
    version: 2.7.0
    image: 'opensearchproject/opensearch-dashboards:2.7.0'
    enable: true
    replicas: 2
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 1Gi
        cpu: 500m
  confMgmt:
    smartScaler: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30Gi
      nodeSelector: null
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 500m
      roles:
        - master
        - data
      persistence:
        pvc:
          storageClass: longhorn
          accessModes:
            - ReadWriteOnce
    - component: nodes
      replicas: 3
      diskSize: 30Gi
      nodeSelector: null
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 500m
      roles:
        - data
      persistence:
        pvc:
          storageClass: longhorn
          accessModes:
            - ReadWriteOnce
    - component: coordinators
      replicas: 3
      diskSize: 30Gi
      nodeSelector: null
      resources:
        requests:
          memory: 2Gi
          cpu: 500m
        limits:
          memory: 2Gi
          cpu: 500m
      roles:
        - ingest
      persistence:
        pvc:
          storageClass: longhorn
          accessModes:
            - ReadWriteOnce
```

operator values.yaml:

```
opensearch-operator:
  manager:
    image:
      repository: opsterio/opensearch-operator
      tag: ""
      pullPolicy: "Always"
    watchNamespace: "osp-als"
  kubeRbacProxy:
    image:
      repository: "kubebuilder/kube-rbac-proxy"
      tag: "v0.12.0"

omc:
  omc:
    deployment:
      image:
        repository: opsterio/opster-management-console
        tag: "latest"
      watchNamespace: "osp-opensearch-operator"
  ui:
    deployment:
      image:
        repository: opsterio/opster-operator-ui
        tag: "latest"
      watchNamespace: "osp-opensearch-operator"
  ingress:
    enable: true
```

Error Trace:

```
I0622 08:27:36.356911       1 request.go:682] Waited for 1.040292314s due to client-side throttling, not priority and fairness, request: GET:https://10.43.0.1:443/apis/apiextensions.k8s.io/v1?timeout=32s
1.6874224566155038e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
1.6874224566160445e+09	INFO	setup	starting manager
1.6874224566171324e+09	INFO	Starting server	{"path": "/metrics", "kind": "metrics", "addr": "127.0.0.1:8080"}
I0622 08:27:36.617288       1 leaderelection.go:248] attempting to acquire leader lease osp-als/a867c7dc.opensearch.opster.io...
1.687422456617157e+09	INFO	Starting server	{"kind": "health probe", "addr": "[::]:8081"}
I0622 08:27:53.090144       1 leaderelection.go:258] successfully acquired lease osp-als/a867c7dc.opensearch.opster.io
1.687422473090203e+09	DEBUG	events	opensearch-operator-controller-manager-6c84f59645-6cl7r_8e9016b6-f414-410d-813f-e4e8b2946787 became leader	{"type": "Normal", "object": {"kind":"Lease","namespace":"osp-als","name":"a867c7dc.opensearch.opster.io","uid":"e77b7d66-a686-4639-b224-6514ca07a83f","apiVersion":"coordination.k8s.io/v1","resourceVersion":"158837636"}, "reason": "LeaderElection"}
1.687422473090356e+09	INFO	Starting EventSource	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "source": "kind source: *v1.OpenSearchCluster"}
1.687422473090402e+09	INFO	Starting EventSource	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "source": "kind source: *v1.Pod"}
1.6874224730903828e+09	INFO	Starting EventSource	{"controller": "opensearchrole", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchRole", "source": "kind source: *v1.OpensearchRole"}
1.6874224730903885e+09	INFO	Starting EventSource	{"controller": "opensearchuser", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUser", "source": "kind source: *v1.OpensearchUser"}
1.6874224730904298e+09	INFO	Starting EventSource	{"controller": "opensearchrole", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchRole", "source": "kind source: *v1.OpenSearchCluster"}
1.6874224730904334e+09	INFO	Starting EventSource	{"controller": "opensearchuser", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUser", "source": "kind source: *v1.OpenSearchCluster"}
1.6874224730904121e+09	INFO	Starting EventSource	{"controller": "opensearchuserrolebinding", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUserRoleBinding", "source": "kind source: *v1.OpensearchUserRoleBinding"}
1.6874224730904438e+09	INFO	Starting EventSource	{"controller": "opensearchuser", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUser", "source": "kind source: *v1.Secret"}
1.6874224730904508e+09	INFO	Starting Controller	{"controller": "opensearchuser", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUser"}
1.6874224730904524e+09	INFO	Starting EventSource	{"controller": "opensearchuserrolebinding", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUserRoleBinding", "source": "kind source: *v1.OpenSearchCluster"}
1.6874224730904596e+09	INFO	Starting Controller	{"controller": "opensearchuserrolebinding", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUserRoleBinding"}
1.6874224730904129e+09	INFO	Starting EventSource	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "source": "kind source: *v1.Secret"}
1.6874224730904384e+09	INFO	Starting Controller	{"controller": "opensearchrole", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchRole"}
1.6874224730904756e+09	INFO	Starting EventSource	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "source": "kind source: *v1.ConfigMap"}
1.687422473090501e+09	INFO	Starting EventSource	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "source": "kind source: *v1.Service"}
1.6874224730905151e+09	INFO	Starting EventSource	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "source": "kind source: *v1.Deployment"}
1.6874224730905206e+09	INFO	Starting EventSource	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "source": "kind source: *v1.StatefulSet"}
1.6874224730905252e+09	INFO	Starting Controller	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster"}
1.6874224731917207e+09	INFO	Starting workers	{"controller": "opensearchuserrolebinding", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUserRoleBinding", "worker count": 1}
1.6874224731918125e+09	INFO	Starting workers	{"controller": "opensearchuser", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchUser", "worker count": 1}
1.6874224731917684e+09	INFO	Starting workers	{"controller": "opensearchrole", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpensearchRole", "worker count": 1}
1.6874224731918333e+09	INFO	Starting workers	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "worker count": 1}
1.6874224731922848e+09	INFO	Reconciling OpenSearchCluster	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"als","namespace":"osp-als"}, "namespace": "osp-als", "name": "als", "reconcileID": "9ad2cc9b-db87-46c8-b2f2-318fc369315d", "cluster": "osp-als/als"}
1.687422473216302e+09	INFO	Generating certificates	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"als","namespace":"osp-als"}, "namespace": "osp-als", "name": "als", "reconcileID": "9ad2cc9b-db87-46c8-b2f2-318fc369315d", "interface": "transport"}
1.6874224732227995e+09	INFO	Generating certificates	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"als","namespace":"osp-als"}, "namespace": "osp-als", "name": "als", "reconcileID": "9ad2cc9b-db87-46c8-b2f2-318fc369315d", "interface": "http"}
1.6874224732228873e+09	INFO	Not passed any SecurityconfigSecret	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"als","namespace":"osp-als"}, "namespace": "osp-als", "name": "als", "reconcileID": "9ad2cc9b-db87-46c8-b2f2-318fc369315d"}
1.6874224733233187e+09	INFO	Starting securityconfig update job	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"als","namespace":"osp-als"}, "namespace": "osp-als", "name": "als", "reconcileID": "9ad2cc9b-db87-46c8-b2f2-318fc369315d"}
1.6874224733235786e+09	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluster": {"name":"als","namespace":"osp-als"}, "namespace": "osp-als", "name": "als", "reconcileID": "9ad2cc9b-db87-46c8-b2f2-318fc369315d"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xdbfbb8]

goroutine 677 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:118 +0x1f4
panic({0x17ec1e0, 0x294e900})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/hashicorp/go-version.prereleaseCheck(0x0?, 0xc000916320?)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/constraint.go:198 +0x18
github.com/hashicorp/go-version.constraintGreaterThanEqual(0x19fd706?, 0x0?)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/constraint.go:250 +0x25
github.com/hashicorp/go-version.(*Constraint).Check(...)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/constraint.go:163
github.com/hashicorp/go-version.Constraints.Check(...)
	/go/pkg/mod/github.com/hashicorp/go-version@v1.6.0/constraint.go:93
opensearch.opster.io/pkg/helpers.VersionCheck(0xc00025bb00)
	/workspace/pkg/helpers/reconcile-helpers.go:109 +0x8f
opensearch.opster.io/pkg/builders.NewSecurityconfigUpdateJob(_, {_, _}, {_, _}, {_, _}, {_, _}, {0xc00069009c, ...}, ...)
	/workspace/pkg/builders/cluster.go:976 +0x3b8
opensearch.opster.io/pkg/reconcilers.(*SecurityconfigReconciler).Reconcile(0xc0002d2770)
	/workspace/pkg/reconcilers/securityconfig.go:129 +0x835
opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).reconcilePhaseRunning(0xc00003fea0, {0x1c89158?, 0xc00090eb10})
	/workspace/controllers/opensearchController.go:320 +0x725
opensearch.opster.io/controllers.(*OpenSearchClusterReconciler).Reconcile(0xc00003fea0, {0x1c89158?, 0xc00090eb10}, {{{0xc000e821d6, 0x7}, {0xc000e821f9, 0x3}}})
	/workspace/controllers/opensearchController.go:141 +0x7a8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1c890b0?, {0x1c89158?, 0xc00090eb10?}, {{{0xc000e821d6?, 0x1915b60?}, {0xc000e821f9?, 0x4045d4?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:121 +0xc8
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000461040, {0x1c890b0, 0xc000d16a40}, {0x1845d20?, 0xc0008820c0?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:320 +0x33c
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000461040, {0x1c890b0, 0xc000d16a40})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:230 +0x333
```
