### ISSUE TITLE
PersistentVolumeClaims not being created by the operator

### ISSUE THREAD

**Issue by juliohm1978** [Opster/opensearch-k8s-operator#542]
Hi all,

I have installed the operator v2.3.1. I'm trying to create an OpenSearchCluster instance, but the operator refuses to create the StatefulSet with the following error message:

```yaml
operator-controller-manager 1.687537302482004e+09    ERROR    Reconciler error    {"controller": "opensearchcluster", "controllerGroup": "opensearch.opster.io", "controllerKind": "OpenSearchCluster", "OpenSearchCluste
r": {"name":"osdemo","namespace":"osdemo"}, "namespace": "osdemo", "name": "osdemo", "reconcileID": "48b984d0-ea53-45ef-942b-c3c6acba5db8", "error": "StatefulSet.apps \"osdemo-nodes\" not found; PersistentVolumeClaim 
\"data-osdemo-nodes-0\" not found", "errorCauses": [{"error": "StatefulSet.apps \"osdemo-nodes\" not found"}, {"error": "PersistentVolumeClaim \"data-osdemo-nodes-0\" not found"}]}
```

Using the following OpenSearchCluster yaml
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: osdemo
  namespace: osdemo
spec:
  general:
    serviceName: osdemo
    version: 2.8.0
  dashboards:
    enable: true
    version: 2.8.0
    replicas: 1
    resources:
      requests:
          memory: "5Mi"
          cpu: "1m"
      limits:
          memory: "1Gi"
          cpu: "4"
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "10Gi"
      nodeSelector:
      resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
          limits:
            memory: "8Gi"
            cpu: "4"
      roles:
        - "cluster_manager"
      persistence:
        pvc:
          storageClass: vsphere
    - component: nodes
      replicas: 2
      diskSize: "50Gi"
      nodeSelector:
      resources:
          requests:
            memory: "1Mi"
            cpu: "1m"
          limits:
            memory: "8Gi"
            cpu: "4"
      roles:
        - "data"
      persistence:
        pvc:
          storageClass: vsphere
```

Any clues as to why PVCs are not being created?
