### ISSUE TITLE
Is there a way to set custom initContainers in the pods?

### ISSUE THREAD

**Issue by matiskay** [Opster/opensearch-k8s-operator#543]
I'm working on setting up the operator inside GKE Autopilot, and I need to set a condition to know if `max_map_count` is set to a maximum value. I'm using a DaemonSet to set the `max_map_count` and the pods have to wait for this value before starting initializing the application containers. I want to use the same strategy [ECK uses to set it up on GKE Autopilot](https://www.elastic.co/guide/en/cloud-on-k8s/master/k8s-virtual-memory.html).

## Init container I want to use:

```
initContainers:
        - name: max-map-count-check
          command: ['sh', '-c', "while true; do mmc=$(cat /proc/sys/vm/max_map_count); if [ ${mmc} -eq 262144 ]; then exit 0; fi; sleep 1; done"]
```

## DemonSet

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: max-map-count-setter
  labels:
    k8s-app: max-map-count-setter
spec:
  selector:
    matchLabels:
      name: max-map-count-setter
  template:
    metadata:
      labels:
        name: max-map-count-setter
    spec:
      initContainers:
        - name: max-map-count-setter
          image: docker.io/bash:5.2.15
          resources:
            limits:
              cpu: 100m
              memory: 32Mi
          securityContext:
            privileged: true
            runAsUser: 0
          command: ['/usr/local/bin/bash', '-e', '-c', 'echo 262144 > /proc/sys/vm/max_map_count']
      containers:
        - name: sleep
          image: docker.io/bash:5.2.15
          command: ['sleep', 'infinity']
```

Note: `setVMMaxMapCount: true` doesn't work on GKE Autopilot because GKE Autopilot doesn't run `init-sysctl` because it requires a privileged container which is denied by GKE Autopilot.. `[denied by autogke-disallow-privilege]":["container init-sysctl is privileged; not allowed in Autopilot]`
