### ISSUE TITLE
Add support for existing claim (pvc) of pre-created PV

### ISSUE THREAD

**Issue by surikbs** [Opster/opensearch-k8s-operator#550]
Hi Team,

We are trying to mount the pre-created pv and pvc's to the node pools. We tried to create these objects similar to the operator created objects   (having the right naming convention, labels, annotations etc) and applied the cluster config yaml with diskSize option setting the size of the pre-created volumes. These volumes were not picked up by the pods and we see the below events of the pods.

``` │ Events:                                                                                                                                                                 │
│   Type     Reason       Age                  From     Message                                                                                                           │
│   ----     ------       ----                 ----     -------                                                                                                           │
│   Warning  FailedMount  50m (x77 over 21h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[http-cert securityconfig config  │
│ dmin-credentials data kube-api-access-qx6cl transport-cert[]: timed out waiting for the condition                                                                       │
│   Warning  FailedMount  45m (x95 over 21h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data kube-api-access-qx6cl trans │
│ ort-cert http-cert securityconfig config admin-credentials[]: timed out waiting for the condition                                                                       │
│   Warning  FailedMount  41m (x87 over 21h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[transport-cert http-cert securit │
│ config config admin-credentials data kube-api-access-qx6cl[]: timed out waiting for the condition                                                                       │
│   Warning  FailedMount  25m (x89 over 21h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[config admin-credentials data ku │
│ e-api-access-qx6cl transport-cert http-cert securityconfig[]: timed out waiting for the condition                                                                       │
│   Warning  FailedMount  16m (x74 over 21h)   kubelet  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[securityconfig config admin-cred │
│ ntials data kube-api-access-qx6cl transport-cert http-cert[]: timed out waiting for the condition                                                                       │
│   Warning  FailedMount  60s (x630 over 22h)  kubelet  MountVolume.SetUp failed for volume "data-dev-osp-als-masters-0" : rpc error: code = Internal desc = Failed to mo │
│ unt /opt/mapr/k8s/mounts/291de469-6ab6-41b0-a4b4-54bbaca65f7f-data-dev-osp-als-masters-0/datalake-dev.dhl.com/osp-als-0 at /var/lib/kubelet/pods/291de469-6ab6-41b0-a4b │
│ 4-54bbaca65f7f/volumes/kubernetes.io~csi/data-dev-osp-als-masters-0/mount : exit status 32                                                                              │
│
```

**Comment by prudhvigodithi** [comment]
Hey @surikbs I have done some tests and it worked with created PV's

1) pre create the PV, in my case I'm using AWS, notice the key `persistentVolumeReclaimPolicy: Retain`, this will ensure the volumes are retained even with PV/PVC deletion and notice the `claimRef`, this is the key part ensure the right values are passed (infer based on your manifest yaml, how it was previously created)

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1a
  name: pvc-16ab328d-f215-43e9-897f-5ef50ea09c6a
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1a/vol-0ad62046c10587373
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-my-first-cluster-masters-0
    namespace: default
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem

---

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1f
  name: pvc-2b734e45-099e-42c6-8c46-9e3356964e15

spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1f/vol-081fb585241dbb62
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-my-first-cluster-masters-1
    namespace: default
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1f
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east-1
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp2
  volumeMode: Filesystem


--- 

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    topology.kubernetes.io/region: us-east-1
    topology.kubernetes.io/zone: us-east-1a
  name: pvc-46258e93-b8e9-4a8e-baa9-1779b9a9ee09
spec:
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: aws://us-east-1a/vol-0bef135b28cb16c8d
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: data-my-first-cluster-masters-2
    namespace: default
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: topology.kubernetes.io/zone
          operator: In
          values:
          - us-east-1a
        - key: topology.kubernetes.io/region
          operator: In
          values:
          - us-east-1
  persistentVolumeReclaimPolicy: Delete
  storageClassName: gp2
  volumeMode: Filesystem
```

2) Once the above PV yaml file is applied, the status would be `Available`.
```
 k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                     STORAGECLASS   REASON   AGE
pvc-16ab328d-f215-43e9-897f-5ef50ea09c6a   10Gi       RWO            Retain           Available   default/data-my-first-cluster-masters-0   gp2                     13s
pvc-2b734e45-099e-42c6-8c46-9e3356964e15   10Gi       RWO            Retain           Available   default/data-my-first-cluster-masters-1   gp2                     13s
pvc-46258e93-b8e9-4a8e-baa9-1779b9a9ee09   10Gi       RWO            Delete           Available   default/data-my-first-cluster-masters-2   gp2                     12s
```

3) Once the cluster operator manifest to create a cluster is applied, it would create PVC's and bound to the pre-created PV. Notice the status `Bound`
```
k get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                                     STORAGECLASS   REASON   AGE
pvc-16ab328d-f215-43e9-897f-5ef50ea09c6a   10Gi       RWO            Retain           Bound       default/data-my-first-cluster-masters-0   gp2                     6m6s
pvc-2b734e45-099e-42c6-8c46-9e3356964e15   10Gi       RWO            Retain           Available   default/data-my-first-cluster-masters-1   gp2                     6m6s
pvc-46258e93-b8e9-4a8e-baa9-1779b9a9ee09   10Gi       RWO            Delete           Available   default/data-my-first-cluster-masters-2   gp2                     6m5s
```
