### ISSUE TITLE
[Bug]: Installing dashboard plugin repository-s3 for opensearch dashboard-> AccessDenied

### ISSUE THREAD

**Issue by raulpuente** [Opster/opensearch-k8s-operator#568]
**Describe the bug**

I'm trying to install plugin repository-s3 with OpensearchCluster yaml for dashboard opensearch.

```yaml
  ...
  dashboards:
    enable: true
    version: 2.8.0
    pluginsList:
      - repository-s3
  ...
```

And never starts correctly the pod opensearch-dashboard

Log output:
```log
v16.20.0
Attempting to transfer from repository-s3
Attempting to transfer from https://ci.opensearch.org/ci/dbc/distribution-build-opensearch-dashboards/2.8.0/latest/linux/x64/tar/builds/opensearch-dashboards/plugins/repository-s3-2.8.0.zip
Plugin installation was unsuccessful due to error "No valid url specified."
```

I can reproduce it accessing to the pod and execute:

```sh
bin/opensearch-dashboards-plugin install repository-s3
```

This is my cluster_configuration
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: test-cluster
spec:
  security:
    tls:
       http:
         generate: true
       transport:
         generate: true
         perNode: true
  general:
    httpPort: 9200
    serviceName: test-cluster
    version: 2.8.0
    pluginsList:
      - repository-s3
    drainDataNodes: true
  dashboards:
    enable: true
    version: 2.8.0
    pluginsList:
      - repository-s3
    replicas: 1

    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 2
      diskSize: "5Gi"
      nodeSelector:
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "2Gi"
            cpu: "500m"
      roles:
        - "data"
        - "cluster_manager"
```

If i delete the pluginList part on dashboard section it works.

Thank you
