### ISSUE TITLE
https is used when the security.tls.http is disabled

### ISSUE THREAD

**Issue by zzzz465** [Opster/opensearch-k8s-operator#573]
https://github.com/Opster/opensearch-k8s-operator/blob/33d9c53682d0060e2a4d3b68f6187272c0539299/opensearch-operator/pkg/reconcilers/util/util.go#L185

we're using http plaintext for opensearch rest api (in-cluster). but the operator creates readiness probe on master node that uses `https` scheme for querying endpoint, causing node not being ready state.

```yaml
      readinessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - curl -k -u "$(cat /mnt/admin-credentials/username):$(cat
              /mnt/admin-credentials/password)" --silent --fail
              https://localhost:9200
```
