### ISSUE TITLE
getting error in integrating keycloak with opensearch

### ISSUE THREAD

**Issue by kannanvr** [Opster/opensearch-k8s-operator#576]
Hi Team,
Am trying to integrate keycloak with opensearch using k8s opster operator. Getting some error. Refer the below yaml files and error details.

opensearch.yaml
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-cluster1
  namespace: opensearch
spec:
  security:
    config:
      adminCredentialsSecret:
        name: a-admin-credentials-secret
      securityConfigSecret:
        name: a-securityconfig-secret
    tls:
      transport:
        generate: true
      http:
        generate: true
  general:
    serviceName: my-cluster1
    version: 2.8.0
    pluginsList: ["repository-s3"]
    drainDataNodes: true
    setVMMaxMapCount: true
  dashboards:
    additionalConfig:
      logging.verbose: "true"
      server.name: my-cluster1-dashboards
      server.host: 0.0.0.0
      server.ssl.enabled: "true"
      server.ssl.key: /usr/share/opensearch-dashboards/config/opensearch.example.org.key
      server.ssl.certificate: /usr/share/opensearch-dashboards/config/opensearch.example.org.cert
      opensearch_security.auth.type: "openid"
      opensearch_security.auth.multiple_auth_enabled: "True"
      opensearch_security.openid.connect_url: https://x.x.x.x/.well-known/openid-configuration
      opensearch_security.openid.base_redirect_url: <dashboard-url>
      opensearch_security.openid.client_id: xxxxxx
      opensearch_security.openid.client_secret: xxxxxxxxxx
      opensearch_security.openid.scope: openid profile email
      opensearch_security.openid.header: Authorization
      opensearch_security.openid.trust_dynamic_headers: "true"
      opensearch.optimizedHealthcheckId: "my-cluster1"
      opensearch.hosts: "https://<opensearch-svc-ip>:9200"
      opensearch.username: "kibanaserver"
      opensearch.password: "kibanaserver"
      opensearch_security.openid.verify_hostnames: "false"
      opensearch_security.cookie.secure: "false"
      opensearch.ssl.verificationMode: none
      opensearch.requestHeadersWhitelist:  |
        ["securitytenant","Authorization","security_tenant"]
    opensearchCredentialsSecret:
      name: a-admin-credentials-secret
    enable: true
    version: 2.8.0
    replicas: 1
    resources:
      requests:
         memory: "512Mi"
         cpu: "200m"
      limits:
         memory: "512Mi"
         cpu: "200m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: "5Gi"
      jvm: "-Dopensearch.allow_insecure_settings=true"
      resources:
         requests:
            memory: "2Gi"
            cpu: "500m"
         limits:
            memory: "3Gi"
            cpu: "1000m"
      roles:
        - "data"
        - "master"
        - "ingest"
#      persistence:
#        pvc:
#          storageClass: mystorageclass
#          accessModes: # You can change the accessMode
#          - ReadWriteOnce

```

admin-credentials-secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: a-admin-credentials-secret
  namespace: opensearch
type: Opaque
data:
  # admin
  username: YWRtaW4=
  # admin123
  password: YWRtaW4xMjMK

```  
  
securityconfig-secret.yaml
```
apiVersion: v1
kind: Secret
metadata:
  name: a-securityconfig-secret
  namespace: opensearch
type: Opaque
stringData:
      internal_users.yml: |-
        _meta:
          type: "internalusers"
          config_version: 2
        admin:
          hash: "$2a$12$vZHSkfDt1zB/rSLZ/GtIsuEpQ2O9aP8QorCXVSQMmptAD/9XpPSnK"
          reserved: true
          backend_roles:
          - "admin"
          description: "Demo admin user"

        anomalyadmin:
          hash: "$2y$12$TRwAAJgnNo67w3rVUz4FIeLx9Dy/llB79zf9I15CKJ9vkM4ZzAd3."
          reserved: false
          opendistro_security_roles:
          - "anomaly_full_access"
          description: "Demo anomaly admin user, using internal role"

        kibanaserver:
          hash: "$2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H."
          reserved: true
          description: "Demo OpenSearch Dashboards user"

        kibanaro:
          hash: "$2a$12$JJSXNfTowz7Uu5ttXfeYpeYE0arACvcwlPBStB1F.MI7f0U9Z4DGC"
          reserved: false
          backend_roles:
          - "kibanauser"
          - "readall"
          attributes:
            attribute1: "value1"
            attribute2: "value2"
            attribute3: "value3"
          description: "Demo OpenSearch Dashboards read only user, using external role mapping"

        logstash:
          hash: "$2a$12$u1ShR4l4uBS3Uv59Pa2y5.1uQuZBrZtmNfqB3iM/.jL0XoV9sghS2"
          reserved: false
          backend_roles:
          - "logstash"
          description: "Demo logstash user, using external role mapping"

        readall:
          hash: "$2a$12$ae4ycwzwvLtZxwZ82RmiEunBbIPiAmGZduBAjKN0TXdwQFtCwARz2"
          reserved: false
          backend_roles:
          - "readall"
          description: "Demo readall user, using external role mapping"

        snapshotrestore:
          hash: "$2y$12$DpwmetHKwgYnorbgdvORCenv4NAK8cPUg8AI6pxLCuWf/ALc0.v7W"
          reserved: false
          backend_roles:
          - "snapshotrestore"
          description: "Demo snapshotrestore user, using external role mapping"
      config.yml: |-
        _meta:
          type: "config"
          config_version: 2
        config:
          dynamic:
            authz: {}
            authc:
              basic_internal_auth_domain:
                http_enabled: true
                transport_enabled: true
                order: 0
                http_authenticator:
                  type: basic
                  challenge: false
                authentication_backend:
                  type: intern

              openid_auth_domain:
                http_enabled: true
                transport_enabled: true
                order: 1
                http_authenticator:
                  type: openid
                  challenge: false
                  config:
                    openid_connect_idp:
                      enable_ssl: true
                      verify_hostnames: false
                      pemtrustedcas_filepath: "https://x.x.x.x/protocol/openid-connect/certs"
                    subject_key: preferred_username
                    roles_key: roles
                    openid_connect_url: "https://x.x.x.x/.well-known/openid-configuration"
                authentication_backend:
                  type: noop

```
Opensearch pods are running fine and health is 100%, but dashboard pod is not running. Dashboard logs shows:-
```
Unable to retrieve version information from OpenSearch nodes.
{
  "level": "unavailable",
  "summary": "[59] services are unavailable",
  "detail": "See the status page for more information",
  "meta": {
    "affectedServices": {
      "opensearch": {
        "level": "unavailable",
        "summary": "Waiting for OpenSearch",
        "meta": {
          "warningNodes": [],
          "incompatibleNodes": []
        }
      }
	  .
	  .
	  .
	}
  }
}

```

**Comment by swoehrl-mw** [comment]
Hi @kannanvr
Dashboard config options like `server.name`, `server.host`, `opensearch.hosts`, `opensearch.username` and `opensearch.password` should not be configured. These are provided by the operator automatically with the correct values. 

Note that unless you specify `spec.dashboards.opensearchCredentialsSecret` the operator will set the credentials to `admin/admin` (in all cases this will overy any `opensearch.username/password` option in the config). In your case this will not work as you have changed them. And I think this is the source of your problem. Please use that option and try again.

**Comment by kannanvr** [comment]
Hi @swoehrl-mw ,

We have removed the mentioned parameters (server.name, server.host, opensearch.hosts, opensearch.username and opensearch.password) from dashboard configuration. But still the same error.

**Comment by swoehrl-mw** [comment]
Hi @kannanvr. I tried your setup but with commented out openid config for dashboards. I found two problems:

* You have a newline in the encoded password (so it is actually "admin123\n") which breaks the connection
* TLS for dashboards must be configured via the operator as otherwise the health checks will not expect TLS and will fail (see https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#dashboards-http how to configure it)

**Comment by kannanvr** [comment]
Hi @swoehrl-mw ,

- Encoded password in the secret is "admin123" only. It is not appended with \n.
- When we enable the dashboard TLS config, dashboard pod itself not coming up.
```
  dashboards:
    enable: true  # Deploy Dashboards component
    tls:
      enable: true  # Configure TLS
      generate: true  # Have the Operator generate and sign a certificate
```

Operator Logs:
![image](https://github.com/Opster/opensearch-k8s-operator/assets/16012974/e3f64f7e-3284-4d5b-b332-e8e2db2a587f)

**Comment by swoehrl-mw** [comment]
Hi @kannanvr.

> * Encoded password in the secret is "admin123" only. It is not appended with \n.

Did you change it in your secret for further tests? Because the password value in the a-admin-credentials-secret secret as you have provided it has the newline:
```
$ python -c 'import base64; print(base64.b64decode("YWRtaW4xMjMK"))'
b'admin123\n'
```

> When we enable the dashboard TLS config, dashboard pod itself not coming up.

You actually ran into a bug here. As a workaround please remove all `security.ssl` configuration from the dashboards configuration in the spec. These are automatically provided by the operator. Is dashboards then coming up?

**Comment by rmssath** [comment]
Hi @swoehrl-mw ,

We are able to access the keycloak login page. 

After login the keycloak, getting **"error: 401 Unauthorized"** when its trying to redirect to dashboard page.

**Comment by swoehrl-mw** [comment]
@rmssath This sounds like a problem in the interaction between opensearch and keycloak. Can you check if there are any problems reported in the logs? You might need to increase the log level (https://opensearch.org/docs/latest/monitoring-your-cluster/logs/) to see them.

**Comment by rmssath** [comment]
Hi @swoehrl-mw ,

After enabling the log level, getting below warning message in opnesearch logs

```
[2023-08-29T17:14:22,304][WARN ][o.o.s.h.HTTPBasicAuthenticator] [my-cluster1-masters-1] No 'Basic Authorization' header, send 401 and 'WWW-Authenticate Basic'
[2023-08-29T17:14:22,304][WARN ][o.o.s.a.BackendRegistry  ] [my-cluster1-masters-1] Authentication finally failed for null from 10.233.66.7:51476
```

Current auth.type setting is  **_opensearch_security.auth.type: "openid"_**

When we try to enable multiple auth type. Getting below error while applying the yaml.
_**opensearch_security.auth.type: ["basicauth","openid"]
opensearch_security.auth.multiple_auth_enabled: "True"**_

`error: error validating "opensearch-new.yaml": error validating data: ValidationError(OpenSearchCluster.spec.dashboards.additionalConfig.opensearch_security.auth.type): invalid type for io.opster.opensearch.v1.OpenSearchCluster.spec.dashboards.additionalConfig: got "array", expected "string"; if you choose to ignore these errors, turn validation off with --validate=false`

**Comment by rmssath** [comment]
Hi @swoehrl-mw ,

Am able to access the opensearch dashboard through keycloak. 

But dashboard discover page is showing empty. I think some roles or privileges are missing for the keycloak user. 

When we checked the privileges of the keycloak user, **own_index** role is mapped to it. 

Kindly suggest the way to map roles for the keycloak user.

**Comment by swoehrl-mw** [comment]
@rmssath. I'm not an expert in this area but I think you will need to create role mappings (as part of the securityconfig) that use the keycloak role name as `backendrole`.

```
# in securityconfig secret:
  roles_mapping.yml: |-
    _meta:
      type: "rolesmapping"
      config_version: 2

    all_access: # Name of the opensearch role
      reserved: false
      backend_roles:
      - "some_keycloak_role" # Name of the keycloak role
```

Again none of this is operator-specific, so I recommend you search the [official opensearch forum](https://forum.opensearch.org/) which also has threads on keycloak integration.
