### ISSUE TITLE
OpenSearchCluster in version "v1" cannot be handled as a OpenSearchCluster: strict decoding error: unknown field "spec.drainDataNodes"

### ISSUE THREAD

**Issue by ricardorqr** [Opster/opensearch-k8s-operator#591]
Hello team,

When I run the YAML file below. I need to use YAML file because this deployment is part of an automation using Ansible.

```yaml
apiVersion: "opensearch.opster.io/v1"
kind: "OpenSearchCluster"
metadata:
  name: "opensearch"
  namespace: "opensearch"
spec:
  initHelper:
    image: "public.ecr.aws/opsterio/busybox"
  general:
    vendor: "opensearch"
    defaultRepo: "opensearchproject"
    serviceName: "opensearch"
    setVMMaxMapCount: true
    version: "2.9.0"
    httpPort: 9200
  nodePools:
    - component: "master"
      replicas: "3"
      persistence:
        pvc:
          storageClass: "gp2"
      diskSize: "30Gi"
      resources:
        limits:
          cpu: "500m"
          memory: "1024Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
      roles:
        - "CLUSTER_MANAGER"
    - component: "data"
      replicas: 1
      persistence:
        pvc:
          storageClass: "gp2"
      diskSize: "30Gi"
      resources:
        limits:
          cpu: "500m"
          memory: "1024Mi"
        requests:
          cpu: "500m"
          memory: "1024Mi"
      roles:
        - "DATA"
  confMgmt:
    smartScaler: true
  drainDataNodes: true
  security:
    tls:
      transport:
        generate: true
        perNode: false
      http:
        generate: true
  dashboards:
    enable: true
    version: "2.9.0"
    replicas: "1"
    resources:
      limits:
        cpu: "500m"
        memory: "1024Mi"
      requests:
        cpu: "500m"
        memory: "1024Mi"
    tls:
      enable: false
      generate: false
```

I have this error:
```
Error from server (BadRequest): error when creating "opensearch.yaml": OpenSearchCluster in version "v1" cannot be handled as a OpenSearchCluster: strict decoding error: unknown field "spec.drainDataNodes"
```
.
I created this file from the operator. Please, take a look at the screenshots.
![Screenshot 2023-08-25 at 7 39 34 PM](https://github.com/Opster/opensearch-k8s-operator/assets/12563452/1599c90e-1284-4ccd-bb58-85ddfa736f89)
![Screenshot 2023-08-25 at 7 40 28 PM](https://github.com/Opster/opensearch-k8s-operator/assets/12563452/3a07e52c-d600-4464-852f-a2e3b7a514b5)
![Screenshot 2023-08-25 at 7 40 43 PM](https://github.com/Opster/opensearch-k8s-operator/assets/12563452/c0eb3b22-5af9-4aab-8139-f368c9240cfa)
![Screenshot 2023-08-25 at 7 40 58 PM](https://github.com/Opster/opensearch-k8s-operator/assets/12563452/105161eb-98bc-49e3-900e-66fdc4ecbe0d)
![Screenshot 2023-08-25 at 7 41 25 PM](https://github.com/Opster/opensearch-k8s-operator/assets/12563452/718e50cd-f323-4e9c-9144-31898b8293c5)
