### ISSUE TITLE
[Proposal] Create a Opensearch proxy CRD

### ISSUE THREAD

**Issue by AndersBennedsgaard** [Opster/opensearch-k8s-operator#596]
We have a use-case where one team manage an OpenSearch cluster instance, and other teams are able to configure new roles, rolebindings, tenants, etc. but we would prefer if these teams does not have access to the cluster instance, in order to reduce possible configuration disasters.
Therefore, we would like to be able to reference OpenSearch instances in other namespaces, using the CRDs that comes with this operator, however, I believe that opens up for several security-concerns if we just allow directly referencing clusters across namespaces (I was able to find this comment https://github.com/Opster/opensearch-k8s-operator/pull/220#discussion_r928507613 where @swoehrl-mw argues for the same non-cross-referencing)

Instead, we propose a new OpensearchConnection / OpensearchProxy CRD.

This would simply create a connection to a pre-existing OpenSearch cluster using an URL for the connection, together with necessary (pre-configured) authentication methods (basic auth, TLS auth, etc.)
The operator would make use of this URL + auth to connect with the cluster, and do its magic.
Additionally, it would be possible to create multiple instances of the operator, which has different permissions towards the cluster. One for managing the cluster with admin rights, and all the others for managing very specific things inside of the OpenSearch cluster.
This also enables the operator to manage OpenSearch clusters that are hosted in other locations than in the Kubernetes cluster.

An instance of the CRD could look like:

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpensearchConnection
metadata:
  name: opensearch-connect
  namespace: opensearch-configuration
spec:
  url: https://opensearch.opensearch.svc:9200
  auth:
    username: admin
    secretRef: opensearch-admin
    secretKey: password
  tls:
    secretRef: opensearch-certificates
```

Configuring a new role could be done using:

```yaml
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: test
  namespace: opensearch-configuration
spec:
  opensearchCluster:
    name: opensearch-connect
    kind: OpensearchConnection
  clusterPermissions: []
  ...
```

What do you guys think of this proposal?
