### ISSUE TITLE
ServiceMonitor tracks every node twice

### ISSUE THREAD

**Issue by Alwinius** [Opster/opensearch-k8s-operator#602]
Hi,
I'm setting up the Prometheus integration of OpenSearch with this operator and I can observe that every node is scraped twice. My guess is that the ServiceMonitor object only references the label opster.io/opensearch-cluster, but this matches two services, both the service with the cluster name and the service name of the specific node pool. In the name of resource efficiency, is it possible to select only one of the services?

Please let me know if you need more information about my setup, it's a very basic opensearch cluster with the ServiceMonitor enabled like this:

`    monitoring:
      enable: true
      tlsConfig:
        insecureSkipVerify: true
`

**Comment by banza** [comment]
+1 from me, the same problem and there is no way to override match labels.

**Comment by swoehrl-mw** [comment]
Hi @Alwinius. I was able to confirm your report and your guess, the selector is too wide and catches both the global service and the per-nodepool services.

The fix will be to change the ServiceMonitor to have a selector like
```yaml
  selector:
    matchExpressions:
    - key: opster.io/opensearch-nodepool
      operator: Exists
    - key: opster.io/opensearch-cluster
      operator: In
      values:
        - my-first-cluster
```
