### ISSUE TITLE
Readinessprobe should be able to be specified

### ISSUE THREAD

**Issue by Nickmman** [Opster/opensearch-k8s-operator#603]
The readinessProbe is [hard-coded into the chart](https://github.com/madhukarmmallia-plivo/opensearch-k8s-operator/blob/b8eac97a037f52c050decbffba178c9bd14d8292/opensearch-operator/pkg/builders/cluster.go#L199-L213), it would be great if we can define a readinessProbe of our own.

In my case, I'm relying on Certificate-based authentication and only have Internal User authentication due to the readinessProbe.

I'm all for leaving it as the way it is in case it is not specified.

**Comment by swoehrl-mw** [comment]
Hi @Nickmman. There have been discussions on and off about switching any interaction the operator does with opensearch (probes + API interaction) to certificates (the operator already requires an admin cert for the securityconfig) and not relying on username/password. Would that also work for you or would you still want to customize the readiness probe?

**Comment by Nickmman** [comment]
Hi @swoehrl-mw, I think that would work, I'm looking forward to disabling the internal user database and relying entirely on CertAuth+SAML. With that switch, that would mean that the probe would also authenticate via certificates, correct?

**Comment by swoehrl-mw** [comment]
> With that switch, that would mean that the probe would also authenticate via certificates, correct?

Correct. Internal users could theoretically be disabled completely.

Just to caution your expectations: No idea when that rework will happen. There have been discussions but no concrete plans.

**Comment by gautamgadipudi-hpe** [comment]
I am having a similar problem of incorrect / hardcoded readiness probe.

Requirement: We needed an opensearch (provisioned through the operator) **without credentials**.

And, as per the documentation I have added the field `plugins.security.disabled: "true"`. See entire opensearchCluster configuration below:

```
opensearchCluster:
  enabled: true
  general:
    httpPort: "9200"
    version: 1.3.9
    serviceName: "my-cluster"
    additionalConfig:
      plugins.security.disabled: "true"
  dashboards:
    enable: true
    replicas: 1
    version: 1.3.9
    resources:
      requests:
        memory: "1Gi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "500m"
  nodePools:
    - component: masters
      diskSize: "30Gi"
      replicas: 3
      roles:
        - "master"
        - "data"
      resources:
        requests:
          memory: "2Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "500m"
```

The first (1/3) master pod is running, but never goes into ready state as the readiness probe of opensearch pod is [hard-coded into the chart](https://github.com/madhukarmmallia-plivo/opensearch-k8s-operator/blob/b8eac97a037f52c050decbffba178c9bd14d8292/opensearch-operator/pkg/builders/cluster.go#L199-L213). So, the remaining pods don't come up.

I am looking to modify the readiness probe to ignore credentials and use `http`, or another way to disable credentials.
