### ISSUE TITLE
Parallel recovery regression in 2.4.0

### ISSUE THREAD

**Issue by JakobPetersson** [Opster/opensearch-k8s-operator#607]
Version: 2.4.0
Function: [Parallel Cluster Recovery](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#cluster-recovery)

### Description

Parallel cluster recovery is not activating for my cluster in 2.4.0. (Works in 2.3.1 and 2.3.2)

### Scenario:
* Create cluster with operator
* Delete statefulset for cluster and pods (--cascade=foreground)
* Let operator recreate it and wait for cluster to recover

I have tested this scenario in both 2.3.1 and 2.3.2 without issue.

### Expected behaviour after triggering scenario

* All nodes should be started at the same time. (statefulset has `podManagementPolicy: Parallel`)
* Cluster recovers.

### Actual behaviour after triggering scenario

* Only a single node is started. (statefulset has `podManagementPolicy: OrderedReady `)
* Cluster never starts other nodes and never recovers.

### Thoughts

Logic related to the parallel recovery has been changed between 2.3.2 and 2.4.0 in for example #477 and #545.

**Comment by swoehrl-mw** [comment]
Hi @JakobPetersson. I was unable to reproduce your report. 
I created a cluster, waited for it to be deployed fully, then deleted the sts and pods. I tried it several times and each time the operator recreated the pods in parallel.

Can you please try again and provide the cluster definition you are using? Have you configured PVCs for persistence?

**Comment by JakobPetersson** [comment]
Hello, thank you for looking at the issue!
I can recreate the scenario reliably in my own environment so there could be something different between our clusters.
I can also recreate my cluster with 2.3.2 and reliably verify that it works with that version for me.

Yes, my PVC is persistent in this setup.

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: {{ .Release.Name }}-search-cluster
spec:
  general:
    serviceName: {{ .Release.Name }}-search-cluster
    version: 2.8.0
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
    securityContext:
      allowPrivilegeEscalation: false
      runAsNonRoot: true
      privileged: false
      capabilities:
        drop:
          - ALL
    serviceAccount: {{ .Release.Name }}-search-cluster
  security:
    tls:
      transport:
        generate: false
        perNode: false
        secret:
          name: "{{ .Release.Name }}-search-cluster-node-cert"
        nodesDn:
          - "CN=node,OU={{ .Release.Name }}-search-cluster,O=TEST"
        adminDn:
          - "CN=admin,OU={{ .Release.Name }}-search-cluster,O=TEST"
      http:
        generate: false
        secret:
          name: "{{ .Release.Name }}-search-cluster-tls-cert"
    config:
      adminSecret:
        name: "{{ .Release.Name }}-search-cluster-admin-cert"
      securityConfigSecret:
        name: {{ .Release.Name }}-search-cluster-security-config
      adminCredentialsSecret:
        name: {{ .Release.Name }}-search-cluster-admin-credentials
  nodePools:
    - component: nodes
      replicas: 3
      resources:
        requests:
          memory: "4Gi"
          cpu: "500m"
        limits:
          memory: "4Gi"
      # Official recommendation: half of memory request
      # https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#set-java-heap-size
      jvm: -Xmx2048M -Xms2048M
      roles:
        - "cluster_manager"
        - "data"
      # Get rid of the following log output:
      # "Enabling execution of install_demo_configuration.sh for OpenSearch Security Plugin"
      # ...
      # "OpenSearch Security Demo Installer"
      # "** Warning: Do not use on production or public reachable systems **"
      env:
        - name: DISABLE_INSTALL_DEMO_CONFIG
          value: "true"
      diskSize: "50Gi"
      persistence:
        pvc:
          storageClass: nfs-client
          accessModes:
            - ReadWriteOnce
```
