### ISSUE TITLE
Cannot set resource limits on bootstrap pod

### ISSUE THREAD

**Issue by jbnjohnathan** [Opster/opensearch-k8s-operator#610]
When deploying a CR manifest for `OpenSearchCluster` I get this error message:

```
{"level":"error","ts":"2023-09-18T06:23:57.138Z","msg":"Reconciler error","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"opensearch","namespace":"mynamespace"},"namespace":"mynamespace","name":"opensearch","reconcileID":"4f698915-5982-4c46-9693-113f6e188e48","error":"failed to create resource: creating resource failed: pods \"opensearch-bootstrap-0\" is forbidden: failed quota: mynamespace-quota: must specify limits.cpu for: opensearch; limits.memory for: opensearch","errorVerbose":"pods \"opensearch-bootstrap-0\" is forbidden: failed quota: mynamespace-quota: must specify limits.cpu for: opensearch; limits.memory for: opensearch\ncreating resource failed
```

I have set limits on everything I can, which is for dashboards and nodePools.

I am trying to deploy OpenSearch in a OpenShift cluster with resource quotas on the namespace. Due to this all containers deployed need to have a limit set.

I tried settings this in `spec`
```
    bootstrap:
      additionalConfig:
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "500m"
```
But got an error from helm when trying to apply the manifest
` * OpenSearchCluster.opensearch.opster.io "opensearch" is invalid: spec.bootstrap.additionalConfig.resources: Invalid value: "object": spec.bootstrap.additionalConfig.resources in body must be of type string: "object"`
