### ISSUE TITLE
Work towards being able to run with securityContext restrictions

### ISSUE THREAD

**Issue by jbnjohnathan** [Opster/opensearch-k8s-operator#611]
I have been working to get Opensearch to run on our OpenShift cluster that have a security policy that enforces certain things. This means that all containers needs to set a securityContext.
* Containers run with random UID
* Namespaces have resource quotas. This means that all containers needs to have a resource limit set
```
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
```

I have gotten as far as only allowing a single init container to run with read-write, while the rest of the opensearch containers run with read-only.

It would be great if the operator would enable the necessary changes to allow this when deploying opensearch using the operator as well.

These are the issues and solutions I have found so far
# Helm
## The docker image needs to be built with permissions that allow any user to read and execute the files inside the container
  - I created a pull request for this, but no reply so far: https://github.com/opensearch-project/docker-images/pull/36
 - This isn't really in the scope of the operator as anyone could build their own image and use with it

## Exception in thread "main" java.nio.file.FileSystemException: /tmp/opensearch-13365302973015516133: Read-only file system
- Added a mount for /tmp to a emptyDir
## Error opening log file 'logs/gc.log': Read-only file system
- Added a mount for /usr/share/opensearch/logs to a emptyDir
## Exception in thread "main" org.opensearch.bootstrap.BootstrapException: java.nio.file.FileSystemException: /usr/share/opensearch/config/opensearch.keystore.tmp: Read-only file system
- Used the keystore container that reads a secret and generates the `opensearch.keystore` file and mounts it as a configmap into the opensearch container. This means that only the keystore container needs to be read-write.

# Operator
## The initHelper container cannot have a securityContext set
- Disabled the initHelper
## Issues with setting securityContext on the bootstrap container.
- Turns out that settings `setVMMaxMapCount` to `true` enabled a container that always runs as privileged.
- Setting `setVMMaxMapCount` to `false` solved this
