### ISSUE TITLE
Unable to create 1.3 version cluster with custom security configuration

### ISSUE THREAD

**Issue by evheniyt** [Opster/opensearch-k8s-operator#623]
According to the [compatibility table](https://github.com/Opster/opensearch-k8s-operator#compatibility), the latest version of the operator should work with 1.3 version of OpenSearch.
However, I found multiple issues when was trying to use some custom options described in the doc.
First, if this security config is set
```yaml
    security:
      tls:
        http:
          caSecret: {}
          generate: true
          secret: {}
        transport:
          caSecret: {}
          generate: true
          secret: {}
```
Then operator fails to start the first node and in logs there are repeating errors:
```
opensearch [2023-09-21T10:47:11,157][ERROR][o.o.s.a.BackendRegistry  ] [opensearch-bootstrap-0] Not yet initialized (you may need to run securityadmin)                                                             
opensearch [2023-09-21T10:47:16,633][ERROR][o.o.s.c.ConfigurationLoaderSecurity7] [opensearch-bootstrap-0] Failure no such index [.opendistro_security] retrieving configuration for [INTERNALUSERS, ACTIONGROUPS, CONFIG, ROLES, ROLESMAPPING, TENANTS, NODESDN, WHITELIST, AUDIT] (index=.opendistro_security)     
```
Second, if custom admin password is set
```yaml
  security:
    config:
      adminCredentialsSecret:
        name: admin-credentials-secret
      adminSecret: {}
      securityConfigSecret:
        name: securityconfig-secret
```
Then I could see that opensearch is still using default `admin:admin` creds and node couldn't startup.

The last one is more critical, so attaching config that includes this options
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: primary
  namespace: default
spec:
  bootstrap:
    resources: {}
  confMgmt: {}
  dashboards:
    enable: true
    opensearchCredentialsSecret:
      name: admin-credentials-secret
    replicas: 1
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 500m
        memory: 1Gi
    service:
      type: ClusterIP
    version: 1.3.9
  general:
    drainDataNodes: true
    httpPort: 9200
    monitoring: {}
    pluginsList:
    - repository-s3
    serviceName: primary
    setVMMaxMapCount: true
    vendor: opensearch
    version: 1.3.9
  initHelper:
    resources: {}
  nodePools:
  - component: nodes
    diskSize: 30Gi
    pdb:
      enable: true
      minAvailable: 4
    replicas: 3
    resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 3Gi
    roles:
    - cluster_manager
    - data
  security:
    config:
      adminCredentialsSecret:
        name: admin-credentials-secret
      adminSecret: {}
      securityConfigSecret:
        name: securityconfig-secret
    tls: {}
```
Want to mention that this configuration works fine for Opensearch 2.3 version.

Opensearch version: 1.3.9
Operator version 2.4.0
Kubernetes version 1.24
