### ISSUE TITLE
Ghost/quantum/missing snapshot in s3

### ISSUE THREAD

**Issue by jonathon2nd** [Opster/opensearch-k8s-operator#657]
I am having a funny problem, and was wondering what anyone here would have to say about it. 

I have added [s3 keys to keystore](https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md#add-secrets-to-keystore).
```
general:
    keystore:
    - secret:
        name: wasabi-s3-secret
      keyMappings:
        # Renames key accessKey in secret to s3.client.default.access_key in keystore
        accessKey: s3.client.default.access_key
       # Renames key secretKey in secret to s3.client.default.secret_key in keystore
        secretKey: s3.client.default.secret_key
...
```

And have added repo in dashboard
```
{
  "type": "s3",
  "settings": {
    "bucket": "test-web-opensearch",
    "base_path": "/",
    "endpoint": "s3.ca-central-1.wasabisys.com",
    "region": "ca-central-1",
    "client": "default"
  }
}
```

I have been able to take snapshot
![image](https://github.com/Opster/opensearch-k8s-operator/assets/52681917/e5984944-3506-443f-b2bc-bf74d12b9ce8)
![image](https://github.com/Opster/opensearch-k8s-operator/assets/52681917/f917bc5b-8eee-42a7-b017-68195faf2525)
And have even been able to restore the snapshot, after restarting all the pods.

But nothing shows up in the bucket
![image](https://github.com/Opster/opensearch-k8s-operator/assets/52681917/b00404bb-7b52-4ea6-990a-6addc6096310)
![image](https://github.com/Opster/opensearch-k8s-operator/assets/52681917/95542c7b-a6ab-4592-a1e3-04a0e03adc32)

**Comment by jonathon2nd** [comment]
I see it now when I move the endpoint to here.
```
general:
    serviceName: labs-cluster
    version: 2.10.0
    setVMMaxMapCount: true
    pluginsList: ["repository-s3","https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.10.0.0/prometheus-exporter-2.10.0.0.zip"]
    keystore:
    - secret:
        name: wasabi-s3-secret
      keyMappings:
        # Renames key accessKey in secret to s3.client.default.access_key in keystore
        accessKey: s3.client.default.access_key
       # Renames key secretKey in secret to s3.client.default.secret_key in keystore
        secretKey: s3.client.default.secret_key
    additionalConfig:
      s3.client.default.endpoint: s3.ca-central-1.wasabisys.com
      s3.client.default.region: ca-central-1
```
