### ISSUE TITLE
Kubernetes Zones & Node Labels : Shard allocation awareness or forced awareness

### ISSUE THREAD

**Issue by sergeiwaigant** [Opster/opensearch-k8s-operator#664]
Hi guys.

I am looking for an elegant way to populate node labels, which are hosting the zone information for a particular node, into the statefulset, which is running the OpenSearch Node Pools.

We have to ensure that OpenSearch is distributed over the two given data centers and that the nodes are not running on the same kubernetes worker. Configuring the spread is fairly simple with topology spread constraints such as ...

```yaml
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: company.domain/zone
    whenUnsatisfiable: "ScheduleAnyway"
    labelSelector:
      matchLabels:
        opster.io/opensearch-nodepool: coordinator
  - maxSkew: 1
    topologyKey: kubernetes.io/hostname
    whenUnsatisfiable: "ScheduleAnyway"
    labelSelector:
      matchLabels:
        opster.io/opensearch-nodepool: coordinator
```

From what I see, there is no built-in feature of the operator to do that, right?

Since we added `cluster.routing.allocation.awareness.attributes: "zone"` and `cluster.routing.allocation.awareness.force.zone.values: "dc1,dc2"` I need the following label as environment variable
* `company.domain/zone` => `node.attr.zone`

```yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    <snip>
  creationTimestamp: "2023-10-16T13:25:04Z"
  labels:
    <snip>
    company.domain/zone: dc2
    topology.csi.vmware.com/k8s-zone: dc2
  name: k8w-node-110
spec:
  podCIDR: 10.42.4.0/24
  podCIDRs:
  - 10.42.4.0/24
```

I have seen that there is no support from Kubernetes via the Downward API to populate node labels into the pod, only the pod labels - thats a blocker we cannot fix right here.
Another solution which I've found is coming from Strimzi Operator for Kafka which is handling this situation via an init container which is talking to the K8S API, fetching this information and storing it down to a config file into a shared volume that is accessible from the Kafka Broker afterwards.
This `kafka_init_run.sh` is simply running some Java class to perform this activity. https://github.com/strimzi/strimzi-kafka-operator/blob/main/kafka-init/scripts/kafka_init_run.sh

```yaml
  initContainers:
  - args:
    - /opt/strimzi/bin/kafka_init_run.sh
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: spec.nodeName
    - name: RACK_TOPOLOGY_KEY
      value: company.domain/zone
    image: quay.io/strimzi/operator:0.38.0
    imagePullPolicy: IfNotPresent
    name: kafka-init
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/kafka/init
      name: rack-volume
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-fz2mm
      readOnly: true
  nodeName: k8w-all-110
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 0
  serviceAccount: kafka-kafka
  serviceAccountName: kafka-kafka
  subdomain: kafka-kafka-brokers
```

If we do not provide this zone information to the running OpenSeard node, the distribution of data and high availability will not work properly.

Right now, we handled it by defining separated node pools per zone, but this has the downside, that the Operator is just updating the statefulsets and Kubernetes is not aware about the link between the statefulsets and in which order to perform the update.

Now the question... any idea how to handle this scenario?
Maybe someone has an idea how to inject some kind of init container to do that.

Regards
Sergei

**Comment by swoehrl-mw** [comment]
Hi @sergeiwaigant.
First of all, the operator has support for `topologySpreadConstraints`. It will not automatically generate them, but you can define them in the CR per nodepool.
An init container is probably your best bet in getting the node information. But the operator currently does not have support for custom init containers. There is a feature request for that (#543) that also has a suggestion for a potential workaround (although I doubt that would work in this case). Another problem is how to get the information into opensearch as the opensearch config is controlled by the operator.

Long term I can see node information as something the operator should provide (just not sure how right now). I'll mark this issue as a feature request.

> Right now, we handled it by defining separated node pools per zone, but this has the downside, that the Operator is just updating the statefulsets and Kubernetes is not aware about the link between the statefulsets and in which order to perform the update.

Not sure if that helps but there is an open feature request (#650) to form update groups over multiple nodepools so just one pod per group is restarted at the same time.

**Comment by piellick** [comment]
Hi @sergeiwaigant we are in a similar case, have you continued on a solution based on an initcontainer? Another possible scenario... once the cluster is started via the operator, go through the Opensearch API for shards distribution.

**Comment by sergeiwaigant** [comment]
> Hi @sergeiwaigant we are in a similar case, have you continued on a solution based on an initcontainer? Another possible scenario... once the cluster is started via the operator, go through the Opensearch API for shards distribution.

Nope, couldn't spend time on it and the customer for which I was working on this, doesn't have Budget at the moment to takle this issue.

**Comment by piellick** [comment]
@sergeiwaigant we fix this issue by using kyverno mutate pod biding: https://kyverno.io/policies/other/mutate-pod-binding/mutate-pod-binding/

On kyverno `resourceFilters`, remove:
`Binding and Pod/Bindind` 


And apply this rule:
```
apiVersion: kyverno.io/v2beta1
kind: ClusterPolicy
metadata:
  name: mutate-pod-binding
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Mutate Pod Binding
    policies.kyverno.io/category: Other
    policies.kyverno.io/subject: Pod
    kyverno.io/kyverno-version: 1.10.0
    policies.kyverno.io/minversion: 1.10.0
    kyverno.io/kubernetes-version: "1.26"
spec:
  background: false
  rules:
    - name: project-foo
      match:
        any:
        - resources:
            kinds:
            - Pod/binding
      context:
      - name: node
        variable:
          jmesPath: request.object.target.name
          default: ''
      - name: zone
        apiCall:
          urlPath: "/api/v1/nodes/{{node}}"
          jmesPath: "metadata.labels.\"topology.kubernetes.io/zone\" || 'empty'"
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              topology.kubernetes.io/zone: "{{ zone }}"
          spec:
            containers:
            - env:
              - valueFrom:
                  fieldRef:
                    fieldPath: metadata.annotations['topology.kubernetes.io/zone']
```
