### ISSUE TITLE
Operator not creating pods with default installation.

### ISSUE THREAD

**Issue by prudhvigodithi** [Opster/opensearch-k8s-operator#67]
Hey i'm following this guide to install the operator but I dont see operator creating pods.
```
make build manifests
(connecting to the cluster)
make install
```
But I dont see any pods bought up by the controller 
```
kubectl get pods
No resources found in default namespace.
```

Used the following cluster.yaml file
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
  dashboards:
    enable: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30
      NodeSelector:
      cpu: 1
      memory: 1
      roles:
        - "master"
        - "data"
```

The following is the output describing the cluster

```
Name:         my-cluster
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  opensearch.opster.io/v1
Kind:         OpenSearchCluster
Metadata:
  Creation Timestamp:  2022-03-17T20:50:17Z
  Generation:          1
  Managed Fields:
    API Version:  opensearch.opster.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:confMgmt:
          .:
          f:smartScaler:
        f:dashboards:
          .:
          f:enable:
        f:general:
          .:
          f:httpPort:
          f:serviceName:
          f:vendor:
          f:version:
        f:nodePools:
        f:security:
          .:
          f:tls:
            .:
            f:http:
              .:
              f:generate:
            f:transport:
              .:
              f:generate:
    Manager:         kubectl-client-side-apply
    Operation:       Update
    Time:            2022-03-17T20:50:17Z
  Resource Version:  264753
  UID:               8f6f66ce-04f8-413d-9c50-6b1cb1985c50
Spec:
  Conf Mgmt:
    Smart Scaler:  true
  Dashboards:
    Enable:  true
  General:
    Http Port:     9200
    Service Name:  my-cluster
    Vendor:        opensearch
    Version:       latest
  Node Pools:
    Component:  masters
    Cpu:        1
    Disk Size:  30
    Memory:     1
    Replicas:   3
    Roles:
      master
      data
    Component:  nodes
    Cpu:        1
    Disk Size:  100
    Memory:     1
    Replicas:   3
    Roles:
      data
    Component:  coordinators
    Cpu:        1
    Disk Size:  100
    Replicas:   3
    Roles:
      ingest
  Security:
    Tls:
      Http:
        Generate:  true
      Transport:
        Generate:  true
Events:            <none>

```
