### ISSUE TITLE
Cluster resources reconciler - CPU and Memory

### ISSUE THREAD

**Issue by prudhvigodithi** [Opster/opensearch-k8s-operator#68]
Make opensearch-k8s-operator able to adjust the OpenSearch statefulset resources (cpu/memory resources requests and limits)
The user should be able to pass cpu and memory resources to the cluster from cluster.yaml 
https://github.com/Opster/opensearch-k8s-operator/blob/main/docs/userguide/main.md
Example as 
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
  dashboards:
    enable: true
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30
      NodeSelector:
      cpu: "0.3"
      memory: "2Gi"
      roles:
        - "data"
        - "master"
```
The values should be passed as follows, user should be able to adjust cpu with. "m" and memory with "Mi" or "Gi".

```
      cpu: "0.3"
      memory: "2Gi"
```

**Comment by prudhvigodithi** [comment]
More improvement is better if a user can pass as 
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
  dashboards:
    enable: true
    resources:
       requests:
          memory: "64Mi"
          cpu: "250m"
       limits:
         memory: "128Mi"
         cpu: "500m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30
      NodeSelector:
      resources:
         requests:
            memory: "64Mi"
            cpu: "250m"
         limits:
            memory: "128Mi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
```

**Comment by dbason** [comment]
So a couple of thoughts here.  Functionally for memory the limit and request should be the same.  Setting them differently doesn't make sense for an opensearch node.  Also we should set the JVM heapsize to be half of whatever the memory limit/request is.  I think it's OK to let the user override this (they shouldn't) but set it by default.

**Comment by prudhvigodithi** [comment]
Hey @dbason yes JVM is currently set as jvm = "-Xmx512M -Xms512M" which is default, but as per my thought it would be good to allow users to set the resource upper and lower limits as per the their own environment.

**Comment by prudhvigodithi** [comment]
Hey my point is if we have to add resources, it should be the same for both opensearch and opensearch-dashboard 
Example as
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
  dashboards:
    enable: true
    resources:
       requests:
          memory: "64Mi"
          cpu: "250m"
       limits:
         memory: "128Mi"
         cpu: "500m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30
      NodeSelector:
      resources:
         requests:
            memory: "64Mi"
            cpu: "250m"
         limits:
            memory: "128Mi"
            cpu: "500m"
      roles:
        - "data"
        - "master"
```
Key points 

- If we have to remove the option for  `requests`, then it should be for both opensearch and opensearch-dashboard as this makes easy for a user to declare resources for both opensearch and opensearch-dashboard

- we can consider adding as follows 
```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
  namespace: default
spec:
  general:
    serviceName: my-first-cluster
  dashboards:
    enable: true
    resources:
          memory: "64Mi"
          cpu: "250m"
  nodePools:
    - component: masters
      replicas: 3
      diskSize: 30
      NodeSelector:
      resources:
            memory: "64Mi"
            cpu: "250m"
      roles:
        - "data"
        - "master"

```
This will make sure both the limits and requests are set to values passed  in `memory:` and `cpu:` fields and allow node.Jvm to be half of this value.
https://github.com/Opster/opensearch-k8s-operator/blob/5c6610a6822cf162601990c7a9969fa11f25808a/opensearch-operator/pkg/builders/cluster.go#L123
**(still a user can override this with Jvm field)**

- Its definitely good to have both requests and limits to be passed during runtime, as this allows backend to use the required resources in range of declared requests and limits and not locking the max value even when not needed. 

I'm open for any inputs and suggestions here, so that I can modify my PR in accordingly :)
https://github.com/Opster/opensearch-k8s-operator/pull/69
