### ISSUE TITLE
[BUG] Can't use custom image in dashboards

### ISSUE THREAD

**Issue by Pigueiras** [Opster/opensearch-k8s-operator#992]
### What is the bug?

Since `spec.dashboards.version` is required I can't specify the `image` in the dashboard like this like you can do for other parameters:

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
...
  dashboards:
    image: "myregistry.example.org/opensearchproject/opensearch:2.18.0
    ...
```

It fails with: 

```
Error: INSTALLATION FAILED: 1 error occurred:
        * OpenSearchCluster.opensearch.opster.io "pigueira" is invalid: spec.dashboards.version: Required value
```

And if I specify a version:

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
...
  dashboards:
    image: "myregistry.example.org/opensearchproject/opensearch:2.18.0
    version: 2.18.0
    ...
```

The controller crashes with 

```
| operator-controller-manager {"level":"error","ts":"2025-04-10T10:03:45.394Z","msg":"unable to parse version, assuming >= 2.0.0","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchClust │
│ operator-controller-manager {"level":"error","ts":"2025-04-10T10:03:45.394Z","msg":"unable to parse version, assuming >= 2.0.0","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchClust │
│ operator-controller-manager {"level":"info","ts":"2025-04-10T10:03:45.394Z","msg":"admin cert does not exist, creating","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"na │
│ operator-controller-manager {"level":"info","ts":"2025-04-10T10:03:50.576Z","msg":"resource created","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io","controllerKind":"OpenSearchCluster","OpenSearchCluster":{"name":"pigueira","nam │
│ operator-controller-manager {"level":"info","ts":"2025-04-10T10:03:50.576Z","msg":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","controller":"opensearchcluster","controllerGroup":"opensearch.opster.io", │
│ operator-controller-manager panic: runtime error: invalid memory address or nil pointer dereference [recovered]                                                                                                                                                 │
│ operator-controller-manager     panic: runtime error: invalid memory address or nil pointer dereference                                                                                                                                                         │
│ operator-controller-manager [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1544b94]
```

And if I don't specify anything in the image then it tries to use latest (2.19.1), which also is not great either.

```
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
...
  dashboards:
    image: "myregistry.example.org/opensearchproject/opensearch
    version: 2.18.0
    ...
```

### How can one reproduce the bug?
The previous information should give enough hints to reproduce it.

### What is the expected behavior?
`dashboards` should work like `initContainers` and `general`

### What is your host/environment?
I am using operator 2.7.0

### Do you have any screenshots?
Not applicable

### Do you have any additional context?
Nope
