### ISSUE TITLE
Opensearch pods does not become ready without basic auth

### ISSUE THREAD

**Issue by ragu2003** [Opster/opensearch-k8s-operator#998]
I am trying to setup Opensearch cluster using the `opensearch-k8s-operator` without basic Auth. I will be using just jwt auth going forward.
Here is my configuration for the `opensearchcluster`:
```yaml
apiVersion: opensearch.opster.io/v1
kind: OpenSearchCluster
metadata:
  name: my-first-cluster
spec:
  general:
    serviceName: my-first-cluster
    image: opensearchproject/opensearch:2.17.0
    version: 2.17.0
  security:
    tls:
      http:
        caSecret:
          name: my-tls-secret
        generate: false
        secret:
          name: my-tls-secret
      transport:
        nodesDn:
          - "CN=node1.dns.a-record,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA"
        adminDn:
          - "CN=A,OU=UNIT,O=ORG,L=TORONTO,ST=ONTARIO,C=CA"
        caSecret:
          name: my-tls-secret
        generate: false
        secret:
            name: my-tls-secret
    config:
      securityConfigSecret:
        name: securityconfig-secret
      adminSecret:
        name: my-admin-tls-secret
  nodePools:
    - component: nodes
      replicas: 3
      diskSize: "1Gi"
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "500m"
      roles:
        - "cluster_manager"
        - "data"
```

`config.yml` in my security config:
```yaml
  config.yml: |-
    _meta:
      type: "config"
      config_version: 2
    config:
      dynamic:
        http:
          anonymous_auth_enabled: False
        authc:
          jwt_auth_domain:
            description: "Authenticate via Json Web Token"
            order: 0
            http_enabled: true
            transport_enabled: true
            http_authenticator:
              type: jwt
              challenge: false
              config:
                signing_key: |-
                  -----BEGIN PUBLIC KEY-----
                  { public key }
                  -----END PUBLIC KEY-----
                jwt_header: "Authorization"
                jwt_url_parameter: null
                roles_key: opensearch_roles
                subject_key: sub
            authentication_backend:
              type: noop
```

I am able to get it work if I add `basic_internal_auth_domain` in `config.yml`. But I don't want basic auth as it adds another setup overhead to create admin credentials. And to constantly rotate them.

The reason I think, it fails is because the readiness probe is trying to get the status using the basic auth credentials and it fails so the pods are stuck in non ready state.
```bash
exec [/bin/bash -c curl -k -u "$(cat /mnt/admin-credentials/username):$(cat /mnt/admin-credentials/password)" --silent --fail https://localhost:9200]
```

Is there any workaround for this?
